'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';
import CashBillControlled from './CashBillControlled';
type Product={id:string;name:string;sku:string|null;sales_price:number;default_tax_rate_id:string|null};
type Tax={id:string;name:string;rate:number};
type Account={id:string;code:string;name:string};
type TaxProfile={tax_regime:string|null;gst_registration_type:string|null;gstin:string|null};
type Line={product_service_id:string;quantity:number;unit_price:number;tax_rate_id:string};
const today=()=>new Date().toISOString().slice(0,10);
export default function CashBillPage(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[products,setProducts]=useState<Product[]>([]),[taxes,setTaxes]=useState<Tax[]>([]),[cashAccount,setCashAccount]=useState<Account|null>(null),[upiAccount,setUpiAccount]=useState<Account|null>(null),[taxRegistered,setTaxRegistered]=useState(false),[lines,setLines]=useState<Line[]>([]),[date,setDate]=useState(today()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[createdInvoiceId,setCreatedInvoiceId]=useState(''),[paymentMethod,setPaymentMethod]=useState<'cash'|'upi'>('cash');
 useEffect(()=>{(async()=>{const r=await supabase.rpc('get_my_business_context');const c=r.data?.[0] as BusinessContext|undefined;if(!c){location.href='/';return}setCtx(c);const[ps,ts,as,tp]=await Promise.all([supabase.from('products_services').select('id,name,sku,sales_price,default_tax_rate_id').eq('business_id',c.business_id).eq('is_active',true).order('name'),supabase.from('tax_rates').select('id,name,rate').eq('business_id',c.business_id).eq('is_active',true).order('rate'),supabase.from('accounts').select('id,code,name').eq('business_id',c.business_id).eq('is_active',true).order('code'),supabase.from('business_tax_profiles').select('tax_regime,gst_registration_type,gstin').eq('business_id',c.business_id).maybeSingle()]);setProducts(ps.data||[]);setTaxes(ts.data||[]);const accounts=(as.data||[]) as Account[];setCashAccount(accounts.find(a=>a.code==='1000')||null);setUpiAccount(accounts.find(a=>a.code!=='1000'&&/bank|upi|cash|wallet|current|savings/i.test(a.name))||accounts.find(a=>a.code!=='1000')||null);const profile=tp.data as TaxProfile|null;const registered=Boolean(profile&&profile.tax_regime&&profile.tax_regime!=='NONE'&&((profile.tax_regime!=='GST')||profile.gst_registration_type&&profile.gst_registration_type!=='NONE'));setTaxRegistered(registered);})();},[]);
 const add=()=>{const p=products[0];if(p)setLines(x=>[...x,{product_service_id:p.id,quantity:1,unit_price:Number(p.sales_price||0),tax_rate_id:taxRegistered?(p.default_tax_rate_id||''):''}])};
 const change=(i:number,k:keyof Line,v:any)=>setLines(x=>x.map((l,j)=>j===i?{...l,[k]:v}:l));
 const totals=useMemo(()=>{let subtotal=0,tax=0;for(const l of lines){const base=Number(l.quantity||0)*Number(l.unit_price||0);subtotal+=base;if(taxRegistered)tax+=base*(taxes.find(t=>t.id===l.tax_rate_id)?.rate||0)/100}return{subtotal,tax,total:subtotal+tax}},[lines,taxes,taxRegistered]);
 const save=async()=>{const settlementAccount=paymentMethod==='cash'?cashAccount:upiAccount;if(!ctx||!lines.length||totals.total<=0||!settlementAccount)return;setBusy(true);setError('');setSuccess('');setCreatedInvoiceId('');const cc=await supabase.rpc('get_or_create_cash_customer',{p_business_id:ctx.business_id});if(cc.error){setError(cc.error.message);setBusy(false);return}const customerId=cc.data;const inv=await supabase.rpc('create_invoice_from_items',{p_business_id:ctx.business_id,p_customer_id:customerId,p_invoice_date:date,p_due_date:date,p_items:lines.map(l=>taxRegistered?l:{...l,tax_rate_id:''}),p_invoice_discount_type:null,p_invoice_discount_value:0,p_notes:'Cash Bill',p_terms:'Paid in full at counter.'});if(inv.error){setError(inv.error.message);setBusy(false);return}const post=await supabase.rpc('post_invoice',{p_invoice_id:inv.data,p_location_id:null});if(post.error){setError(post.error.message);setBusy(false);return}const pay=await supabase.rpc('record_customer_payment',{p_business_id:ctx.business_id,p_customer_id:customerId,p_invoice_id:inv.data,p_amount:Number(totals.total),p_method:paymentMethod,p_account_id:settlementAccount.id,p_reference:null,p_payment_date:date,p_notes:`Cash Bill · ${paymentMethod.toUpperCase()}`});if(pay.error){setError(pay.error.message);setBusy(false);return}setSuccess(`Cash Bill created, posted and marked paid via ${paymentMethod==='cash'?'Cash':'UPI'}.`);setCreatedInvoiceId(String(inv.data));setLines([]);setDate(today());setPaymentMethod('cash');setBusy(false)};
 const newBill=()=>{setLines([]);setDate(today());setPaymentMethod('cash');setError('');setSuccess('');setCreatedInvoiceId('')};
 if(!ctx)return <div className="grid min-h-screen place-items-center"><span className="text-sm text-slate-500">Loading cash bill workspace…</span></div>;
 return <CashBillControlled date={date} setDate={setDate} lines={lines} products={products} taxes={taxes} taxRegistered={taxRegistered} totals={totals} busy={busy} cashAccount={cashAccount} upiAccount={upiAccount} paymentMethod={paymentMethod} setPaymentMethod={setPaymentMethod} error={error} success={success} createdInvoiceId={createdInvoiceId} add={add} change={change} remove={i=>setLines(x=>x.filter((_,j)=>j!==i))} save={save} newBill={newBill}/>;
}
