'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

type Receipt={id:string;receipt_number:string;receipt_date:string;amount:number;payment_method:string|null;reference_number:string|null;customer_id:string|null;payment_id:string|null};
type Customer={id:string;display_name:string};
type Payment={id:string;invoice_id:string|null;amount:number;reference:string|null};
type Invoice={id:string;invoice_number:string;total:number;amount_paid:number;balance_due:number};

export default function Receipts(){
 const[rows,setRows]=useState<Receipt[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[payments,setPayments]=useState<Payment[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[q,setQ]=useState(''),[pageSize,setPageSize]=useState('20'),[page,setPage]=useState(1),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}const[r,cu]=await Promise.all([supabase.from('receipts').select('id,receipt_number,receipt_date,amount,payment_method,reference_number,customer_id,payment_id').eq('business_id',b.business_id).order('receipt_date',{ascending:false}).limit(500),supabase.from('customers').select('id,display_name').eq('business_id',b.business_id).eq('is_active',true).order('display_name')]);const paymentIds=(r.data||[]).map((x:Receipt)=>x.payment_id).filter(Boolean);const[p]=paymentIds.length?[await supabase.from('payments').select('id,invoice_id,amount,reference').eq('business_id',b.business_id).in('id',paymentIds)]:[{data:[]} as any];const invoiceIds=(p.data||[]).map((x:Payment)=>x.invoice_id).filter(Boolean);const[i]=invoiceIds.length?[await supabase.from('invoices').select('id,invoice_number,total,amount_paid,balance_due').eq('business_id',b.business_id).in('id',invoiceIds)]:[{data:[]} as any];setRows(r.data||[]);setCustomers(cu.data||[]);setPayments(p.data||[]);setInvoices(i.data||[]);setLoading(false)})()},[]);
 const name=(id:string|null)=>customers.find(x=>x.id===id)?.display_name||'Customer';
 const payment=(id:string|null)=>payments.find(x=>x.id===id);
 const invoice=(id:string|null)=>invoices.find(x=>x.id===id);
 const filtered=useMemo(()=>rows.filter(x=>`${x.receipt_number} ${name(x.customer_id)} ${x.reference_number||''} ${x.payment_method||''} ${invoice(payment(x.payment_id)?.invoice_id||null)?.invoice_number||''}`.toLowerCase().includes(q.toLowerCase())),[rows,customers,payments,invoices,q]);
 useEffect(()=>setPage(1),[q,pageSize]);
 const total=rows.reduce((a,x)=>a+Number(x.amount||0),0);const size=pageSize==='all'?filtered.length:Number(pageSize);const pages=Math.max(1,Math.ceil(filtered.length/Math.max(size,1)));const visible=pageSize==='all'?filtered:filtered.slice((page-1)*size,page*size);
 const openReceipt=(id:string)=>{location.href=`/next-workspace/documents?type=receipt&id=${id}`};
 const copyLink=async(id:string)=>{const url=`${location.origin}/next-workspace/documents?type=receipt&id=${id}`;try{await navigator.clipboard.writeText(url);window.alert('Receipt link copied.')}catch{window.prompt('Copy receipt link',url)}};
 const shareReceipt=async(id:string)=>{const url=`${location.origin}/next-workspace/documents?type=receipt&id=${id}`;const r=rows.find(x=>x.id===id);try{if(navigator.share)await navigator.share({title:`Receipt ${r?.receipt_number||''}`,text:`Payment receipt ${r?.receipt_number||''} · ${money(r?.amount||0)}`,url});else await navigator.clipboard.writeText(url)}catch{/* cancelled */}};
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading receipts…</div>;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1350px]">
  <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Money received</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Receipts</h1><p className="mt-2 text-sm text-slate-500">Every receipt is generated from a recorded payment and stays linked to the customer, invoice and ledger entry.</p></div><button onClick={()=>location.href='/next-workspace/payments'} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">＋ Record payment</button></header>
  <div className="grid gap-4 sm:grid-cols-3"><K title="Receipts" value={String(rows.length)} note="Recorded receipts"/><K title="Total received" value={money(total)} note="Receipt value"/><K title="Current view" value={pageSize==='all'?String(filtered.length):`${Math.min((page-1)*size+1,filtered.length)}–${Math.min(page*size,filtered.length)}`} note={`${filtered.length} matching receipts`}/></div>
  <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search receipt, customer, invoice or reference…" className="flex-1 rounded-xl border border-slate-200 bg-[#fbfaff] px-3 py-2.5 text-sm outline-none"/><label className="flex items-center gap-2 text-xs font-semibold text-slate-500">Show<select value={pageSize} onChange={e=>setPageSize(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-700"><option value="20">20</option><option value="50">50</option><option value="100">100</option><option value="all">All</option></select></label></div>
   <div className="hidden grid-cols-[125px_110px_1fr_150px_125px_150px] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>Receipt</span><span>Date</span><span>Customer / Invoice</span><span>Method</span><span className="text-right">Amount</span><span className="text-right">Actions</span></div>
   <div className="divide-y divide-slate-100">{visible.map(r=>{const p=payment(r.payment_id),i=invoice(p?.invoice_id||null);return <div key={r.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[125px_110px_1fr_150px_125px_150px] sm:items-center sm:gap-3 sm:px-5"><div><button onClick={()=>openReceipt(r.id)} className="text-left text-sm font-bold text-violet-700 hover:underline">{r.receipt_number}</button><div className="mt-1 text-[10px] text-slate-400">Receipt</div></div><span className="text-xs text-slate-500">{r.receipt_date}</span><span><b className="block text-sm">{name(r.customer_id)}</b><span className="text-xs text-slate-400">{i?.invoice_number||'No invoice linked'}{r.reference_number?` · ${r.reference_number}`:''}</span></span><span className="text-xs capitalize text-slate-500">{String(r.payment_method||'—').replaceAll('_',' ')}</span><b className="text-sm text-emerald-700 sm:text-right">{money(r.amount)}</b><div className="flex flex-wrap gap-1.5 sm:justify-end"><button onClick={()=>openReceipt(r.id)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[11px] font-semibold text-slate-700">View</button><button onClick={()=>shareReceipt(r.id)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[11px] font-semibold text-slate-700">Share</button><button onClick={()=>copyLink(r.id)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[11px] font-semibold text-slate-700">Copy link</button></div></div>})}{!visible.length&&<div className="p-12 text-center text-sm text-slate-500">No receipts found.</div>}</div>
   {filtered.length>0&&pageSize!=='all'&&<div className="flex flex-col gap-3 border-t border-slate-100 px-4 py-3 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(x=>Math.max(1,x-1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Next</button></div></div>}
  </section></div></main>;
}
function K({title,value,note}:{title:string;value:string;note:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-semibold text-slate-500">{title}</span><b className="mt-3 block text-2xl tracking-tight">{value}</b><span className="mt-1 block text-xs text-slate-400">{note}</span></section>}
