'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

type Doc='invoice'|'quotation'|'receipt';
type Template={id:string;document_type:Doc;template_key:string;template_name:string;description:string|null};
type Business={id:string;name:string;brand_primary_color:string;brand_secondary_color:string;brand_accent_color:string;logo_storage_path:string|null};
type DocPref={document_type:Doc;template_id:string|null;custom_fields:any};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100';
const names:Record<string,string>={bold:'Bold',classic:'Classic',compact:'Compact',minimal:'Minimal',modern:'Modern'};

function TemplateCard({t,selected,onClick,type}:{t:Template;selected:boolean;onClick:()=>void;type:Doc}){
 const k=t.template_key;
 const title=type==='invoice'?(k==='classic'?'INVOICE':'TAX INVOICE'):'ESTIMATE';
 return <button onClick={onClick} className={`w-[180px] shrink-0 rounded-2xl border bg-white p-2 text-left transition ${selected?'border-violet-600 ring-2 ring-violet-100':'border-slate-200 hover:border-violet-300'}`}>
  <div className="relative h-[230px] overflow-hidden rounded-xl border bg-white p-3 text-[6px] text-slate-600">
   {k==='bold'&&<div className="absolute inset-x-0 top-0 h-12 bg-slate-800"/>}
   {k==='modern'&&<div className="absolute inset-x-0 top-0 h-2 bg-violet-600"/>}
   {k==='minimal'&&<div className="absolute left-3 right-3 top-14 border-t border-slate-200"/>}
   {k==='compact'&&<div className="absolute inset-x-3 top-3 h-8 border-b-2 border-slate-700"/>}
   {k==='classic'&&<div className="absolute inset-x-3 top-10 border-b-2 border-slate-800"/>}
   <div className={`relative flex items-start justify-between ${k==='bold'?'pt-1 text-white':'pt-1'}`}><div><b>{'BUSINESS NAME'}</b><div className="mt-1 text-[5px]">Address · Phone · GSTIN</div></div><div className="text-right font-bold">{title}<div className="font-normal">INV-2026-0042</div></div></div>
   <div className="mt-7 grid grid-cols-2 gap-2"><div><b>Bill to</b><div>Rahul Sharma</div><div>customer@email.com</div></div><div className="text-right"><b>Date</b><div>21 Aug 2026</div><b>Due</b><div>20 Sep 2026</div></div></div>
   <div className={`mt-5 overflow-hidden border ${k==='compact'?'rounded-none':'rounded-md'}`}><div className={`grid grid-cols-[1fr_28px_42px] px-2 py-1 font-bold text-white ${k==='bold'?'bg-slate-800':k==='modern'?'bg-violet-600':'bg-slate-700'}`}><span>Description</span><span>Qty</span><span className="text-right">Amount</span></div>{[1,2,3].map(i=><div key={i} className="grid grid-cols-[1fr_28px_42px] border-t border-slate-100 px-2 py-1"><span>Service item {i}</span><span>1</span><span className="text-right">₹2,500</span></div>)}</div>
   <div className="mt-3 ml-auto w-24 space-y-1 text-right"><div>Subtotal ₹7,500</div><div>GST ₹1,350</div><b>Total ₹8,850</b></div>
   <div className="absolute bottom-3 left-3 right-3 border-t border-slate-200 pt-2 text-[5px] text-slate-400">Terms & conditions · Thank you for your business</div>
  </div><div className="px-1 pt-2"><b className="block text-sm">{names[k]||t.template_name}</b><span className="text-[10px] text-slate-400">{t.description||'Professional layout'}</span></div>
 </button>
}

function ReceiptPreview({t,selected,onClick}:{t:Template;selected:boolean;onClick:()=>void}){const k=t.template_key;return <button onClick={onClick} className={`w-[180px] shrink-0 rounded-2xl border bg-white p-2 text-left ${selected?'border-violet-600 ring-2 ring-violet-100':'border-slate-200 hover:border-violet-300'}`}><div className="relative h-[230px] overflow-hidden rounded-xl border bg-white p-4 text-[6px] text-slate-600"><div className={`mx-auto flex h-10 w-10 items-center justify-center rounded-full text-white ${k==='bold'?'bg-slate-900':k==='modern'?'bg-violet-600':k==='compact'?'bg-slate-700':k==='minimal'?'bg-slate-400':'bg-slate-800'}`}>✓</div><div className="mt-3 text-center text-base font-black text-slate-900">PAYMENT RECEIPT</div><div className="mt-1 text-center text-[6px]">REC-2026-0091 · 21 Aug 2026</div><div className="mx-auto mt-5 w-32 rounded-xl border p-3 text-center"><div className="text-[5px] uppercase tracking-wider text-slate-400">Amount received</div><b className="mt-1 block text-xl text-slate-900">₹8,850</b><div className="mt-1">Paid via UPI</div></div><div className="mt-5 space-y-1"><div><b>Received from:</b> Rahul Sharma</div><div><b>Against:</b> INV-2026-0042</div><div><b>Reference:</b> UPI123456789</div></div><div className="absolute bottom-3 left-4 right-4 border-t pt-2 text-center text-[5px] text-slate-400">This receipt confirms payment received.</div></div><div className="px-1 pt-2"><b className="block text-sm">{names[k]||t.template_name}</b><span className="text-[10px] text-slate-400">Payment-focused receipt</span></div></button>}

export default function InvoiceEstimateSettings(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[business,setBusiness]=useState<Business|null>(null),[settings,setSettings]=useState<any>({invoice_prefix:'INV-',estimate_prefix:'EST-',receipt_prefix:'RCT-',invoice_due_days:0,invoice_notes:'',default_payment_terms:'Due on receipt'}),[prefs,setPrefs]=useState<any>({tax_mode:'auto',default_payment_reminders:true,default_reminder_days:3}),[templates,setTemplates]=useState<Template[]>([]),[docPrefs,setDocPrefs]=useState<Record<string,DocPref>>({}),[tab,setTab]=useState<'general'|'invoice'|'estimate'|'receipt'>('general'),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const c=await supabase.rpc('get_my_business_context');const b=(c.data?.[0]||null) as BusinessContext|undefined;if(!b)return;setCtx(b);const [br,s,p,t,d]=await Promise.all([supabase.from('businesses').select('id,name,brand_primary_color,brand_secondary_color,brand_accent_color,logo_storage_path').eq('id',b.business_id).single(),supabase.from('business_settings').select('invoice_prefix,estimate_prefix,receipt_prefix,invoice_due_days,invoice_notes,default_payment_terms').eq('business_id',b.business_id).maybeSingle(),supabase.from('business_preferences').select('tax_mode,default_payment_reminders,default_reminder_days').eq('business_id',b.business_id).maybeSingle(),supabase.from('document_templates').select('id,document_type,template_key,template_name,description').eq('is_system',true).eq('is_active',true).order('template_name'),supabase.from('business_document_preferences').select('document_type,template_id,custom_fields').eq('business_id',b.business_id)]);setBusiness(br.data as Business);setSettings(s.data||settings);setPrefs(p.data||prefs);setTemplates((t.data||[]) as Template[]);const m:Record<string,DocPref>={};(d.data||[]).forEach((x:any)=>m[x.document_type]=x);setDocPrefs(m)};
 useEffect(()=>{load()},[]);
 const setS=(k:string,v:any)=>setSettings((x:any)=>({...x,[k]:v}));const setCF=(type:Doc,k:string,v:any)=>setDocPrefs(x=>({...x,[type]:{...(x[type]||{document_type:type,template_id:null,custom_fields:{}}),custom_fields:{...(x[type]?.custom_fields||{}),[k]:v}}}));
 async function save(){if(!ctx||!business)return;setSaving(true);setMessage('');const s=await supabase.from('business_settings').upsert({...settings,business_id:ctx.business_id},{onConflict:'business_id'});const p=await supabase.from('business_preferences').upsert({...prefs,business_id:ctx.business_id},{onConflict:'business_id'});for(const type of ['invoice','quotation','receipt'] as Doc[]){const d=docPrefs[type];if(d?.template_id)await supabase.from('business_document_preferences').upsert({business_id:ctx.business_id,document_type:type,template_id:d.template_id,custom_fields:d.custom_fields||{}},{onConflict:'business_id,document_type'});}setMessage(s.error?.message||p.error?.message?'Some settings could not be saved.':'Settings saved.');setSaving(false)}
 const pick=(type:Doc,id:string)=>setDocPrefs(x=>({...x,[type]:{...(x[type]||{document_type:type,custom_fields:{}}),document_type:type,template_id:id,custom_fields:x[type]?.custom_fields||{}}}));
 const current=(type:Doc)=>templates.filter(t=>t.document_type===type);const cf=(type:Doc,k:string,d:any)=>docPrefs[type]?.custom_fields?.[k]??d;
 if(!business)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading document settings…</div>;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-6"><div className="mx-auto max-w-7xl"><header className="mb-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Settings · Sales & Payments</p><h1 className="mt-1 text-2xl font-semibold">Invoices & estimates</h1><p className="mt-1 text-sm text-slate-500">Configure document defaults without a long scrolling settings page.</p></header><div className="grid gap-5 lg:grid-cols-[190px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-2 lg:sticky lg:top-24"><div className="mb-2 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">Settings</div>{[['general','General settings'],['invoice','Invoice settings'],['estimate','Estimate settings'],['receipt','Receipt settings']].map(([v,l])=><button key={v} onClick={()=>setTab(v as any)} className={`mb-1 w-full rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${tab===v?'bg-violet-50 text-violet-800':'text-slate-600 hover:bg-violet-50'}`}>{l}</button>)}<div className="mt-3 border-t border-slate-100 px-3 pt-3 text-[10px] text-slate-400">Templates are shared visually between invoices and estimates; the document heading changes automatically.</div></aside><section className="min-w-0">
 {tab==='general'&&<Panel title="General settings" subtitle="Business identity and the five core layouts."><div className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-4"><b className="text-sm">Brand</b><div className="mt-3 grid gap-3"><div className="flex items-center gap-3"><div className="grid h-16 w-20 place-items-center rounded-xl border bg-slate-50">{business.logo_storage_path?<span className="text-[9px] text-slate-400">Business logo</span>:<span className="text-[9px] text-slate-400">No logo</span>}</div><div><b>{business.name}</b><p className="text-xs text-slate-400">Logo and legal details are managed in Brand & Templates.</p></div></div><label className="text-xs font-semibold">Accent colour<input type="color" value={business.brand_accent_color||'#7c3aed'} onChange={e=>setBusiness({...business,brand_accent_color:e.target.value})} className="mt-1 h-10 w-full rounded-lg border p-1"/></label></div></div><div className="rounded-2xl border border-slate-200 p-4"><b className="text-sm">Invoice / estimate layouts</b><p className="mt-1 text-xs text-slate-400">Five ready layouts. Pick once; invoice and estimate use the same structure with the correct heading.</p><div className="mt-3 flex gap-3 overflow-x-auto pb-2">{current('invoice').map(t=><TemplateCard key={t.id} t={t} type="invoice" selected={docPrefs.invoice?.template_id===t.id} onClick={()=>pick('invoice',t.id)}/>)}</div></div></div></Panel>}
 {tab==='invoice'&&<Panel title="Invoice settings" subtitle="Defaults applied to new invoices. GST mode automatically changes the heading to Tax Invoice."><div className="grid gap-4 md:grid-cols-2"><Field label="Default payment terms"><select className={input} value={settings.default_payment_terms||'Due on receipt'} onChange={e=>setS('default_payment_terms',e.target.value)}><option>Due on receipt</option><option>Net 7</option><option>Net 15</option><option>Net 30</option><option>Net 45</option></select></Field><Field label="Default invoice title"><input className={input} value={cf('invoice','title','Invoice')} onChange={e=>setCF('invoice','title',e.target.value)}/></Field><Field label="Default subheading"><input className={input} value={cf('invoice','subheading','Internet Service Provider')} onChange={e=>setCF('invoice','subheading',e.target.value)}/></Field><Field label="Default footer"><input className={input} value={cf('invoice','footer','This is a computer generated invoice.')} onChange={e=>setCF('invoice','footer',e.target.value)}/></Field><div className="md:col-span-2"><Field label="Default notes / terms"><textarea className={`${input} min-h-24`} value={settings.invoice_notes||''} onChange={e=>setS('invoice_notes',e.target.value)} placeholder="Bank details, payment instructions, terms…"/></Field></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Toggle label="Show Pay Now button" help="UI placeholder for payment-gateway integration. No gateway is required yet." checked={cf('invoice','show_pay_now',true)} onChange={v=>setCF('invoice','show_pay_now',v)}/><Toggle label="Show QR / Scan to Pay" help="UI placeholder; QR will use the payment gateway once integrated." checked={cf('invoice','show_payment_qr',true)} onChange={v=>setCF('invoice','show_payment_qr',v)}/></div><div className="mt-5 rounded-2xl border border-dashed border-violet-200 bg-violet-50 p-4 text-sm text-violet-900"><b>Payment integration placeholder</b><p className="mt-1 text-xs text-violet-700">The invoice layout reserves space for Pay Now + QR. We will connect the actual amount, payment link and QR generation when the payment API is integrated.</p></div></Panel>}
 {tab==='estimate'&&<Panel title="Estimate settings" subtitle="Estimates use the same five visual layouts as invoices, with ESTIMATE as the heading."><div className="grid gap-4 md:grid-cols-2"><Field label="Default estimate title"><input className={input} value={cf('quotation','title','Estimate')} onChange={e=>setCF('quotation','title',e.target.value)}/></Field><Field label="Default subheading"><input className={input} value={cf('quotation','subheading','Quotation / Proposal')} onChange={e=>setCF('quotation','subheading',e.target.value)}/></Field><Field label="Default footer"><input className={input} value={cf('quotation','footer','This estimate is valid for the stated validity period.')} onChange={e=>setCF('quotation','footer',e.target.value)}/></Field><Field label="Default notes / terms"><textarea className={`${input} min-h-24`} value={cf('quotation','notes','Thank you for the opportunity.')} onChange={e=>setCF('quotation','notes',e.target.value)}/></Field></div><div className="mt-5 flex gap-3 overflow-x-auto pb-2">{current('quotation').map(t=><TemplateCard key={t.id} t={t} type="quotation" selected={docPrefs.quotation?.template_id===t.id} onClick={()=>pick('quotation',t.id)}/>)}</div></Panel>}
 {tab==='receipt'&&<Panel title="Receipt settings" subtitle="Receipts are intentionally payment-focused and do not reuse the invoice table layout."><div className="grid gap-4 md:grid-cols-2"><Field label="Default receipt title"><input className={input} value={cf('receipt','title','Payment Receipt')} onChange={e=>setCF('receipt','title',e.target.value)}/></Field><Field label="Default footer"><input className={input} value={cf('receipt','footer','This receipt confirms payment received.')} onChange={e=>setCF('receipt','footer',e.target.value)}/></Field><div className="md:col-span-2"><Field label="Default notes"><textarea className={`${input} min-h-20`} value={cf('receipt','notes','Thank you for your payment.')} onChange={e=>setCF('receipt','notes',e.target.value)}/></Field></div></div><div className="mt-5 flex gap-3 overflow-x-auto pb-2">{current('receipt').map(t=><ReceiptPreview key={t.id} t={t} selected={docPrefs.receipt?.template_id===t.id} onClick={()=>pick('receipt',t.id)}/>)}</div></Panel>}
 <div className="sticky bottom-3 mt-4 flex items-center gap-3 rounded-2xl border border-violet-100 bg-white/95 p-3 shadow-lg backdrop-blur"><span className="mr-auto text-sm text-emerald-700">{message}</span><button disabled={saving} onClick={save} className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save all changes'}</button></div></section></div></div></main>;
}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>}
function Toggle({label,help,checked,onChange}:{label:string;help:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex cursor-pointer items-center justify-between rounded-2xl border border-slate-200 p-4"><span><b className="text-sm">{label}</b><span className="mt-1 block text-xs text-slate-400">{help}</span></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-5 w-5 accent-violet-600"/></label>}
