import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const ubl=await readFile(new URL('lib/server/documents/ubl/serialize.ts',root),'utf8');
const cii=await readFile(new URL('lib/server/documents/factur-x/cii.ts',root),'utf8');
const pdf=await readFile(new URL('lib/server/documents/factur-x/pdf-a3.ts',root),'utf8');
const migration=await readFile(new URL('supabase/migrations/20261003130000_strategic_gap_einvoice_endpoints_v1.sql',root),'utf8');
const ublRoute=await readFile(new URL('app/api/documents/invoices/[id]/ubl/route.ts',root),'utf8');
const fxRoute=await readFile(new URL('app/api/documents/invoices/[id]/factur-x/route.ts',root),'utf8');
test('PEPPOL UBL serializer contains mandatory Billing 3.0 identifiers and terms',()=>{for(const x of ['PEPPOL_CUSTOMIZATION_ID','PEPPOL_PROFILE_ID','AccountingSupplierParty','AccountingCustomerParty','EndpointID','TaxTotal','LegalMonetaryTotal','InvoiceLine'])assert.ok(ubl.includes(x),x);assert.match(ubl,/urn:oasis:names:specification:ubl:schema:xsd:Invoice-2/);});
test('PEPPOL EAS scheme validation is explicit',()=>{assert.match(ubl,/const EAS = new Set/);assert.match(ubl,/EAS\.has/);});
test('Factur-X CII uses EN16931 guideline and CII namespaces',()=>{assert.match(cii,/CrossIndustryInvoice:100/);assert.match(cii,/ReusableAggregateBusinessInformationEntity:100/);assert.match(cii,/urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:en16931/);});
test('PDF/A-3 container embeds Factur-X XML as Alternative with output intent and XMP',()=>{for(const x of ['/AFRelationship /Alternative','/EmbeddedFiles','factur-x.xml','/DestOutputProfile','pdfaid:part>3','pdfaid:conformance>B','urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#'])assert.ok(pdf.includes(x),x);assert.match(pdf,/1\.09\.2/);});
test('Endpoint fields and entitlement gates are database-backed',()=>{assert.match(migration,/e_invoice_endpoint_id/);assert.match(migration,/e_invoice_endpoint_scheme/);assert.match(migration,/e_invoice_endpoint_pair_chk/);assert.match(ublRoute,/e_invoicing_enabled/);assert.match(fxRoute,/e_invoicing_enabled/);});