'use client';
import {useEffect,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';
type Item={id:string;name:string;sku:string|null;barcode:string|null;sales_price:number;category_id:string|null};
export default function Barcodes(){const[ctx,setCtx]=useState<BusinessContext|null>(null),[items,setItems]=useState<Item[]>([]),[templates,setTemplates]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[qty,setQty]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[company,setCompany]=useState('Business');
async function load(){const c=await supabase.rpc('get_my_business_context');const b=(c.data||[])[0] as BusinessContext|undefined;if(!b)return;setCtx(b);const [i,t,br]=await Promise.all([supabase.from('products_services').select('id,name,sku,barcode,sales_price,category_id').eq('business_id',b.business_id).eq('is_active',true).order('name'),supabase.from('barcode_print_templates').select('*').eq('business_id',b.business_id).order('name'),supabase.from('businesses').select('name').eq('id',b.business_id).single()]);setItems(i.data||[]);setTemplates(t.data||[]);setCompany(br.data?.name||'Business')}useEffect(()=>{load()},[]);
async function saveTemplate(){if(!ctx)return;setBusy(true);const r=await supabase.from('barcode_print_templates').insert({business_id:ctx.business_id,name:'Standard 50×25',media_type:'thermal_roll',label_width_mm:50,label_height_mm:25,labels_across:1,labels_down:1,show_company_name:true,show_item_name:true,show_selling_price:true,show_mrp:true,barcode_format:'CODE128'});if(r.error)setError(r.error.message);else await load();setBusy(false)}
function print(){window.print()}
return (<main className="min-h-screen bg-slate-50 p-4 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">Physical operations</p><h1 className="mt-1 text-3xl font-semibold">Barcode Printing</h1><p className="mt-1 text-sm text-slate-500">Select catalog items, choose quantities, and print thermal-style labels.</p></div><div className="flex gap-2"><button className="rounded-xl border bg-white px-4 py-2 text-sm" onClick={saveTemplate} disabled={busy}>+ Template</button><button className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" onClick={print}>Print labels</button></div></header>{error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="grid gap-5 lg:grid-cols-[1fr_420px]"><section className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between"><b>Catalog</b><label className="text-xs">Copies <input className="ml-2 w-20 rounded border p-2" type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="mt-3 divide-y">{items.map(x=><label key={x.id} className="flex items-center gap-3 py-3 text-sm"><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,x.id]:s.filter(id=>id!==x.id))}/><span className="flex-1"><b>{x.name}</b><span className="ml-2 text-xs text-slate-400">{x.sku||'No SKU'} · {x.barcode||'No barcode'}</span></span><span>₹{Number(x.sales_price||0).toLocaleString('en-IN')}</span></label>)}</div></section><section className="rounded-2xl border bg-white p-4 print-area"><b>Label preview</b><div className="mt-3 grid grid-cols-2 gap-2">{selected.flatMap(id=>Array.from({length:qty},()=>items.find(x=>x.id===id))).filter(Boolean).map((x:any,i)=><div key={i} className="barcode-label border border-dashed border-slate-400 p-2 text-center text-[10px]"><div className="font-bold">{company}</div><div>{x.name}</div><div className="mt-1 text-base tracking-[.18em]">|||||||||||||</div><div className="font-mono">{x.barcode||x.sku||x.id.slice(0,8)}</div><div>₹{Number(x.sales_price||0).toLocaleString('en-IN')}</div></div>))}</div>{!selected.length&&<p className="py-12 text-center text-sm text-slate-400">Select items to preview labels.</p>}</section></div></div><style jsx global>{'@media print{body *{visibility:hidden}.print-area,.print-area *{visibility:visible}.print-area{position:absolute;left:0;top:0;width:100%}.barcode-label{break-inside:avoid}}'}</style></main>);
}