'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/lib/workspace-context';
import { EmptyState, ErrorState, LoadingState } from '../workspace-ui';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
type Invoice={id:string;invoice_number:string;invoice_date:string;due_date:string;total:number;balance_due:number;customer_id:string;status:string};
type Customer={id:string;display_name:string;phone:string|null};
type Row=Invoice & {customer?:Customer;age:number;priority:'Critical'|'High'|'Medium'|'Upcoming'};

export default function Collections(){
 const{business,loading:workspaceLoading}=useWorkspace();
 const[invoices,setInvoices]=useState<Invoice[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!business){setLoading(false);return}let alive=true;(async()=>{const[i,c]=await Promise.all([supabase.from('invoices').select('id,invoice_number,invoice_date,due_date,total,balance_due,customer_id,status').eq('business_id',business.business_id).gt('balance_due',0).order('due_date',{ascending:true}).limit(200),supabase.from('customers').select('id,display_name,phone').eq('business_id',business.business_id).eq('is_active',true)]);if(!alive)return;const e=i.error||c.error;if(e)setError(e.message);setInvoices(i.data||[]);setCustomers(c.data||[]);setLoading(false)})();return()=>{alive=false}},[business]);
 const rows=useMemo<Row[]>(()=>invoices.map(i=>{const customer=customers.find(c=>c.id===i.customer_id);const age=Math.max(0,Math.floor((Date.now()-new Date(i.due_date).getTime())/86400000));const priority:Row['priority']=i.status==='overdue'?(age>=30?'Critical':age>=7?'High':'Medium'):'Upcoming';return{...i,customer,age,priority}}).sort((a,b)=>({Critical:0,High:1,Medium:2,Upcoming:3}[a.priority]-({Critical:0,High:1,Medium:2,Upcoming:3}[b.priority]))),[invoices,customers]);
 if(workspaceLoading||loading)return <LoadingState label="Building collections queue…"/>;
 if(!business)return <div className="p-6"><ErrorState message="No business workspace is active."/></div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]"><header className="mb-7"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Money in</p><h1 className="mt-1 text-3xl font-semibold">Collections</h1><p className="mt-2 text-sm text-slate-500">Work from customer action and priority—not from a raw overdue list.</p></header>{error&&<div className="mb-5"><ErrorState message={error}/></div>}<div className="grid gap-4 sm:grid-cols-3"><K title="Outstanding" value={money(rows.reduce((a,x)=>a+Number(x.balance_due||0),0))}/><K title="Overdue" value={String(rows.filter(x=>x.priority!=='Upcoming').length)}/><K title="Critical" value={String(rows.filter(x=>x.priority==='Critical').length)}/></div><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white">{!rows.length?<EmptyState title="Collections are clear" description="There are no outstanding customer balances in the current workspace."/>:<div className="divide-y divide-slate-100">{rows.map(row=><div key={row.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_120px_120px_150px_110px] lg:items-center"><div><b className="block text-sm">{row.customer?.display_name||'Customer'}</b><span className="text-xs text-slate-400">{row.invoice_number} · Due {row.due_date}</span></div><span className="text-sm font-semibold">{money(row.balance_due)}</span><span className="text-xs text-slate-500">{row.age?`${row.age} days overdue`:'Due soon'}</span><span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${row.priority==='Critical'?'bg-rose-100 text-rose-700':row.priority==='High'?'bg-amber-100 text-amber-700':row.priority==='Medium'?'bg-violet-100 text-violet-700':'bg-slate-100 text-slate-600'}`}>{row.priority}</span></span><button onClick={()=>{window.location.href=`/next-workspace/customers/${row.customer_id}/statement`}} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-violet-50">Customer action →</button></div>)}</div>}</section></div></main>;
}
function K({title,value}:{title:string;value:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-semibold text-slate-500">{title}</span><b className="mt-3 block text-2xl tracking-tight">{value}</b></section>}
