import type { ReportTemplate } from '@/lib/reports/report-definitions';

export const SALES_TEMPLATES: ReportTemplate[] = [
 {id:'sales-register',category:'Sales & Receivables',title:'Sales Register',description:'Posted invoice activity with customer, tax and outstanding values.',tags:['Sales','GST','Receivables'],source:'invoices',dateField:'invoice_date',allowedGroups:['none','customer','date'],statusOptions:['all','draft','sent','partially_paid','paid','overdue','void'],searchFields:['invoice_number','customer','status'],columns:[
  {key:'invoice_number',label:'Invoice',kind:'text'},{key:'invoice_date',label:'Date',kind:'date'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'status',label:'Status',kind:'status'},{key:'subtotal',label:'Subtotal',kind:'money'},{key:'tax',label:'Tax',kind:'money'},{key:'total',label:'Total',kind:'money'},{key:'balance',label:'Balance',kind:'money'}],
  kpis:[{key:'volume',label:'Total Volume',kind:'sum',field:'total',format:'money'},{key:'net',label:'Net Sales',kind:'sum',field:'subtotal',format:'money'},{key:'tax',label:'Tax Collected',kind:'sum',field:'tax',format:'money'},{key:'avg',label:'Average Order',kind:'avg',field:'total',format:'money'}]
 },
 {id:'aging-summary',category:'Sales & Receivables',title:'Aging Summary',description:'Open receivables bucketed by days outstanding as of the selected end date.',tags:['AR','Collections','Aging'],source:'aging',dateField:'due_date',allowedGroups:['none','customer','date'],statusOptions:['all','sent','partially_paid','overdue'],searchFields:['invoice_number','customer','bucket'],columns:[
  {key:'invoice_number',label:'Invoice',kind:'text'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'invoice_date',label:'Invoice Date',kind:'date'},{key:'due_date',label:'Due Date',kind:'date'},{key:'bucket',label:'Aging Bucket',kind:'status'},{key:'total',label:'Invoice Total',kind:'money'},{key:'balance',label:'Outstanding',kind:'money'},{key:'days_overdue',label:'Days Overdue',kind:'number'}],
  kpis:[{key:'outstanding',label:'Outstanding',kind:'sum',field:'balance',format:'money'},{key:'overdue',label:'Overdue',kind:'sum',field:'overdue',format:'money'},{key:'invoices',label:'Open Invoices',kind:'count',format:'number'},{key:'avg',label:'Average Balance',kind:'avg',field:'balance',format:'money'}]
 },
 {id:'sales-by-item',category:'Sales & Receivables',title:'Sales by Item',description:'Line-level product and service sales with quantity, tax and HSN/SAC.',tags:['Items','Inventory','HSN/SAC'],source:'invoice_items',dateField:'invoice_date',allowedGroups:['none','customer','date','tax_slab'],statusOptions:['all','posted'],searchFields:['item','sku','customer','hsn_sac','tax_slab'],columns:[
  {key:'invoice_date',label:'Date',kind:'date'},{key:'item',label:'Item / Service',kind:'text'},{key:'sku',label:'SKU',kind:'text'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'quantity',label:'Qty',kind:'number'},{key:'net',label:'Net Value',kind:'money'},{key:'tax',label:'Tax',kind:'money'},{key:'total',label:'Gross Value',kind:'money'},{key:'tax_slab',label:'Tax Slab',kind:'status',groupKey:'tax_slab'},{key:'hsn_sac',label:'HSN/SAC',kind:'text'}],
  kpis:[{key:'qty',label:'Quantity Sold',kind:'sum',field:'quantity',format:'number'},{key:'net',label:'Net Value',kind:'sum',field:'net',format:'money'},{key:'tax',label:'Tax Collected',kind:'sum',field:'tax',format:'money'},{key:'avg',label:'Average Line Value',kind:'avg',field:'total',format:'money'}]
 },
 {id:'customer-statement',category:'Sales & Receivables',title:'Customer Statement',description:'Invoice debits and customer payments in one chronological statement canvas.',tags:['Customer 360','AR','Statement'],source:'customer_statement',dateField:'date',allowedGroups:['none','customer','date','payment_mode'],statusOptions:['all','invoice','payment'],searchFields:['customer','reference','document','type','method'],columns:[
  {key:'date',label:'Date',kind:'date'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'type',label:'Type',kind:'status'},{key:'document',label:'Document',kind:'text'},{key:'debit',label:'Debit',kind:'money'},{key:'credit',label:'Credit',kind:'money'},{key:'net',label:'Net Movement',kind:'money'},{key:'reference',label:'Reference',kind:'text'}],
  kpis:[{key:'debit',label:'Invoiced',kind:'sum',field:'debit',format:'money'},{key:'credit',label:'Received',kind:'sum',field:'credit',format:'money'},{key:'net',label:'Net Exposure',kind:'sum',field:'net',format:'money'},{key:'entries',label:'Entries',kind:'count',format:'number'}]
 }
];

export const OPERATIONS_TEMPLATES: ReportTemplate[] = [
 {id:'daily-shift-settlement',category:'POS & Counter Operations',title:'Daily Shift Settlement',description:'Cash & Carry tendered payments for the selected operating period.',tags:['POS','Cash','UPI'],source:'pos_payments',dateField:'payment_date',allowedGroups:['none','date','customer','payment_mode'],statusOptions:['all','inbound','outbound'],searchFields:['invoice_number','customer','method','reference'],columns:[
  {key:'payment_date',label:'Date',kind:'date',groupKey:'date'},{key:'invoice_number',label:'Cash Bill',kind:'text'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'method',label:'Tender',kind:'status',groupKey:'payment_mode'},{key:'reference',label:'Reference',kind:'text'},{key:'amount',label:'Amount',kind:'money'}],
  kpis:[{key:'volume',label:'Tendered Volume',kind:'sum',field:'amount',format:'money'},{key:'cash',label:'Cash',kind:'sum',field:'cash_amount',format:'money'},{key:'upi',label:'UPI',kind:'sum',field:'upi_amount',format:'money'},{key:'txns',label:'Transactions',kind:'count',format:'number'}]
 },
 {id:'tender-breakdown',category:'POS & Counter Operations',title:'Tender Breakdown',description:'Payment-mode register for counter and customer receipts.',tags:['Payments','Tender','Reconciliation'],source:'payments',dateField:'payment_date',allowedGroups:['none','date','payment_mode','customer'],statusOptions:['all','inbound','outbound'],searchFields:['customer','method','reference','direction'],columns:[
  {key:'payment_date',label:'Date',kind:'date'},{key:'customer',label:'Customer',kind:'text',groupKey:'customer'},{key:'direction',label:'Direction',kind:'status'},{key:'method',label:'Payment Mode',kind:'status',groupKey:'payment_mode'},{key:'reference',label:'Reference',kind:'text'},{key:'amount',label:'Amount',kind:'money'}],
  kpis:[{key:'received',label:'Money Received',kind:'sum',field:'inbound_amount',format:'money'},{key:'paid',label:'Money Paid',kind:'sum',field:'outbound_amount',format:'money'},{key:'net',label:'Net Movement',kind:'sum',field:'net',format:'money'},{key:'txns',label:'Transactions',kind:'count',format:'number'}]
 }
];

export const STATUTORY_TEMPLATES: ReportTemplate[] = [
 {id:'tax-summary-by-slab',category:'Tax & Statutory',title:'Tax Summary by Slab',description:'Taxable value and collected tax grouped by configured business tax rates.',tags:['GST','Tax','Statutory'],source:'tax_items',dateField:'invoice_date',allowedGroups:['none','tax_slab','date'],statusOptions:['all','posted'],searchFields:['tax_slab','tax_name','invoice_number','customer'],statutory:true,columns:[
  {key:'invoice_date',label:'Date',kind:'date'},{key:'tax_slab',label:'Tax Slab',kind:'status',groupKey:'tax_slab'},{key:'tax_name',label:'Tax Profile',kind:'text'},{key:'taxable',label:'Taxable Value',kind:'money'},{key:'tax',label:'Tax',kind:'money'},{key:'total',label:'Gross Value',kind:'money'}],
  kpis:[{key:'taxable',label:'Taxable Value',kind:'sum',field:'taxable',format:'money'},{key:'tax',label:'Tax Collected',kind:'sum',field:'tax',format:'money'},{key:'gross',label:'Gross Value',kind:'sum',field:'total',format:'money'},{key:'slabs',label:'Tax Lines',kind:'count',format:'number'}]
 },
 {id:'hsn-sac-breakdown',category:'Tax & Statutory',title:'HSN/SAC Breakdown',description:'Line-level HSN/SAC analysis with quantity, taxable value and tax.',tags:['HSN/SAC','GST','Statutory'],source:'tax_items',dateField:'invoice_date',allowedGroups:['none','tax_slab','date'],statusOptions:['all','posted'],searchFields:['hsn_sac','item','tax_slab','customer'],statutory:true,columns:[
  {key:'hsn_sac',label:'HSN/SAC',kind:'text'},{key:'item',label:'Item / Service',kind:'text'},{key:'quantity',label:'Qty',kind:'number'},{key:'tax_slab',label:'Tax Slab',kind:'status',groupKey:'tax_slab'},{key:'taxable',label:'Taxable Value',kind:'money'},{key:'tax',label:'Tax',kind:'money'},{key:'total',label:'Gross Value',kind:'money'}],
  kpis:[{key:'qty',label:'Quantity',kind:'sum',field:'quantity',format:'number'},{key:'taxable',label:'Taxable Value',kind:'sum',field:'taxable',format:'money'},{key:'tax',label:'Tax Collected',kind:'sum',field:'tax',format:'money'},{key:'codes',label:'HSN/SAC Lines',kind:'count',format:'number'}]
 }
];