'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Bill={id:string;business_id:string;vendor_id:string;bill_number:string;bill_date:string;due_date:string;status:string;currency_code:string;subtotal:number;discount_total:number;tax_total:number;total:number;amount_paid:number;balance_due:number;notes:string|null;terms:string|null;supply_type:string;reverse_charge:boolean;tax_inclusive:boolean;journal_entry_id:string|null};
type Item={id:string;description:string;quantity:number;unit_price:number;discount:number;tax_amount:number;line_total:number;product_service_id:string|null};
type Vendor={id:string;display_name:string;phone:string|null;email:string|null};
type Account={id:string;code:string;name:string;account_type:string};
type Payment={id:string;amount:number;payment_date:string;method:string;reference:string|null;journal_entry_id:string|null};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

export default function PurchaseBillDetail(){
 const params=useParams<{id:string}>();const id=params.id;
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[bill,setBill]=useState<Bill|null>(null),[items,setItems]=useState<Item[]>([]),[vendor,setVendor]=useState<Vendor|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [payAmount,setPayAmount]=useState(''),[payMethod,setPayMethod]=useState('bank_transfer'),[payAccount,setPayAccount]=useState(''),[payDate,setPayDate]=useState(new Date().toISOString().slice(0,10)),[payReference,setPayReference]=useState(''),[payNotes,setPayNotes]=useState('');
 const load=async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const [br,ir,vr,ar,pr]=await Promise.all([
   supabase.from('bills').select('id,business_id,vendor_id,bill_number,bill_date,due_date,status,currency_code,subtotal,discount_total,tax_total,total,amount_paid,balance_due,notes,terms,supply_type,reverse_charge,tax_inclusive,journal_entry_id').eq('id',id).eq('business_id',b.business_id).single(),
   supabase.from('bill_items').select('id,description,quantity,unit_price,discount,tax_amount,line_total,product_service_id').eq('bill_id',id).order('sort_order'),
   supabase.from('vendors').select('id,display_name,phone,email').eq('business_id',b.business_id),
   supabase.from('accounts').select('id,code,name,account_type').eq('business_id',b.business_id).eq('is_active',true).eq('account_type','asset').order('code'),
   supabase.from('payments').select('id,amount,payment_date,method,reference,journal_entry_id').eq('business_id',b.business_id).eq('bill_id',id).eq('direction','outbound').order('payment_date',{ascending:false})
 ]);if(br.error){setError(br.error.message);setLoading(false);return}setBill(br.data);setItems(ir.data||[]);setVendor((vr.data||[]).find(v=>v.id===br.data.vendor_id)||null);setAccounts(ar.data||[]);setPayments(pr.data||[]);if(ar.data?.length&&!payAccount)setPayAccount(ar.data[0].id);setPayAmount(String(Math.max(Number(br.data.balance_due||0),0)));setLoading(false)};
 useEffect(()=>{if(id)load()},[id]);
 const canPost=!!bill&&bill.status==='draft';const canPay=!!bill&&['received','partially_paid','overdue'].includes(bill.status)&&Number(bill.balance_due)>0;
 const post=async()=>{if(!bill)return;setBusy(true);setError('');const r=await supabase.rpc('post_bill',{p_bill_id:bill.id});if(r.error)setError(r.error.message);else await load();setBusy(false)};
 const recordPayment=async()=>{if(!bill||!ctx)return;const amount=Number(payAmount);if(!amount||amount<=0){setError('Enter a positive payment amount.');return}if(amount>Number(bill.balance_due)+0.005){setError('Payment exceeds the bill balance. The RPC supports overpayments, but this UI keeps bill payments within the outstanding balance.');return}if(!payAccount){setError('Select the cash/bank account used for payment.');return}setBusy(true);setError('');const r=await supabase.rpc('record_vendor_payment',{p_business_id:ctx.business_id,p_vendor_id:bill.vendor_id,p_bill_id:bill.id,p_amount:amount,p_method:payMethod,p_account_id:payAccount,p_reference:payReference||null,p_payment_date:payDate,p_notes:payNotes||null});if(r.error)setError(r.error.message);else{setPayReference('');setPayNotes('');await load()}setBusy(false)};
 const paidFromPayments=useMemo(()=>payments.reduce((a,p)=>a+Number(p.amount||0),0),[payments]);
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading bill…</div>;
 if(!bill)return <div className="mx-auto max-w-3xl p-8"><section className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center text-sm text-rose-800">{error||'Bill not found.'}<div><button onClick={()=>location.href='/next-workspace/purchases'} className="mt-5 rounded-xl bg-violet-600 px-4 py-2.5 font-semibold text-white">Back to purchases</button></div></section></div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1200px]">
  <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Purchase bill</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">{bill.bill_number}</h1><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{bill.status.replaceAll('_',' ')}</span></div><p className="mt-2 text-sm text-slate-500">{vendor?.display_name||'Supplier'} · Bill date {bill.bill_date} · Due {bill.due_date}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>location.href='/next-workspace/purchases'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Purchases</button>{canPost&&<button disabled={busy} onClick={post} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Posting…':'Post bill'}</button>}</div></header>
  {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
  <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="space-y-5"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid gap-4 border-b border-slate-100 p-5 sm:grid-cols-3"><div><span className="label">Supplier</span><b className="block mt-1 text-sm">{vendor?.display_name||'—'}</b><span className="text-xs text-slate-400">{vendor?.phone||vendor?.email||'No contact details'}</span></div><div><span className="label">Supply</span><b className="block mt-1 text-sm">{bill.supply_type.replaceAll('_',' ')}{bill.reverse_charge?' · Reverse charge':''}</b></div><div><span className="label">Posting</span><b className="block mt-1 text-sm">{bill.journal_entry_id?'Posted to ledger':'Draft — not posted'}</b></div></div><div className="divide-y divide-slate-100">{items.map(i=><div key={i.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_80px_120px_120px] sm:items-center"><div><b className="block text-sm">{i.description}</b><span className="text-xs text-slate-400">Qty {i.quantity} · Unit {money(i.unit_price)}</span></div><span className="text-sm">{i.quantity}</span><span className="text-sm">{money(i.tax_amount)} tax</span><b className="text-sm sm:text-right">{money(i.line_total)}</b></div>)}</div><div className="ml-auto max-w-sm space-y-2 border-t border-slate-100 p-5 text-sm"><Sum label="Subtotal" value={bill.subtotal}/><Sum label="Discount" value={-bill.discount_total}/><Sum label="Tax" value={bill.tax_total}/><div className="border-t border-slate-100 pt-3"><Sum label="Total" value={bill.total} bold/></div></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Payment history</h2><p className="mt-1 text-xs text-slate-500">{payments.length} payment{payments.length===1?'':'s'} · {money(paidFromPayments)} recorded</p></div></div>{payments.length?<div className="mt-4 divide-y divide-slate-100">{payments.map(p=><div key={p.id} className="flex items-center gap-3 py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700">₹</span><div className="flex-1"><b className="block text-sm">{money(p.amount)}</b><span className="text-xs text-slate-400">{p.payment_date} · {p.method.replaceAll('_',' ')}{p.reference?` · ${p.reference}`:''}</span></div><span className="text-xs font-semibold text-emerald-700">Posted</span></div>)}</div>:<div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs text-slate-500">No supplier payments recorded yet.</div>}</section></section>
  <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><span className="label">Outstanding</span><b className="mt-2 block text-3xl">{money(bill.balance_due)}</b><p className="mt-1 text-xs text-slate-500">Paid {money(bill.amount_paid)} of {money(bill.total)}</p>{canPay&&<div className="mt-5 space-y-3"><h2 className="font-semibold">Record supplier payment</h2><Field label="Amount"><input type="number" min="0.01" max={bill.balance_due} step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)} className="input"/></Field><Field label="Method"><select value={payMethod} onChange={e=>setPayMethod(e.target.value)} className="input"><option value="bank_transfer">Bank transfer</option><option value="upi">UPI</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="payment_gateway">Payment gateway</option><option value="other">Other</option></select></Field><Field label="Paid from"><select value={payAccount} onChange={e=>setPayAccount(e.target.value)} className="input"><option value="">Select account…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></Field><Field label="Payment date"><input type="date" value={payDate} onChange={e=>setPayDate(e.target.value)} className="input"/></Field><Field label="Reference"><input value={payReference} onChange={e=>setPayReference(e.target.value)} placeholder="UTR / transaction reference" className="input"/></Field><Field label="Notes"><textarea value={payNotes} onChange={e=>setPayNotes(e.target.value)} rows={2} className="input"/></Field><button disabled={busy} onClick={recordPayment} className="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'Recording…':'Record payment'}</button><p className="text-[11px] leading-5 text-slate-400">Payment is posted by <b>record_vendor_payment()</b>, including AP settlement and journal validation.</p></div>}</section>{bill.notes&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Notes</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{bill.notes}</p></section>}</aside></div>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label mb-1.5 block">{label}</span>{children}</label>}
function Sum({label,value,bold=false}:{label:string;value:number;bold?:boolean}){return <div className={`flex justify-between ${bold?'text-base font-semibold':'text-slate-600'}`}><span>{label}</span><span>{money(value)}</span></div>}
