'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';
import { Button, Card, EmptyState, PageHeader, SearchInput, StatusBadge } from '@/components/moneymatters';

type Bill={id:string;bill_number:string;bill_date:string;due_date:string;status:string;total:number;balance_due:number;vendor_id:string;is_purchase_order:boolean;po_status:string|null;converted_bill_id:string|null};
type Vendor={id:string;display_name:string};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

export default function BillsWorkspace(){
 const [tab,setTab]=useState<'bills'|'pos'>('bills'),[rows,setRows]=useState<Bill[]>([]),[vendors,setVendors]=useState<Vendor[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}const [br,vr]=await Promise.all([supabase.from('bills').select('id,bill_number,bill_date,due_date,status,total,balance_due,vendor_id,is_purchase_order,po_status,converted_bill_id').eq('business_id',b.business_id).order('bill_date',{ascending:false}).limit(500),supabase.from('vendors').select('id,display_name').eq('business_id',b.business_id).eq('is_active',true).order('display_name')]);if(br.error||vr.error)setError(br.error?.message||vr.error?.message||'Unable to load bills.');setRows((br.data||[]) as Bill[]);setVendors((vr.data||[]) as Vendor[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const name=(id:string)=>vendors.find(v=>v.id===id)?.display_name||'Vendor';
 const filtered=useMemo(()=>rows.filter(x=>x.is_purchase_order===(tab==='pos')&&`${x.bill_number} ${name(x.vendor_id)} ${x.status} ${x.po_status||''}`.toLowerCase().includes(q.toLowerCase())),[rows,vendors,q,tab]);
 const payable=rows.filter(x=>!x.is_purchase_order).reduce((a,x)=>a+Number(x.balance_due||0),0);
 const openPOs=rows.filter(x=>x.is_purchase_order&&!x.converted_bill_id&&x.po_status!=='cancelled').length;
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading bills…</div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1320px]">
  <PageHeader eyebrow="Money out" title="Bills & Procurement" description="Vendor Bills create Accounts Payable. Purchase Orders are procurement commitments only until goods are received and converted." actions={<><Button onClick={()=>location.href='/next-workspace/purchases/new'}>＋ New Vendor Bill</Button><Button variant="secondary" onClick={()=>location.href='/next-workspace/purchases/new?mode=po'}>＋ New Purchase Order</Button><Button variant="secondary" onClick={()=>location.href='/next-workspace/vendors'}>Vendors</Button></>}/>
  {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Vendor Bills</span><b className="mt-3 block text-2xl">{rows.filter(x=>!x.is_purchase_order).length}</b><span className="text-xs text-slate-400">Finalized payables and drafts</span></Card><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Outstanding AP</span><b className="mt-3 block text-2xl">{money(payable)}</b><span className="text-xs text-slate-400">Vendor bill balance due</span></Card><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Open Purchase Orders</span><b className="mt-3 block text-2xl">{openPOs}</b><span className="text-xs text-slate-400">Awaiting goods receipt</span></Card></div>
  <Card className="mt-6 overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={()=>setTab('bills')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab==='bills'?'bg-white text-violet-700 shadow-sm':'text-slate-500'}`}>Vendor Bills</button><button onClick={()=>setTab('pos')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab==='pos'?'bg-white text-violet-700 shadow-sm':'text-slate-500'}`}>Purchase Orders</button></div><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==='bills'?'Search bills or vendors…':'Search purchase orders or vendors…'}/></div>
   <div className="hidden grid-cols-[140px_1fr_120px_150px_150px] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>{tab==='pos'?'PO':'Bill'}</span><span>Vendor</span><span>Date</span><span>Status</span><span className="text-right">{tab==='pos'?'Value':'Balance'}</span></div>
   <div className="divide-y divide-slate-100">{filtered.map(b=><button key={b.id} onClick={()=>location.href=`/next-workspace/purchases/${b.id}`} className="grid w-full gap-2 px-4 py-4 text-left transition hover:bg-violet-50/40 sm:grid-cols-[140px_1fr_120px_150px_150px] sm:items-center sm:px-5"><span className="text-sm font-semibold">{b.bill_number}</span><span><b className="block text-sm">{name(b.vendor_id)}</b><span className="text-xs text-slate-400">{tab==='pos'?(b.po_status||'draft').replaceAll('_',' '):`Due ${b.due_date}`}</span></span><span className="text-xs text-slate-500">{b.bill_date}</span><StatusBadge status={tab==='pos'?(b.converted_bill_id?'fulfilled':b.po_status||'draft'):b.status} tone={tab==='pos'?(b.converted_bill_id?'success':'info'):(b.status==='paid'?'success':b.status==='overdue'?'danger':b.status==='partially_paid'?'warning':'info')}/><span className="text-sm font-semibold sm:text-right">{money(tab==='pos'?b.total:b.balance_due)}</span></button>)}{!filtered.length&&<div className="p-10"><EmptyState title={tab==='pos'?'No purchase orders found.':'No vendor bills found.'} description={tab==='pos'?'Create a purchase order to track procurement before AP exists.':'Create a vendor bill to record a payable.'} action={<Button onClick={()=>location.href=tab==='pos'?'/next-workspace/purchases/new?mode=po':'/next-workspace/purchases/new'}>{tab==='pos'?'New Purchase Order':'New Vendor Bill'}</Button>}/></div>}</div>
  </Card></div></main>;
}
