'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';

type Category={id:string;name:string;sort_order:number};
type Subcategory={id:string;category_id:string;name:string;sort_order:number};
const input='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100';
const states=['Maharashtra','Karnataka','Telangana','Gujarat','Delhi','Tamil Nadu','Uttar Pradesh','Other'];
const channels=[['Physical store / office','physical_store'],['Website','website'],['WhatsApp','whatsapp'],['Instagram / Facebook','social'],['Amazon','amazon'],['Flipkart','flipkart'],['Meesho','meesho'],['B2B / direct customers','b2b'],['Field sales','field_sales'],['Other','other']];
const sizes=['Just me','2–5','6–10','11–25','26–50','51–100','100+'];

function Field({label,children,help}:{label:string;children:ReactNode;help?:string}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}{help&&<span className="mt-1 block text-[11px] text-slate-400">{help}</span>}</label>}

export default function BusinessOnboarding(){
 const[name,setName]=useState(''),[type,setType]=useState('sole_proprietorship'),[categoryId,setCategoryId]=useState(''),[subcategoryId,setSubcategoryId]=useState('');
 const[sellingModel,setSellingModel]=useState<'products'|'services'|'both'>('products'),[inventoryEnabled,setInventoryEnabled]=useState(false),[salesChannels,setSalesChannels]=useState<string[]>([]),[teamSize,setTeamSize]=useState('');
 const[taxMode,setTaxMode]=useState<'gst'|'non_gst'>('gst'),[gstin,setGstin]=useState(''),[taxState,setTaxState]=useState('Maharashtra');
 const[step,setStep]=useState(1),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[categories,setCategories]=useState<Category[]>([]),[subcategories,setSubcategories]=useState<Subcategory[]>([]);
 useEffect(()=>{(async()=>{const s=await supabase.auth.getSession();if(!s.data.session){window.location.replace('/');return}const[c,sc]=await Promise.all([supabase.from('business_categories').select('id,name,sort_order').eq('is_active',true).order('sort_order'),supabase.from('business_subcategories').select('id,category_id,name,sort_order').eq('is_active',true).order('sort_order')]);if(c.error||sc.error)setError((c.error||sc.error)?.message||'Unable to load business categories.');setCategories(c.data||[]);setSubcategories(sc.data||[]);setLoading(false)})()},[]);
 const visibleSubs=useMemo(()=>subcategories.filter(x=>x.category_id===categoryId),[subcategories,categoryId]);
 const toggle=(v:string)=>setSalesChannels(x=>x.includes(v)?x.filter(y=>y!==v):[...x,v]);
 const next=()=>{setError('');if(step===1&&(!name.trim()||!categoryId||!subcategoryId)){setError('Business name, category and sub-category are required.');return}if(step===2&&sellingModel==='services')setInventoryEnabled(false);setStep(x=>Math.min(3,x+1));};
 const create=async()=>{if(taxMode==='gst'&&!taxState.trim()){setError('Tax state is required for GST businesses.');return}setBusy(true);setError('');
   const stateCode:Record<string,string>={Maharashtra:'MH',Karnataka:'KA',Telangana:'TS',Gujarat:'GJ',Delhi:'DL','Tamil Nadu':'TN','Uttar Pradesh':'UP',Other:'OT'};
   const r=await supabase.rpc('create_business_for_current_user',{p_business_name:name.trim(),p_business_type:type,p_country_code:'IN',p_currency_code:'INR',p_tax_enabled:taxMode==='gst',p_tax_region:taxMode==='gst'?'IN-'+(stateCode[taxState]||'OT'):null,p_tax_mode:taxMode,p_notification_email:true,p_notification_whatsapp:true,p_notification_sms:false,p_category_id:categoryId,p_subcategory_id:subcategoryId,p_selling_model:sellingModel,p_sales_channels:salesChannels,p_team_size:teamSize||null,p_tax_state:taxMode==='gst'?taxState:null,p_gstin:taxMode==='gst'?gstin.trim()||null:null,p_feature_flags:{has_physical_inventory:inventoryEnabled,is_tax_registered:taxMode==='gst',industry_preset:categories.find(x=>x.id===categoryId)?.name||'custom'}});
   if(r.error){setError(r.error.message);setBusy(false);return}
   const contexts=await supabase.rpc('get_my_business_context');const rows=(contexts.data||[]) as Array<{business_id:string;business_name:string}>;const returned=typeof r.data==='string'?r.data:Array.isArray(r.data)?(typeof r.data[0]==='string'?r.data[0]:r.data[0]?.business_id):r.data?.business_id;const created=rows.find(x=>x.business_id===returned)||rows.find(x=>x.business_name===name.trim());
   if(!created){setError('Business was created but its workspace could not be opened.');setBusy(false);return}
   localStorage.setItem('moneymatters.activeBusinessId',created.business_id);
   if(inventoryEnabled&&sellingModel!=='services'){const inv=await supabase.rpc('enable_business_inventory',{p_business_id:created.business_id});if(inv.error){setError('Business created, but inventory setup could not be completed.');setBusy(false);return}}
   window.location.replace('/next-workspace/business-details?business='+encodeURIComponent(created.business_id));
 };
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#fbfaff] text-sm text-slate-500">Preparing secure business setup…</main>;
 return <main className="min-h-screen bg-[#fbfaff] p-5 sm:p-8"><div className="mx-auto max-w-4xl"><div className="mb-5 flex items-center justify-between"><a href="/" className="text-sm font-semibold text-violet-700">← Back</a><span className="text-xs font-semibold text-slate-400">Step {step} of 3</span></div><section className="overflow-hidden rounded-3xl border border-violet-100 bg-white shadow-xl"><div className="bg-gradient-to-r from-violet-50 to-white p-7 sm:p-10"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-600">New business setup</p><h1 className="mt-2 text-3xl font-semibold">Configure your workspace</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">These answers configure the workspace. Financial history is created only after business setup completes.</p></div><div className="p-7 sm:p-10">
 {step===1&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Business name *"><input className={input} value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="e.g. ABC Traders"/></Field><Field label="Business type *"><select className={input} value={type} onChange={e=>setType(e.target.value)}><option value="sole_proprietorship">Sole proprietorship</option><option value="individual">Individual</option><option value="partnership">Partnership</option><option value="llp">LLP</option><option value="private_limited">Private limited</option><option value="public_limited">Public limited</option><option value="trust">Trust</option><option value="society">Society</option><option value="other">Other</option></select></Field><Field label="Industry category *"><select className={input} value={categoryId} onChange={e=>{setCategoryId(e.target.value);setSubcategoryId('')}}><option value="">Select category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Business sub-category *"><select className={input} value={subcategoryId} onChange={e=>setSubcategoryId(e.target.value)} disabled={!categoryId}><option value="">Select sub-category</option>{visibleSubs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div>}
 {step===2&&<div><Field label="What do you sell?"><div className="grid gap-3 sm:grid-cols-3">{[['Products','products'],['Services','services'],['Products + Services','both']].map(([l,v])=><button type="button" key={v} onClick={()=>setSellingModel(v as 'products'|'services'|'both')} className={'rounded-2xl border p-4 text-left '+(sellingModel===v?'border-violet-400 bg-violet-50':'border-slate-200')}><b>{l}</b><span className="mt-1 block text-xs text-slate-500">{v==='products'?'Physical or digital goods':v==='services'?'Professional services':'Both on one invoice'}</span></button>)}</div></Field><div className="mt-7"><Field label="Sales channels"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{channels.map(([l,v])=><label key={v} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={salesChannels.includes(v)} onChange={()=>toggle(v)} className="h-4 w-4 accent-violet-600"/><span className="text-sm">{l}</span></label>)}</div></Field></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Team size"><select className={input} value={teamSize} onChange={e=>setTeamSize(e.target.value)}><option value="">Prefer not to say</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></Field>{sellingModel!=='services'&&<Field label="Track stock?"><select className={input} value={inventoryEnabled?'yes':'no'} onChange={e=>setInventoryEnabled(e.target.value==='yes')}><option value="no">No</option><option value="yes">Yes</option></select></Field>}</div></div>}
 {step===3&&<div className="space-y-5"><Field label="Tax treatment *"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setTaxMode('gst')} className={'rounded-2xl border p-4 text-left '+(taxMode==='gst'?'border-violet-400 bg-violet-50':'border-slate-200')}><b>GST registered</b><span className="mt-1 block text-xs text-slate-500">Show GST fields and tax reporting.</span></button><button type="button" onClick={()=>setTaxMode('non_gst')} className={'rounded-2xl border p-4 text-left '+(taxMode==='non_gst'?'border-violet-400 bg-violet-50':'border-slate-200')}><b>Not tax registered</b><span className="mt-1 block text-xs text-slate-500">Keep tax out of daily billing.</span></button></div></Field>{taxMode==='gst'&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Tax state *"><select className={input} value={taxState} onChange={e=>setTaxState(e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="GSTIN (optional)"><input className={input} value={gstin} onChange={e=>setGstin(e.target.value.toUpperCase())} placeholder="e.g. 27AAAAA0000A1Z5"/></Field></div>}<div className="rounded-2xl bg-blue-50 p-4 text-xs leading-5 text-blue-800">Country and currency are fixed to India / INR for the current V1 accounting environment.</div></div>}
 {error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <div className="mt-7 flex items-center justify-between"><button type="button" onClick={()=>setStep(x=>Math.max(1,x-1))} disabled={step===1||busy} className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold text-slate-700 disabled:opacity-40">← Back</button>{step<3?<button type="button" onClick={next} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white">Continue →</button>:<button type="button" onClick={create} disabled={busy} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'Creating business…':'Create business →'}</button>}</div>
 </div></section></div></main>;
}
