'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

const frequencies = ['Weekly', 'Monthly', 'Quarterly', 'Half-yearly', 'Yearly', 'Custom'];
const reminderModes = ['Before due date', 'On due date', 'After due date'];

type Recurring = { id: string; name: string; customer_id: string; frequency: string; next_run_date: string; end_date: string | null; auto_send: boolean; auto_remind: boolean; status: string; currency_code: string; reminder_before_due_days: number | null; reminder_on_due: boolean; reminder_after_due_days: number | null; custom_interval_count: number | null; custom_interval_unit: string | null };
type Customer = { id: string; display_name: string };
type Product = { id: string; name: string; item_type: string; sales_price: number; default_tax_rate_id: string | null };
type Item = { product_service_id: string; description: string; quantity: string; unit_price: string; tax_rate_id: string };

const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(n || 0));
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.05)] ${className}`}>{children}</section>; }
function Input(p: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...p} className={`w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-slate-400 ${p.className || ''}`} />; }

export default function RecurringPage() {
  const [ctx, setCtx] = useState<BusinessContext | null>(null), [rows, setRows] = useState<Recurring[]>([]), [customers, setCustomers] = useState<Customer[]>([]), [products, setProducts] = useState<Product[]>([]);
  const [status, setStatus] = useState('all'), [show, setShow] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [name, setName] = useState(''), [customerId, setCustomerId] = useState(''), [frequency, setFrequency] = useState('Monthly'), [nextRun, setNextRun] = useState(new Date().toISOString().slice(0, 10)), [endDate, setEndDate] = useState('');
  const [autoSend, setAutoSend] = useState(false), [autoRemind, setAutoRemind] = useState(true), [reminderMode, setReminderMode] = useState('Before due date'), [reminderDays, setReminderDays] = useState('3');
  const [customCount, setCustomCount] = useState('1'), [customUnit, setCustomUnit] = useState('month'), [dueTerms, setDueTerms] = useState('Due on receipt');
  const [items, setItems] = useState<Item[]>([]);

  async function load() {
    const r = await supabase.rpc('get_my_business_context'); const c = r.data?.[0] as BusinessContext | undefined;
    if (!c) { window.location.href = '/'; return; } setCtx(c);
    const [rr, cc, pp] = await Promise.all([
      supabase.from('recurring_invoices').select('id,name,customer_id,frequency,next_run_date,end_date,auto_send,auto_remind,status,currency_code,reminder_before_due_days,reminder_on_due,reminder_after_due_days,custom_interval_count,custom_interval_unit').eq('business_id', c.business_id).order('next_run_date', { ascending: true }),
      supabase.from('customers').select('id,display_name').eq('business_id', c.business_id).eq('is_active', true).order('display_name'),
      supabase.from('products_services').select('id,name,item_type,sales_price,default_tax_rate_id').eq('business_id', c.business_id).eq('is_active', true).order('name')
    ]);
    setRows(rr.data || []); setCustomers(cc.data || []); setProducts(pp.data || []);
  }
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => rows.filter(r => status === 'all' || r.status === status), [rows, status]);
  const customerName = (id: string) => customers.find(c => c.id === id)?.display_name || 'Unknown customer';

  function addItem() { setItems(x => [...x, { product_service_id: '', description: '', quantity: '1', unit_price: '0', tax_rate_id: '' }]); }
  function updateItem(index: number, patch: Partial<Item>) { setItems(x => x.map((it, i) => i === index ? { ...it, ...patch } : it)); }
  function chooseProduct(index: number, id: string) { const p = products.find(x => x.id === id); updateItem(index, { product_service_id: id, description: p?.name || '', unit_price: String(p?.sales_price || 0), tax_rate_id: p?.default_tax_rate_id || '' }); }

  async function create() {
    if (!ctx || !name.trim() || !customerId || !nextRun || !items.length || items.some(i => !i.product_service_id || Number(i.quantity) <= 0)) { setError('Add at least one valid product/service line.'); return; }
    setBusy(true); setError('');
    const base = { business_id: ctx.business_id, customer_id: customerId, name: name.trim(), frequency: frequency === 'Half-yearly' ? 'half_yearly' : frequency.toLowerCase(), next_run_date: nextRun, end_date: endDate || null, auto_send: autoSend, auto_remind: autoRemind, status: 'active', currency_code: 'INR', notes: null, due_terms: dueTerms, reminder_before_due_days: autoRemind && reminderMode === 'Before due date' ? Number(reminderDays) || 0 : null, reminder_on_due: autoRemind && reminderMode === 'On due date', reminder_after_due_days: autoRemind && reminderMode === 'After due date' ? Number(reminderDays) || 0 : null, custom_interval_count: frequency === 'Custom' ? Number(customCount) || 1 : null, custom_interval_unit: frequency === 'Custom' ? customUnit : null };
    const r = await supabase.from('recurring_invoices').insert(base).select('id').single();
    if (r.error) { setError(r.error.message); setBusy(false); return; }
    const ir = await supabase.from('recurring_invoice_items').insert(items.map((i, sort_order) => ({ recurring_invoice_id: r.data.id, product_service_id: i.product_service_id, description: i.description || products.find(p => p.id === i.product_service_id)?.name || 'Item', quantity: Number(i.quantity), unit_price: Number(i.unit_price) || 0, discount: 0, tax_rate_id: i.tax_rate_id || null, sort_order })));
    if (ir.error) { await supabase.from('recurring_invoices').delete().eq('id', r.data.id); setError(ir.error.message); setBusy(false); return; }
    setShow(false); setName(''); setCustomerId(''); setFrequency('Monthly'); setEndDate(''); setAutoSend(false); setAutoRemind(true); setReminderMode('Before due date'); setReminderDays('3'); setDueTerms('Due on receipt'); setItems([]); await load(); setBusy(false);
  }

  async function setRowStatus(row: Recurring, next: string) { const r = await supabase.from('recurring_invoices').update({ status: next }).eq('id', row.id).eq('business_id', ctx?.business_id || ''); if (!r.error) setRows(prev => prev.map(x => x.id === row.id ? { ...x, status: next } : x)); }

  return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Automate billing</p><h1 className="mt-1 text-3xl font-semibold">Recurring invoices</h1><p className="mt-1 text-sm text-slate-500">Wave-inspired recurring billing with flexible scheduling, automatic sending and customer reminders.</p></div><button onClick={() => setShow(true)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">＋ Create recurring invoice</button></header>
    <div className="mb-5 flex flex-wrap gap-2">{['all','active','paused','completed','cancelled'].map(s => <button key={s} onClick={() => setStatus(s)} className={`rounded-xl px-4 py-2 text-xs font-semibold capitalize ${status === s ? 'bg-slate-950 text-white' : 'border border-slate-200 bg-white text-slate-600'}`}>{s}</button>)}</div>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Recurring invoice</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Schedule</th><th className="px-5 py-3">Next invoice</th><th className="px-5 py-3">Send</th><th className="px-5 py-3">Reminder</th><th className="px-5 py-3">Status</th><th/></tr></thead><tbody>{filtered.map(r => <tr key={r.id} className="border-t border-slate-100"><td className="px-5 py-4"><b>{r.name}</b><span className="mt-1 block text-xs text-slate-400">{r.end_date ? `Ends ${r.end_date}` : 'Never ends'}</span></td><td className="px-5 py-4">{customerName(r.customer_id)}</td><td className="px-5 py-4 capitalize">{r.frequency.replace('_','-')}</td><td className="px-5 py-4 font-semibold">{r.next_run_date}</td><td className="px-5 py-4">{r.auto_send ? 'Automatic' : 'Manual'}</td><td className="px-5 py-4">{r.auto_remind ? (r.reminder_before_due_days != null ? `${r.reminder_before_due_days}d before` : r.reminder_on_due ? 'On due date' : `${r.reminder_after_due_days ?? 0}d after`) : 'Off'}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize">{r.status}</span></td><td className="px-5 py-4 text-right">{r.status === 'active' ? <button onClick={() => setRowStatus(r, 'paused')} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">Pause</button> : r.status === 'paused' ? <button onClick={() => setRowStatus(r, 'active')} className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Activate</button> : null}</td></tr>)}{!filtered.length && <tr><td colSpan={8} className="px-5 py-16 text-center text-sm text-slate-400">No recurring invoices in this view.</td></tr>}</tbody></table></div></Card>
    {show && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><div className="mx-auto my-4 w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Recurring billing</p><h2 className="mt-1 text-xl font-semibold">Create recurring invoice</h2></div><button onClick={() => setShow(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100">×</button></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-500">Name *</span><Input value={name} onChange={e => setName(e.target.value)} placeholder="Monthly maintenance" /></label><label className="sm:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-500">Customer *</span><select value={customerId} onChange={e => setCustomerId(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Select customer</option>{customers.map(c => <option key={c.id} value={c.id}>{c.display_name}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold text-slate-500">Frequency</span><select value={frequency} onChange={e => setFrequency(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{frequencies.map(f => <option key={f}>{f}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold text-slate-500">Start / next invoice</span><Input type="date" value={nextRun} onChange={e => setNextRun(e.target.value)} /></label><label><span className="mb-1 block text-xs font-semibold text-slate-500">End date</span><Input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} /></label><label><span className="mb-1 block text-xs font-semibold text-slate-500">Due terms</span><select value={dueTerms} onChange={e => setDueTerms(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>Due on receipt</option><option>Net 7</option><option>Net 15</option><option>Net 30</option><option>Net 45</option><option>Net 60</option><option>Custom</option></select></label></div>
      {frequency === 'Custom' && <div className="mt-4 grid gap-4 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-semibold">Every</span><Input type="number" min="1" value={customCount} onChange={e => setCustomCount(e.target.value)} /></label><label><span className="mb-1 block text-xs font-semibold">Unit</span><select value={customUnit} onChange={e => setCustomUnit(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="day">Day(s)</option><option value="week">Week(s)</option><option value="month">Month(s)</option><option value="year">Year(s)</option></select></label></div>}
      <div className="mt-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Products / Services</h3><p className="text-xs text-slate-400">Each generated invoice will use these lines.</p></div><button onClick={addItem} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">＋ Add item</button></div><div className="mt-3 space-y-3">{items.map((it, index) => <div key={index} className="grid gap-2 rounded-2xl border border-slate-200 p-3 sm:grid-cols-[2fr_1fr_90px_110px_30px]"><select value={it.product_service_id} onChange={e => chooseProduct(index, e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">Select product/service</option>{products.map(p => <option key={p.id} value={p.id}>{p.name} · {p.item_type}</option>)}</select><Input placeholder="Description" value={it.description} onChange={e => updateItem(index,{description:e.target.value})}/><Input type="number" min="0.01" value={it.quantity} onChange={e => updateItem(index,{quantity:e.target.value})}/><Input type="number" min="0" value={it.unit_price} onChange={e => updateItem(index,{unit_price:e.target.value})}/><button onClick={() => setItems(x => x.filter((_, i) => i !== index))} className="rounded-xl bg-slate-100">×</button></div>)}{!items.length && <div className="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-400">Add the products/services that should appear on every generated invoice.</div>}</div></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={() => setAutoSend(!autoSend)} className={`rounded-2xl border p-4 text-left ${autoSend ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200'}`}><b className="block text-sm">Auto-send invoice</b><span className={`mt-1 block text-xs ${autoSend ? 'text-white/60' : 'text-slate-400'}`}>{autoSend ? 'Yes — send when generated' : 'No — keep it for review'}</span></button><button onClick={() => setAutoRemind(!autoRemind)} className={`rounded-2xl border p-4 text-left ${autoRemind ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200'}`}><b className="block text-sm">Payment reminder</b><span className={`mt-1 block text-xs ${autoRemind ? 'text-white/60' : 'text-slate-400'}`}>{autoRemind ? 'Yes — configure reminder timing below' : 'No — do not remind'}</span></button></div>
      {autoRemind && <div className="mt-3 grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-semibold">Reminder schedule</span><select value={reminderMode} onChange={e => setReminderMode(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{reminderModes.map(x => <option key={x}>{x}</option>)}</select></label>{reminderMode !== 'On due date' && <label><span className="mb-1 block text-xs font-semibold">Days</span><Input type="number" min="0" max="365" value={reminderDays} onChange={e => setReminderDays(e.target.value)} /></label>}</div>}
      {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<button disabled={busy || !name.trim() || !customerId || !items.length} onClick={create} className="mt-5 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? 'Creating…' : 'Create recurring invoice'}</button>
    </div></div>}
  </div></main>;
}
