'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

type Invoice={id:string;invoice_number:string;invoice_date:string;due_date:string;status:string;total:number;amount_paid:number;balance_due:number;customer_id:string;customer?:{display_name:string;email:string|null;phone:string|null}};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
const days=(d:string)=>Math.ceil((new Date(d+'T23:59:59').getTime()-Date.now())/86400000);
const status=(i:Invoice)=>Number(i.balance_due)<=0?'Paid':i.status==='draft'?'Draft':new Date(i.due_date+'T23:59:59')<new Date()?'Overdue':'Unpaid';

export default function Invoices(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[rows,setRows]=useState<Invoice[]>([]),[customers,setCustomers]=useState<any[]>([]),[q,setQ]=useState(''),[customerId,setCustomerId]=useState('all'),[state,setState]=useState('unpaid'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[menu,setMenu]=useState<string|null>(null);
 async function load(){const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const[i,cu]=await Promise.all([supabase.from('invoices').select('id,invoice_number,invoice_date,due_date,status,total,amount_paid,balance_due,customer_id').eq('business_id',b.business_id).order('due_date',{ascending:true}),supabase.from('customers').select('id,display_name,email,phone').eq('business_id',b.business_id).eq('is_active',true).order('display_name')]);if(i.error)setError(i.error.message);setCustomers(cu.data||[]);const cm=new Map((cu.data||[]).map(x=>[x.id,x]));setRows((i.data||[]).map(x=>({...x,customer:cm.get(x.customer_id)})));setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{let a=rows.filter(i=>(customerId==='all'||i.customer_id===customerId)&&(!from||i.invoice_date>=from)&&(!to||i.invoice_date<=to)&&(`${i.invoice_number} ${i.customer?.display_name||''} ${i.customer?.email||''}`).toLowerCase().includes(q.toLowerCase()));if(state==='unpaid')a=a.filter(i=>Number(i.balance_due)>0&&status(i)!=='Draft');if(state==='drafts')a=a.filter(i=>status(i)==='Draft');return a},[rows,customerId,state,from,to,q]);
 const unpaid=rows.filter(i=>Number(i.balance_due)>0&&status(i)!=='Draft'),overdue=unpaid.filter(i=>status(i)==='Overdue'),due30=unpaid.filter(i=>status(i)!=='Overdue'&&days(i.due_date)<=30);
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading invoices…</div>;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-6 lg:p-8" onClick={()=>setMenu(null)}><div className="mx-auto max-w-[1450px]">
  <header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Sales & payments</p><h1 className="mt-1 text-3xl font-semibold">Invoices</h1><p className="mt-1 text-sm text-slate-500">Create, review, collect and manage every invoice.</p></div><button type="button" onClick={()=>location.href='/next-workspace/invoices/new'} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">＋ Create an Invoice</button></header>
  {error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <section className="mb-5 grid gap-3 md:grid-cols-3"><Metric title="Overdue" value={money(overdue.reduce((a,i)=>a+Number(i.balance_due),0))} note={`${overdue.length} invoices`}/><Metric title="Due within next 30 days" value={money(due30.reduce((a,i)=>a+Number(i.balance_due),0))} note={`${due30.length} invoices`}/><Metric title="Outstanding" value={money(unpaid.reduce((a,i)=>a+Number(i.balance_due),0))} note={`${unpaid.length} unpaid invoices`}/></section>
  <section className="mb-4 grid gap-2 lg:grid-cols-[1.2fr_150px_150px_150px_1fr]"><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="all">All customers</option>{customers.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><select value={state} onChange={e=>setState(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="unpaid">Unpaid</option><option value="drafts">Drafts</option><option value="all">All invoices</option></select><label className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-500">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="ml-2 text-sm text-slate-800 outline-none"/></label><label className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-500">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="ml-2 text-sm text-slate-800 outline-none"/></label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoice number or customer…" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"/></section>
  <div className="mb-4 inline-flex overflow-hidden rounded-xl border border-slate-200 bg-white text-sm"><Tab active={state==='unpaid'} onClick={()=>setState('unpaid')}>Unpaid <b>{unpaid.length}</b></Tab><Tab active={state==='drafts'} onClick={()=>setState('drafts')}>Drafts <b>{rows.filter(i=>status(i)==='Draft').length}</b></Tab><Tab active={state==='all'} onClick={()=>setState('all')}>All invoices <b>{rows.length}</b></Tab></div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b border-slate-100 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Status</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Number</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Amount due</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id} onClick={()=>location.href=`/next-workspace/documents?type=invoice&id=${i.id}`} className="cursor-pointer border-b border-slate-100 hover:bg-violet-50/40"><td className="px-4 py-3"><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${status(i)==='Overdue'?'bg-rose-100 text-rose-700':status(i)==='Paid'?'bg-emerald-100 text-emerald-700':status(i)==='Draft'?'bg-slate-100 text-slate-600':'bg-amber-100 text-amber-700'}`}>{status(i)}</span></td><td className="px-4 py-3 text-xs">{status(i)==='Paid'||status(i)==='Draft'?'—':`${Math.abs(days(i.due_date))} ${days(i.due_date)<0?'days ago':'days'}`}</td><td className="px-4 py-3 text-xs">{i.invoice_date}</td><td className="px-4 py-3 font-medium">{i.invoice_number}</td><td className="px-4 py-3 max-w-[220px] truncate">{i.customer?.display_name||'Unknown customer'}</td><td className="px-4 py-3 font-semibold">{money(i.balance_due)}</td><td className="px-4 py-3 text-right" onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>setMenu(menu===i.id?null:i.id)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold">Actions</button>{menu===i.id&&<div className="absolute z-30 mt-1 mr-2 w-44 rounded-xl border border-slate-200 bg-white p-1 text-left shadow-xl"><Action label="View invoice" onClick={()=>location.href=`/next-workspace/documents?type=invoice&id=${i.id}`}/><Action label="Edit draft" onClick={()=>location.href=`/next-workspace/sales?invoice=${i.id}`}/><Action label="Duplicate" onClick={()=>location.href=`/next-workspace/invoices/new?duplicate=${i.id}`}/><Action label="Record payment" onClick={()=>location.href=`/next-workspace/payments?invoice=${i.id}`}/></div>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="p-12 text-center text-sm text-slate-500">No invoices match these filters.</td></tr>}</tbody></table></div></section>
 </div></main>;
}
function Metric({title,value,note}:{title:string;value:string;note:string}){return <section className="rounded-xl border border-slate-200 bg-white p-4"><span className="text-xs font-semibold text-slate-500">{title}</span><b className="mt-2 block text-xl">{value}</b><span className="mt-1 block text-[11px] text-slate-400">{note}</span></section>}
function Tab({children,active,onClick}:{children:React.ReactNode;active:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`px-4 py-2.5 ${active?'bg-violet-50 text-violet-800 font-semibold':'text-slate-500'}`}>{children}</button>}
function Action({label,onClick}:{label:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="block w-full rounded-lg px-3 py-2 text-left text-xs text-slate-700 hover:bg-slate-50">{label}</button>}
