'use client';

import { useMemo, useState } from 'react';

type Module = 'Dashboard' | 'Sales' | 'Purchases' | 'Expenses' | 'Customers' | 'Vendors' | 'Inventory' | 'Banking' | 'Payroll' | 'Accounting' | 'Reports' | 'Automations' | 'Settings';

type Customer = { name: string; phone: string; balance: string; status: string };
const customers: Customer[] = [
  { name: 'ABC Traders', phone: '+91 98765 43210', balance: '₹25,000', status: 'Overdue' },
  { name: 'Shree Enterprises', phone: '+91 98220 11223', balance: '₹18,700', status: 'Due soon' },
  { name: 'Mahalaxmi Stores', phone: '+91 97654 88776', balance: '₹0', status: 'Clear' },
  { name: 'Omkar Distributors', phone: '+91 98901 44556', balance: '₹42,800', status: 'Outstanding' },
];

const products = [
  { sku: 'PRD-001', name: 'Premium Product A', stock: 128, price: '₹1,250', track: true },
  { sku: 'PRD-002', name: 'Premium Product B', stock: 42, price: '₹2,400', track: true },
  { sku: 'PRD-003', name: 'Service Package', stock: 0, price: '₹5,000', track: false },
  { sku: 'PRD-004', name: 'Product C', stock: 8, price: '₹850', track: true },
];

const navGroups: { title: string; items: { label: Module; icon: string }[] }[] = [
  { title: 'Workspace', items: [{ label: 'Dashboard', icon: '⌂' }] },
  { title: 'Money in', items: [{ label: 'Sales', icon: '↗' }, { label: 'Customers', icon: '◎' }] },
  { title: 'Money out', items: [{ label: 'Purchases', icon: '↙' }, { label: 'Expenses', icon: '₹' }, { label: 'Vendors', icon: '◇' }] },
  { title: 'Operations', items: [{ label: 'Inventory', icon: '▦' }, { label: 'Banking', icon: '▣' }, { label: 'Payroll', icon: '♙' }] },
  { title: 'Finance', items: [{ label: 'Accounting', icon: '∑' }, { label: 'Reports', icon: '▤' }, { label: 'Automations', icon: '⚡' }] },
];

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,.035)] ${className}`}>{children}</div>;
}

function Pill({ children, tone = 'slate' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'red' | 'blue' | 'slate' }) {
  const tones = { green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-red-50 text-red-700', blue: 'bg-blue-50 text-blue-700', slate: 'bg-slate-100 text-slate-600' };
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${tones[tone]}`}>{children}</span>;
}

function PageTitle({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) {
  return <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action && <button onClick={onAction} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">＋ {action}</button>}</div>;
}

function Dashboard({ go }: { go: (m: Module) => void }) {
  const attention = [
    ['3 invoices are overdue', '₹42,500 outstanding', 'red', 'Sales'],
    ['2 bank transactions need review', 'AI prepared categories', 'amber', 'Banking'],
    ['Payroll is due in 7 days', '12 employees · August', 'blue', 'Payroll'],
  ] as const;
  return <div className="space-y-7">
    <PageTitle title="Good evening, Vishnu." description="Tuesday, 18 August 2026 · Here’s what needs your attention today." action="Create invoice" onAction={() => go('Sales')} />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {[['Cash & bank','₹4,82,650','+8.4% vs last month','green'],['Receivables','₹1,26,400','6 invoices outstanding','amber'],['Payables','₹74,200','3 bills due soon','red'],['Profit this month','₹60,660','+12.1% vs last month','green']].map(([a,b,c,t]) => <Card key={a} className="p-5"><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-2xl font-semibold">{b}</p><p className={`mt-2 text-xs font-medium ${t === 'red' ? 'text-red-600' : t === 'amber' ? 'text-amber-600' : 'text-emerald-600'}`}>{c}</p></Card>)}
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <Card className="p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Cash flow</h2><p className="mt-1 text-xs text-slate-400">Money in and out · last 6 months</p></div><button onClick={() => go('Reports')} className="text-xs font-semibold text-slate-500">View report →</button></div><div className="mt-8 flex h-52 items-end gap-3 border-b border-slate-100 sm:gap-5">{[58,72,48,86,66,94,78,61,89,74,96,83].map((h,i)=><div key={i} className="group flex flex-1 flex-col justify-end"><div className="mx-auto w-full max-w-8 rounded-t-lg bg-slate-900 transition group-hover:bg-slate-600" style={{height:`${h}%`}}/><span className="mt-2 text-center text-[10px] text-slate-400">{['Mar','Mar','Apr','Apr','May','May','Jun','Jun','Jul','Jul','Aug','Aug'][i]}</span></div>)}</div></Card>
      <Card className="p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Needs attention</h2><p className="mt-1 text-xs text-slate-400">Moneymatters found these for you</p></div><Pill tone="amber">3 items</Pill></div><div className="mt-5 space-y-3">{attention.map(([title,detail,tone,module])=><button key={title} onClick={() => go(module as Module)} className="w-full rounded-xl border border-slate-100 p-4 text-left hover:bg-slate-50"><div className="flex items-start gap-3"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${tone === 'red' ? 'bg-red-400' : tone === 'amber' ? 'bg-amber-400' : 'bg-blue-400'}`}/><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div><span className="ml-auto text-xs font-semibold text-slate-500">Open →</span></div></button>)}</div></Card>
    </div>
    <Card className="p-6"><div className="flex justify-between"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-1 text-xs text-slate-400">Transactions and business events</p></div><button onClick={() => go('Accounting')} className="text-xs font-semibold text-slate-500">View all →</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs text-slate-400"><th className="pb-3">Activity</th><th className="pb-3">Account</th><th className="pb-3">Date</th><th className="pb-3 text-right">Amount</th><th className="pb-3 text-right">Status</th></tr></thead><tbody>{[['Payment received · ABC Traders','Bank','18 Aug','₹25,000','Completed'],['Invoice created · INV-000124','Accounts receivable','18 Aug','₹18,700','Sent'],['Expense · Transport','Operating expenses','17 Aug','₹3,850','Posted'],['Salary processed · August','Payroll','16 Aug','₹1,42,000','Posted']].map(r=><tr key={r[0]} className="border-b border-slate-50 last:border-0"><td className="py-4 font-medium">{r[0]}</td><td className="py-4 text-slate-500">{r[1]}</td><td className="py-4 text-slate-500">{r[2]}</td><td className="py-4 text-right font-medium">{r[3]}</td><td className="py-4 text-right"><Pill tone="green">{r[4]}</Pill></td></tr>)}</tbody></table></div></Card>
  </div>;
}

function Sales({ notify }: { notify: (s: string) => void }) {
  const [tab,setTab] = useState('Invoices');
  const tabs = ['Invoices','Quotations','Receipts'];
  return <div className="space-y-6"><PageTitle title="Sales" description="Create quotations, invoices, collect payments and issue receipts." action={tab === 'Quotations' ? 'Create quotation' : tab === 'Receipts' ? 'Record payment' : 'Create invoice'} onAction={() => notify(`${tab.slice(0,-1)} workflow opened`)} /><div className="flex gap-2 overflow-x-auto">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab===t?'bg-slate-950 text-white':'bg-white text-slate-500 border border-slate-200'}`}>{t}</button>)}</div><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr><th className="p-4">Number</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th><th className="text-right p-4">Action</th></tr></thead><tbody>{[['INV-000124','ABC Traders','18 Aug 2026','₹18,700','Sent'],['INV-000123','Shree Enterprises','17 Aug 2026','₹32,450','Partially paid'],['INV-000122','Mahalaxmi Stores','15 Aug 2026','₹12,800','Paid'],['INV-000121','Omkar Distributors','12 Aug 2026','₹42,800','Overdue']].map((r,i)=><tr key={r[0]} className="border-t border-slate-100"><td className="p-4 font-semibold">{tab==='Invoices'?r[0]:tab==='Quotations'?`QUO-000${124-i}`:`RCT-000${124-i}`}</td><td>{r[1]}</td><td className="text-slate-500">{r[2]}</td><td className="font-medium">{r[3]}</td><td><Pill tone={r[4]==='Overdue'?'red':r[4]==='Paid'?'green':'blue'}>{tab==='Quotations'?'Draft':tab==='Receipts'?'Completed':r[4]}</Pill></td><td className="p-4 text-right"><button onClick={()=>notify(`Opened ${tab.slice(0,-1).toLowerCase()} ${r[0]}`)} className="text-xs font-semibold">Open →</button></td></tr>)}</tbody></table></div></Card><div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">This month</p><p className="mt-2 text-2xl font-semibold">₹2,84,600</p><p className="mt-1 text-xs text-emerald-600">+14.2%</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Outstanding</p><p className="mt-2 text-2xl font-semibold">₹1,26,400</p><p className="mt-1 text-xs text-amber-600">6 invoices</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Collected</p><p className="mt-2 text-2xl font-semibold">₹1,58,200</p><p className="mt-1 text-xs text-emerald-600">82% of due</p></Card></div></div>;
}

function Contacts({ kind, notify }: { kind: 'Customers'|'Vendors'; notify:(s:string)=>void }) {
  const rows = kind==='Customers' ? customers : customers.map((c,i)=>({name:['Shivam Suppliers','Raj Hardware','Kohinoor Wholesalers','A1 Packaging'][i],phone:c.phone,balance:['₹48,000','₹0','₹12,600','₹31,200'][i],status:['Due soon','Clear','Outstanding','Due soon'][i]}));
  return <div className="space-y-6"><PageTitle title={kind} description={`Manage ${kind.toLowerCase()}, balances, statements and communication.`} action={`Add ${kind.slice(0,-1)}`} onAction={()=>notify(`Add ${kind.slice(0,-1).toLowerCase()} form opened`)} /><Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><input className="w-full max-w-md rounded-xl border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-slate-400" placeholder={`Search ${kind.toLowerCase()}…`}/></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr><th className="p-4">Name</th><th>Phone</th><th>Balance</th><th>Status</th><th className="text-right p-4">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.name} className="border-t border-slate-100"><td className="p-4 font-semibold">{r.name}</td><td className="text-slate-500">{r.phone}</td><td className="font-medium">{r.balance}</td><td><Pill tone={r.status==='Overdue'?'red':r.status==='Clear'?'green':'amber'}>{r.status}</Pill></td><td className="p-4 text-right"><button onClick={()=>notify(`Opened ${r.name}`)} className="text-xs font-semibold">View →</button></td></tr>)}</tbody></table></div></Card></div>;
}

function Inventory({ notify }: { notify:(s:string)=>void }) { return <div className="space-y-6"><PageTitle title="Inventory" description="Track stock, locations, valuation, reorder levels and movements." action="Add product" onAction={()=>notify('Product form opened')}/><div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">Stock value</p><p className="mt-2 text-2xl font-semibold">₹8,42,500</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Low stock</p><p className="mt-2 text-2xl font-semibold">8 items</p><p className="mt-1 text-xs text-amber-600">Needs reorder</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Locations</p><p className="mt-2 text-2xl font-semibold">2</p></Card></div><Card className="overflow-hidden"><div className="flex flex-wrap gap-2 border-b border-slate-100 p-4"><button className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Stock</button><button onClick={()=>notify('Stock movement opened')} className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Movements</button><button onClick={()=>notify('Transfer workflow opened')} className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Transfers</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr><th className="p-4">SKU</th><th>Product</th><th>Stock</th><th>Sale price</th><th>Tracking</th><th className="text-right p-4">Action</th></tr></thead><tbody>{products.map(p=><tr key={p.sku} className="border-t border-slate-100"><td className="p-4 font-medium">{p.sku}</td><td>{p.name}</td><td className={p.stock<10?'font-semibold text-red-600':'font-medium'}>{p.track?p.stock:'—'}</td><td>{p.price}</td><td><Pill tone={p.track?'blue':'slate'}>{p.track?'Tracked':'Service'}</Pill></td><td className="p-4 text-right"><button onClick={()=>notify(`Opened ${p.name}`)} className="text-xs font-semibold">View →</button></td></tr>)}</tbody></table></div></Card></div>; }

function Finance({ module, notify }: { module: Module; notify:(s:string)=>void }) {
  const data: Record<string,{title:string;desc:string;action:string;cards:string[]}> = {
    Purchases:{title:'Purchases',desc:'Manage vendor bills, due dates and purchase costs.',action:'Create bill',cards:['₹1,84,200 this month','₹74,200 payable','18 bills']},
    Expenses:{title:'Expenses',desc:'Capture expenses quickly and keep receipts attached.',action:'Add expense',cards:['₹62,450 this month','14 expenses','3 need review']},
    Banking:{title:'Banking',desc:'Connect accounts, import transactions and reconcile automatically.',action:'Add bank account',cards:['₹4,82,650 cash & bank','12 to reconcile','2 AI suggestions']},
    Payroll:{title:'Payroll',desc:'Run payroll, review deductions and post the payroll journal.',action:'Start payroll',cards:['12 employees','₹1,42,000 latest payroll','7 days to pay']},
    Accounting:{title:'Accounting',desc:'Chart of accounts, journals, periods and the general ledger.',action:'New journal',cards:['₹60,660 profit','₹4,82,650 assets','₹1,26,400 receivable']},
    Reports:{title:'Reports',desc:'Financial reports built from the posted accounting ledger.',action:'Custom report',cards:['P&L','Balance Sheet','Trial Balance']},
    Automations:{title:'Automations',desc:'Let Moneymatters handle repetitive work with controlled rules.',action:'Create automation',cards:['3 active rules','8 runs today','1 needs review']},
    Settings:{title:'Settings',desc:'Business profile, logo, branding, templates, users and integrations.',action:'Edit business',cards:['Branding','Templates','Users & permissions']},
  };
  const d=data[module];
  return <div className="space-y-6"><PageTitle title={d.title} description={d.desc} action={d.action} onAction={()=>notify(`${d.action} workflow opened`)}/><div className="grid gap-4 md:grid-cols-3">{d.cards.map((x,i)=><Card key={x} className="p-5"><p className="text-sm text-slate-500">{i===0&&module!=='Reports'&&module!=='Automations'&&module!=='Settings'?'Current':'Moneymatters'}</p><p className="mt-2 text-xl font-semibold">{x}</p><p className="mt-1 text-xs text-slate-400">Click the module actions to continue</p></Card>)}</div><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{module} workspace</h2><p className="mt-1 text-xs text-slate-400">The full workflow is being connected to the accounting engine.</p></div><Pill tone="blue">V1 workflow</Pill></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{['Overview','Transactions','Statements','Settings','Import / export','Audit history'].map(x=><button key={x} onClick={()=>notify(`${x} view opened`)} className="rounded-xl border border-slate-200 p-4 text-left text-sm font-medium hover:bg-slate-50">{x}<span className="float-right text-slate-400">→</span></button>)}</div></Card></div>;
}

export default function MoneyMattersHome() {
  const [active,setActive] = useState<Module>('Dashboard');
  const [mobileOpen,setMobileOpen] = useState(false);
  const [showBusiness,setShowBusiness] = useState(false);
  const [toast,setToast] = useState('');
  const [search,setSearch] = useState('');
  const greeting = useMemo(()=>new Date().getHours()<12?'Good morning':new Date().getHours()<17?'Good afternoon':'Good evening',[]);
  const notify=(s:string)=>{setToast(s); window.setTimeout(()=>setToast(''),3000);};
  const go=(m:Module)=>{setActive(m);setMobileOpen(false);};
  const content = active==='Dashboard' ? <Dashboard go={go}/> : active==='Sales' ? <Sales notify={notify}/> : active==='Customers' ? <Contacts kind="Customers" notify={notify}/> : active==='Vendors' ? <Contacts kind="Vendors" notify={notify}/> : active==='Inventory' ? <Inventory notify={notify}/> : <Finance module={active} notify={notify}/>;
  return <div className="min-h-screen bg-[#f7f8fa] text-slate-900">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-slate-200 bg-white lg:flex lg:flex-col"><div className="flex h-20 items-center gap-3 border-b border-slate-100 px-6"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 font-bold text-white">M</div><div><div className="font-semibold">Moneymatters</div><div className="text-[11px] text-slate-400">Business finance, simplified</div></div></div><div className="p-4"><button onClick={()=>go('Sales')} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800">＋ Quick action</button></div><nav className="flex-1 space-y-5 overflow-y-auto px-3 pb-4">{navGroups.map(g=><div key={g.title}><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{g.title}</p>{g.items.map(item=><button key={item.label} onClick={()=>go(item.label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active===item.label?'bg-slate-100 font-semibold text-slate-950':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><span className="grid w-5 place-items-center">{item.icon}</span>{item.label}{item.label==='Automations'&&<span className="ml-auto rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-700">3</span>}</button>)}</div>)}</nav><div className="border-t border-slate-100 p-4"><button onClick={()=>setShowBusiness(true)} className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left hover:bg-slate-50"><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-200 text-xs font-bold">VH</div><div className="min-w-0"><div className="truncate text-sm font-medium">Business Admin</div><div className="truncate text-xs text-slate-400">Moneymatters business</div></div></button></div></aside>
    {mobileOpen&&<div className="fixed inset-0 z-50 bg-slate-950/30 lg:hidden" onClick={()=>setMobileOpen(false)}><aside onClick={e=>e.stopPropagation()} className="h-full w-72 bg-white p-4 shadow-2xl"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 font-bold text-white">M</div><b>Moneymatters</b></div>{navGroups.flatMap(g=>g.items).map(item=><button key={item.label} onClick={()=>go(item.label)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-slate-600">{item.icon}<span>{item.label}</span></button>)}</aside></div>}
    <main className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-[#f7f8fa]/90 px-4 py-3 backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1500px] items-center gap-3"><button onClick={()=>setMobileOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white lg:hidden">☰</button><div className="relative flex-1"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-16 text-sm outline-none focus:border-slate-400" placeholder="Search customers, invoices, products…"/><span className="absolute right-3 top-1/2 hidden -translate-y-1/2 text-[10px] text-slate-400 md:block">Ctrl K</span></div><button onClick={()=>notify('No new notifications')} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white">♢</button><button onClick={()=>setShowBusiness(true)} className="hidden rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium md:block">Business ▾</button></div></header><div className="mx-auto max-w-[1500px] space-y-7 px-4 py-7 md:px-8">{content}</div></main>
    {showBusiness&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Business profile</p><h2 className="mt-1 text-xl font-semibold">Moneymatters business</h2><p className="mt-1 text-sm text-slate-500">Your logo, colors and document templates are business-specific.</p></div><button onClick={()=>setShowBusiness(false)} className="text-2xl text-slate-400">×</button></div><div className="mt-6 rounded-2xl border border-dashed border-slate-300 p-6 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-slate-100 text-xl font-bold">M</div><p className="mt-3 text-sm font-semibold">Business logo</p><p className="mt-1 text-xs text-slate-400">PNG, JPG, WebP or SVG · up to 5 MB</p><button onClick={()=>notify('Logo upload control opened')} className="mt-4 rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Upload / replace logo</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['Primary','#2563EB'],['Secondary','#0F172A'],['Accent','#10B981']].map(([x,c])=><div key={x} className="rounded-xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{x}</p><div className="mt-2 h-8 rounded-lg" style={{background:c}}/></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2">{['Quotation','Invoice','Receipt'].map(x=><button key={x} onClick={()=>notify(`${x} template selector opened`)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-medium">{x} template</button>)}</div><button onClick={()=>setShowBusiness(false)} className="mt-6 w-full rounded-xl bg-slate-950 py-3 text-sm font-semibold text-white">Save business settings</button></div></div>}
    {toast&&<div className="fixed bottom-5 right-5 z-[80] rounded-xl bg-slate-950 px-4 py-3 text-sm font-medium text-white shadow-xl">{toast}</div>}
  </div>;
}
