'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase';

const types=['customers','vendors','products_services','accounts','invoices','bills','payments','bank_transactions','opening_balances'];

function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());cell='';if(row.some(Boolean))rows.push(row);row=[];}else cell+=c;}if(cell||row.length){row.push(cell.trim());rows.push(row);}if(!rows.length)return [];const headers=rows[0];return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}

export default function DataMigrationPage(){const [type,setType]=useState('customers');const [file,setFile]=useState<File|null>(null);const [rows,setRows]=useState<any[]>([]);const [job,setJob]=useState('');const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
const importFile=async()=>{if(!file)return;setError('');const text=await file.text();try{const data=file.name.toLowerCase().endsWith('.json')?JSON.parse(text):parseCsv(text);if(!Array.isArray(data))throw new Error('File must contain an array of rows');setRows(data);}catch(e){setError(e instanceof Error?e.message:'Invalid file');}};
const stage=async()=>{setBusy(true);setError('');const ctx=await supabase.rpc('get_my_business_context');const businessId=ctx.data?.[0]?.business_id;if(!businessId){setError(ctx.error?.message||'Business context not found');setBusy(false);return;}const r=await supabase.rpc('stage_import_job',{p_business_id:businessId,p_import_type:type,p_source_format:file?.name.toLowerCase().endsWith('.json')?'json':'csv',p_rows:rows});if(r.error)setError(r.error.message);else setJob(r.data);setBusy(false);};
const validate=async()=>{setBusy(true);const r=await supabase.rpc('validate_import_job',{p_import_job_id:job});if(r.error)setError(r.error.message);else setResult(r.data);setBusy(false);};
const commit=async()=>{setBusy(true);const r=await supabase.rpc('commit_import_job',{p_import_job_id:job});if(r.error)setError(r.error.message);else setResult(r.data);setBusy(false);};
const exportAll=async()=>{setBusy(true);const ctx=await supabase.rpc('get_my_business_context');const businessId=ctx.data?.[0]?.business_id;if(!businessId){setError('Business context not found');setBusy(false);return;}const r=await supabase.rpc('export_business_dataset',{p_business_id:businessId});if(r.error)setError(r.error.message);else{const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`moneymatters-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}setBusy(false);};
return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Data management</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Migration, Import & Export</h1><p className="mt-2 text-sm text-slate-500">Stage → validate → commit. Financial imports never bypass accounting controls.</p></div><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Import type<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2 font-normal">{types.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold md:col-span-2">CSV / JSON file<input type="file" accept=".csv,.json" onChange={e=>{setFile(e.target.files?.[0]||null);setRows([]);setJob('');setResult(null)}} className="mt-2 block w-full rounded-xl border p-2 font-normal"/></label></div><div className="mt-5 flex flex-wrap gap-2"><button disabled={!file||busy} onClick={importFile} className="rounded-xl border px-4 py-2 text-sm font-semibold">Read file</button><button disabled={!rows.length||busy} onClick={stage} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Stage import ({rows.length})</button><button disabled={!job||busy} onClick={validate} className="rounded-xl border px-4 py-2 text-sm font-semibold">Validate</button><button disabled={!job||result?.error_count>0||busy} onClick={commit} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Commit</button><button disabled={busy} onClick={exportAll} className="rounded-xl border px-4 py-2 text-sm font-semibold">Export full business JSON</button></div>{job&&<p className="mt-4 text-xs text-slate-500">Import job: {job}</p>}{error&&<div className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{result&&<pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-white">{JSON.stringify(result,null,2)}</pre>}</section></div></main>}
