'use client';

import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Product={id:string;name:string;sku:string|null;description:string|null;item_type:string;unit:string|null;sales_price:number;default_tax_rate_id:string|null;discount_enabled:boolean;max_discount_type:string;max_discount_value:number};
type Form={name:string;sku:string;itemType:'product'|'service';hsn:string;unit:string;purchasePrice:string;salesPrice:string;description:string;inventoryTracked:boolean;openingStock:string;openingCost:string;reorderLevel:string;reorderQuantity:string;barcode:string;trackBatches:boolean;trackSerials:boolean;discountEnabled:boolean;discountType:'percent'|'amount';discountValue:string;sellEnabled:boolean;purchaseEnabled:boolean;guaranteeEnabled:boolean;guaranteeMonths:string;guaranteeDescription:string;warrantyEnabled:boolean;warrantyMonths:string;warrantyDescription:string};
const PRODUCT_UNITS=[['pcs','Piece / Nos'],['kg','Kilogram'],['g','Gram'],['mg','Milligram'],['ton','Tonne'],['L','Litre'],['mL','Millilitre'],['m','Meter'],['cm','Centimeter'],['mm','Millimeter'],['m²','Square metre'],['sq ft','Square foot'],['m³','Cubic metre'],['doz','Dozen'],['pair','Pair'],['set','Set'],['box','Box'],['pack','Pack'],['carton','Carton'],['bag','Bag'],['bottle','Bottle'],['can','Can'],['roll','Roll'],['bundle','Bundle'],['sheet','Sheet']];
const SERVICE_UNITS=[['hour','Hour'],['day','Day'],['week','Week'],['month','Month'],['year','Year'],['visit','Visit'],['session','Session'],['job','Job'],['project','Project']];
const blank:Form={name:'',sku:'',itemType:'product',hsn:'',unit:'',purchasePrice:'',salesPrice:'',description:'',inventoryTracked:true,openingStock:'0',openingCost:'0',reorderLevel:'0',reorderQuantity:'0',barcode:'',trackBatches:false,trackSerials:false,discountEnabled:true,discountType:'percent',discountValue:'0',sellEnabled:true,purchaseEnabled:true,guaranteeEnabled:false,guaranteeMonths:'',guaranteeDescription:'',warrantyEnabled:false,warrantyMonths:'',warrantyDescription:''};
function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 ${p.className||''}`}/>}
function Select(p:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...p} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 ${p.className||''}`}/>}
function Field({label,children,wide=false,required=false,help}:{label:string;children:React.ReactNode;wide?:boolean;required?:boolean;help?:string}){return <label className={`${wide?'sm:col-span-2 ':''}block text-xs font-semibold text-slate-600`}>{label}{required?' *':''}<div className="mt-1">{children}</div>{help&&<span className="mt-1 block text-[11px] font-normal text-slate-400">{help}</span>}</label>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 p-4"><h3 className="font-semibold">{title}</h3><div className="mt-3">{children}</div></section>}

export default function ItemServiceModal({open,businessId,onClose,onCreated,initialItemType='product'}:{open:boolean;businessId:string;onClose:()=>void;onCreated:(item:Product)=>void;initialItemType?:'product'|'service'}){
 const[f,setF]=useState<Form>({...blank});const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{if(open){setF({...blank,itemType:initialItemType});setError('')}},[open,initialItemType]);
 useEffect(()=>{if(f.itemType==='service')setF(x=>({...x,unit:x.unit||'',inventoryTracked:false,openingStock:'0',openingCost:'0',reorderLevel:'0',reorderQuantity:'0',barcode:'',trackBatches:false,trackSerials:false,guaranteeEnabled:false,guaranteeMonths:'',guaranteeDescription:'',warrantyEnabled:false,warrantyMonths:'',warrantyDescription:''}))},[f.itemType]);
 const units=f.itemType==='service'?SERVICE_UNITS:PRODUCT_UNITS;const profit=Number(f.salesPrice||0)-Number(f.purchasePrice||0);const profitPct=Number(f.purchasePrice||0)>0?profit/Number(f.purchasePrice||0)*100:0;
 if(!open)return null;
 const save=async()=>{if(!f.name.trim()){setError('Name is required.');return}if(f.itemType==='product'&&!f.unit.trim()){setError('Billing unit is required for products.');return}if(f.guaranteeEnabled&&(Number(f.guaranteeMonths)<1||Number(f.guaranteeMonths)>1200)){setError('Guarantee must be between 1 and 1200 months.');return}if(f.warrantyEnabled&&(Number(f.warrantyMonths)<1||Number(f.warrantyMonths)>1200)){setError('Warranty must be between 1 and 1200 months.');return}setBusy(true);setError('');const service=f.itemType==='service';const payload={business_id:businessId,name:f.name.trim(),sku:f.sku.trim()||null,description:f.description.trim()||null,item_type:f.itemType,unit:f.unit.trim()||null,hsn_sac:f.hsn.trim()||null,sales_price:Math.max(0,Number(f.salesPrice)||0),purchase_price:Math.max(0,Number(f.purchasePrice)||0),inventory_tracked:service?false:f.inventoryTracked,sell_enabled:f.sellEnabled,purchase_enabled:f.purchaseEnabled,discount_enabled:f.discountEnabled,max_discount_type:f.discountType,max_discount_value:Math.max(0,Number(f.discountValue)||0),reorder_level:service?0:Math.max(0,Number(f.reorderLevel)||0),reorder_quantity:service?0:Math.max(0,Number(f.reorderQuantity)||0),barcode:service?null:(f.barcode.trim()||null),track_batches:service?false:f.trackBatches,track_serials:service?false:f.trackSerials,opening_stock:service?0:Math.max(0,Number(f.openingStock)||0),opening_stock_cost:service?0:Math.max(0,Number(f.openingCost)||0),guarantee_enabled:service?false:f.guaranteeEnabled,guarantee_months:service||!f.guaranteeEnabled?null:Number(f.guaranteeMonths),guarantee_description:service||!f.guaranteeEnabled?null:f.guaranteeDescription.trim()||null,warranty_enabled:service?false:f.warrantyEnabled,warranty_months:service||!f.warrantyEnabled?null:Number(f.warrantyMonths),warranty_description:service||!f.warrantyEnabled?null:f.warrantyDescription.trim()||null,is_active:true};const r=await supabase.from('products_services').insert(payload).select('id,name,sku,description,item_type,unit,sales_price,default_tax_rate_id,discount_enabled,max_discount_type,max_discount_value').single();if(r.error){setError(r.error.message);setBusy(false);return}onCreated(r.data);setBusy(false);onClose()};
 return <div className="fixed inset-0 z-50 bg-slate-950/40 p-3 sm:p-6"><div className="mx-auto max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white/95 px-6 py-4"><div><p className="text-[11px] font-bold uppercase tracking-widest text-violet-600">Master data</p><h2 className="text-xl font-semibold">Create {f.itemType==='product'?'product':'service'}</h2></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100">×</button></div><div className="space-y-5 p-6">
 <div className="grid gap-4 sm:grid-cols-2"><Field label="Name" required><Input autoFocus placeholder={f.itemType==='product'?'Product name':'Service name'} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Type"><Select value={f.itemType} onChange={e=>setF({...f,itemType:e.target.value as 'product'|'service'})}><option value="product">Product</option><option value="service">Service</option></Select></Field><Field label="SKU / Code"><Input value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/></Field><Field label="SAC / HSN"><Input value={f.hsn} onChange={e=>setF({...f,hsn:e.target.value})}/></Field><Field label="Billing unit" required={f.itemType==='product'}><Select value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}><option value="">Select unit…</option>{units.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label={f.itemType==='service'?'Purchase / subcontract cost':'Purchase price'}><Input type="number" min="0" value={f.purchasePrice} onChange={e=>setF({...f,purchasePrice:e.target.value})}/></Field><Field label="Selling price"><Input type="number" min="0" value={f.salesPrice} onChange={e=>setF({...f,salesPrice:e.target.value})}/></Field></div>
 <div className="rounded-2xl border border-violet-100 bg-violet-50/60 p-4"><b>Profit: ₹{profit.toFixed(2)} · {profitPct.toFixed(2)}%</b><p className="mt-1 text-[11px] text-slate-500">Profit % is calculated against purchase price.</p></div>
 <Field label="Description" wide><textarea className="min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field>
 {f.itemType==='service'?<div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-500">Service mode · Services do not use stock, opening units, reorder levels, barcode, batches or serial numbers. Billing unit and pricing remain available.</div>:<Section title="Inventory"><div className="grid gap-4 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm sm:col-span-2"><input type="checkbox" checked={f.inventoryTracked} onChange={e=>setF({...f,inventoryTracked:e.target.checked})}/> Track inventory</label><Field label="Opening stock"><Input type="number" min="0" value={f.openingStock} onChange={e=>setF({...f,openingStock:e.target.value})}/></Field><Field label="Opening stock cost"><Input type="number" min="0" value={f.openingCost} onChange={e=>setF({...f,openingCost:e.target.value})}/></Field><Field label="Reorder level"><Input type="number" min="0" value={f.reorderLevel} onChange={e=>setF({...f,reorderLevel:e.target.value})}/></Field><Field label="Reorder quantity"><Input type="number" min="0" value={f.reorderQuantity} onChange={e=>setF({...f,reorderQuantity:e.target.value})}/></Field><Field label="Barcode"><Input value={f.barcode} onChange={e=>setF({...f,barcode:e.target.value})}/></Field><div className="flex gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.trackBatches} onChange={e=>setF({...f,trackBatches:e.target.checked})}/> Batches</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.trackSerials} onChange={e=>setF({...f,trackSerials:e.target.checked})}/> Serial numbers</label></div></div></Section>}
 <Section title="Discount"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={f.discountEnabled} onChange={e=>setF({...f,discountEnabled:e.target.checked})}/> Allow discount</label>{f.discountEnabled&&<div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Maximum discount type"><Select value={f.discountType} onChange={e=>setF({...f,discountType:e.target.value as 'percent'|'amount'})}><option value="percent">Percent</option><option value="amount">Amount</option></Select></Field><Field label="Maximum discount"><Input type="number" min="0" value={f.discountValue} onChange={e=>setF({...f,discountValue:e.target.value})}/></Field></div>}</Section>
 {f.itemType==='product'&&<Section title="Guarantee & warranty"><div className="grid gap-4 sm:grid-cols-2"><div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.guaranteeEnabled} onChange={e=>setF({...f,guaranteeEnabled:e.target.checked})}/> Guarantee enabled</label>{f.guaranteeEnabled&&<div className="mt-3 space-y-3"><Field label="Guarantee (months)"><Input type="number" min="1" value={f.guaranteeMonths} onChange={e=>setF({...f,guaranteeMonths:e.target.value})}/></Field><Field label="Description"><Input value={f.guaranteeDescription} onChange={e=>setF({...f,guaranteeDescription:e.target.value})}/></Field></div>}</div><div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.warrantyEnabled} onChange={e=>setF({...f,warrantyEnabled:e.target.checked})}/> Warranty enabled</label>{f.warrantyEnabled&&<div className="mt-3 space-y-3"><Field label="Warranty (months)"><Input type="number" min="1" value={f.warrantyMonths} onChange={e=>setF({...f,warrantyMonths:e.target.value})}/></Field><Field label="Description"><Input value={f.warrantyDescription} onChange={e=>setF({...f,warrantyDescription:e.target.value})}/></div>}</div></div></Section>}
 <Section title="Availability"><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={f.sellEnabled} onChange={e=>setF({...f,sellEnabled:e.target.checked})}/> Sell enabled</label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={f.purchaseEnabled} onChange={e=>setF({...f,purchaseEnabled:e.target.checked})}/> Purchase enabled</label></div></Section>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 </div><div className="sticky bottom-0 flex justify-end gap-2 border-t border-slate-200 bg-white px-6 py-4"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="button" disabled={busy||!f.name.trim()||(f.itemType==='product'&&!f.unit.trim())} onClick={save} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Create & add to invoice'}</button></div></div></div>;
}
