'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';
import { FormButton } from '../../form-primitives';

type Props={id:string};
type Customer={id:string;display_name:string;legal_name:string|null;email:string|null;phone:string|null;tax_id:string|null;payment_terms_days:number;payment_reminders_enabled:boolean;reminder_days_before_due:number;default_discount_type:string;default_discount_value:number;notes:string|null};
type Summary={lifetime_invoiced:number;lifetime_paid_on_invoices:number;outstanding:number;overdue:number;last_payment_date:string|null;lifetime_payments:number;invoice_count:number;quotation_count:number;receipt_count:number;last_invoice_date:string|null};
type Entry={entry_date:string;entry_type:string;reference:string;source_id:string;debit:number;credit:number;running_balance:number};
type Invoice={id:string;invoice_number:string;invoice_date:string;due_date:string;status:string;total:number;amount_paid:number;balance_due:number};
type Payment={id:string;payment_date:string;amount:number;method:string;reference:string|null;invoice_id:string|null};
type Receipt={id:string;receipt_number:string;receipt_date:string;amount:number;payment_method:string|null;reference_number:string|null};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const tabs=['overview','invoices','payments','receipts','statement'];
function Card({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_10px_35px_rgba(15,23,42,.045)] ${className}`}>{children}</section>}
function Status({value}:{value:string}){return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold capitalize text-slate-600">{value.replaceAll('_',' ')}</span>}

export default function Customer360Workspace({id}:Props){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[customer,setCustomer]=useState<Customer|null>(null),[summary,setSummary]=useState<Summary|null>(null),[entries,setEntries]=useState<Entry[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[payments,setPayments]=useState<Payment[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{setLoading(true);setError('');const cr=await supabase.rpc('get_my_business_context');const c=cr.data?.[0] as BusinessContext|undefined;if(!c){setError('Business context not available.');setLoading(false);return}setCtx(c);const [cu,su,st,iv,pa,re]=await Promise.all([supabase.from('customers').select('id,display_name,legal_name,email,phone,tax_id,payment_terms_days,payment_reminders_enabled,reminder_days_before_due,default_discount_type,default_discount_value,notes').eq('id',id).eq('business_id',c.business_id).maybeSingle(),supabase.from('customer_360_summary').select('*').eq('customer_id',id).eq('business_id',c.business_id).maybeSingle(),supabase.from('customer_statement_running').select('entry_date,entry_type,reference,source_id,debit,credit,running_balance').eq('customer_id',id).eq('business_id',c.business_id).order('entry_date',{ascending:true}),supabase.from('invoices').select('id,invoice_number,invoice_date,due_date,status,total,amount_paid,balance_due').eq('customer_id',id).eq('business_id',c.business_id).order('invoice_date',{ascending:false}),supabase.from('payments').select('id,payment_date,amount,method,reference,invoice_id').eq('customer_id',id).eq('business_id',c.business_id).eq('direction','inbound').order('payment_date',{ascending:false}),supabase.from('receipts').select('id,receipt_number,receipt_date,amount,payment_method,reference_number').eq('customer_id',id).eq('business_id',c.business_id).order('receipt_date',{ascending:false})]);if(cu.error||!cu.data){setError(cu.error?.message||'Customer not found');setLoading(false);return}setCustomer(cu.data);setSummary(su.data as Summary|null);setEntries((st.data||[]) as Entry[]);setInvoices((iv.data||[]) as Invoice[]);setPayments((pa.data||[]) as Payment[]);setReceipts((re.data||[]) as Receipt[]);setLoading(false)})()},[id]);
 const opening=useMemo(()=>entries.length?Number(entries[0].running_balance)-Number(entries[0].debit)+Number(entries[0].credit:0),[entries]);
 if(loading)return <main className="min-h-screen bg-[#f7f6fb] p-6"><div className="mx-auto max-w-7xl text-sm text-slate-400">Loading Customer 360…</div></main>;
 if(error||!customer)return <main className="min-h-screen bg-[#f7f6fb] p-6"><Card className="mx-auto max-w-2xl p-8"><h1 className="text-xl font-semibold">Customer unavailable</h1><p className="mt-2 text-sm text-slate-500">{error||'Customer not found.'}</p><a className="mt-5 inline-block rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" href="/next-workspace/customers">Back to customers</a></Card></main>;
 const whatsapp=customer.phone?`https://wa.me/${customer.phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${customer.display_name}, your outstanding balance is ${money(Number(summary?.outstanding||0))}.`)}`:null;
 return <main className="min-h-screen bg-[#f7f6fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl"><div className="mb-5 flex items-center gap-2 text-sm"><a href="/next-workspace/customers" className="font-semibold text-slate-500">← Customers</a><span className="text-slate-300">/</span><span className="text-slate-500">Customer 360</span></div><Card className="overflow-hidden"><div className="p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-violet-600">Customer 360</p><h1 className="mt-1 text-3xl font-semibold">{customer.display_name}</h1><p className="mt-2 text-sm text-slate-500">{customer.phone||'No phone'} · {customer.email||'No email'}{customer.tax_id?` · ${customer.tax_id}`:''}</p></div><div className="flex flex-wrap gap-2"><a href={`/next-workspace/invoices/new?customer=${id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">＋ Invoice</a><a href="/next-workspace/quotation" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">＋ Quotation</a>{whatsapp&&<a target="_blank" rel="noreferrer" href={whatsapp} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">WhatsApp</a>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Outstanding" value={money(Number(summary?.outstanding||0))}/><Metric label="Overdue" value={money(Number(summary?.overdue||0))}/><Metric label="Lifetime sales" value={money(Number(summary?.lifetime_invoiced||0))}/><Metric label="Last payment" value={summary?.last_payment_date||'—'}/></div></div><div className="flex gap-1 overflow-x-auto border-t border-slate-100 px-3 pt-2 sm:px-5">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-t-xl px-4 py-3 text-xs font-semibold capitalize ${tab===t?'bg-slate-50 text-slate-950':'text-slate-500 hover:text-slate-900'}`}>{t}</button>)}</div></Card>
 {tab==='overview'&&<div className="mt-5 grid gap-5 lg:grid-cols-3"><Card className="p-6 lg:col-span-2"><h2 className="font-semibold">Financial relationship</h2><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4"><Mini label="Invoices" value={String(summary?.invoice_count||0)}/><Mini label="Payments" value={money(Number(summary?.lifetime_payments||0))}/><Mini label="Receipts" value={String(summary?.receipt_count||0)}/><Mini label="Quotations" value={String(summary?.quotation_count||0)}/></div><div className="mt-6 border-t border-slate-100 pt-5"><h3 className="text-sm font-semibold">Recent activity</h3>{entries.slice(-6).reverse().map(e=><div key={`${e.entry_type}-${e.source_id}`} className="flex items-center justify-between border-b border-slate-50 py-3 text-sm"><div><b className="capitalize">{e.entry_type}</b><span className="ml-2 text-xs text-slate-400">{e.reference} · {e.entry_date}</span></div><b>{e.debit?money(Number(e.debit)):`-${money(Number(e.credit))}`}</b></div>)}{!entries.length&&<p className="py-6 text-sm text-slate-400">No financial activity yet.</p>}</div></Card><Card className="p-6"><h2 className="font-semibold">Customer preferences</h2><div className="mt-4 space-y-3 text-sm"><p>Payment terms <b className="float-right">{customer.payment_terms_days?`Net ${customer.payment_terms_days}`:'Due on receipt'}</b></p><p>Reminders <b className="float-right">{customer.payment_reminders_enabled?`${customer.reminder_days_before_due} days before`:'Off'}</b></p><p>Default discount <b className="float-right">{customer.default_discount_type==='percent'?`${customer.default_discount_value}%`:customer.default_discount_type==='amount'?money(customer.default_discount_value):'None'}</b></p></div><div className="mt-6 border-t border-slate-100 pt-5"><a href={`/next-workspace/customers`} className="text-sm font-semibold text-violet-700">Edit customer settings →</a></div></Card></div>}
 {tab==='invoices'&&<Table title="Invoices" headers={['Invoice','Date','Due','Status','Total','Balance']} rows={invoices.map(i=>[i.invoice_number,i.invoice_date,i.due_date,<Status key={i.id} value={i.status}/>,money(Number(i.total)),money(Number(i.balance_due))])}/>} 
 {tab==='payments'&&<Table title="Payments" headers={['Date','Amount','Method','Reference']} rows={payments.map(p=>[p.payment_date,money(Number(p.amount)),p.method,p.reference||'—'])}/>} 
 {tab==='receipts'&&<Table title="Receipts" headers={['Receipt','Date','Amount','Method','Reference']} rows={receipts.map(r=>[r.receipt_number,r.receipt_date,money(Number(r.amount)),r.payment_method||'—',r.reference_number||'—'])}/>} 
 {tab==='statement'&&<Card className="mt-5 overflow-hidden"><div className="flex flex-col gap-3 p-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Statement of account</p><h2 className="mt-1 text-xl font-semibold">{customer.display_name}</h2><p className="mt-1 text-sm text-slate-500">Opening {money(opening)} · Current outstanding {money(Number(summary?.outstanding||0))}</p></div><button onClick={()=>window.print()} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Print / PDF</button></div><Statement entries={entries}/></Card>}</div></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><span className="text-xs text-slate-400">{label}</span><b className="mt-1 block text-xl">{value}</b></div>}
function Mini({label,value}:{label:string;value:string}){return <div><span className="text-xs text-slate-400">{label}</span><b className="mt-1 block">{value}</b></div>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:React.ReactNode[][]}){return <Card className="mt-5 overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="font-semibold">{title}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr>{headers.map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-slate-100">{r.map((v,j)=><td key={j} className="px-5 py-4">{v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="px-5 py-14 text-center text-sm text-slate-400">Nothing here yet.</td></tr>}</tbody></table></div></Card>}
function Statement({entries}:{entries:Entry[]}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Document</th><th className="px-5 py-3">Debit</th><th className="px-5 py-3">Credit</th><th className="px-5 py-3">Balance</th></tr></thead><tbody>{entries.map(e=><tr key={`${e.entry_type}-${e.source_id}`} className="border-t border-slate-100"><td className="px-5 py-4">{e.entry_date}</td><td className="px-5 py-4"><b className="capitalize">{e.entry_type}</b><span className="ml-2 text-xs text-slate-400">{e.reference}</span></td><td className="px-5 py-4">{Number(e.debit)?money(Number(e.debit)):'—'}</td><td className="px-5 py-4">{Number(e.credit)?money(Number(e.credit)):'—'}</td><td className="px-5 py-4 font-semibold">{money(Number(e.running_balance))}</td></tr>)}{!entries.length&&<tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-slate-400">No statement activity yet.</td></tr>}</tbody></table></div>}
