'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Params = { params: Promise<{ id: string }> };
type Customer = { id:string; display_name:string; legal_name:string|null; email:string|null; phone:string|null; tax_id:string|null; payment_terms_days:number; payment_reminders_enabled:boolean; reminder_days_before_due:number; default_discount_type:string; default_discount_value:number; notes:string|null };
type Summary = { lifetime_invoiced:number; lifetime_paid_on_invoices:number; outstanding:number; overdue:number; last_payment_date:string|null; lifetime_payments:number; invoice_count:number; quotation_count:number; receipt_count:number; last_invoice_date:string|null };
type Entry = { entry_date:string; entry_type:string; reference:string; source_id:string; debit:number; credit:number; running_balance:number };
type Invoice = { id:string; invoice_number:string; invoice_date:string; due_date:string; status:string; total:number; amount_paid:number; balance_due:number };
type Quote = { id:string; quotation_number:string; quotation_date:string; status:string; total:number };
type Payment = { id:string; payment_date:string; amount:number; method:string; reference:string|null; invoice_id:string|null };
type Receipt = { id:string; receipt_number:string; receipt_date:string; amount:number; payment_method:string|null; reference_number:string|null };

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.05)] ${className}`}>{children}</section>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{children}</span>}

export default function Customer360({params}:Params){
 const [id,setId]=useState(''),[ctx,setCtx]=useState<BusinessContext|null>(null),[customer,setCustomer]=useState<Customer|null>(null),[summary,setSummary]=useState<Summary|null>(null),[entries,setEntries]=useState<Entry[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[payments,setPayments]=useState<Payment[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);
 useEffect(()=>{if(!id)return; (async()=>{setLoading(true);setError('');const cr=await supabase.rpc('get_my_business_context');const c=cr.data?.[0] as BusinessContext|undefined;if(!c){setError('Business context not available.');setLoading(false);return}setCtx(c);
  const [cu,su,st,iv,qu,pa,re]=await Promise.all([
   supabase.from('customers').select('id,display_name,legal_name,email,phone,tax_id,payment_terms_days,payment_reminders_enabled,reminder_days_before_due,default_discount_type,default_discount_value,notes').eq('id',id).eq('business_id',c.business_id).maybeSingle(),
   supabase.from('customer_360_summary').select('lifetime_invoiced,lifetime_paid_on_invoices,outstanding,overdue,last_payment_date,lifetime_payments,invoice_count,quotation_count,receipt_count,last_invoice_date').eq('customer_id',id).eq('business_id',c.business_id).maybeSingle(),
   supabase.from('customer_statement_running').select('entry_date,entry_type,reference,source_id,debit,credit,running_balance').eq('customer_id',id).eq('business_id',c.business_id).order('entry_date',{ascending:true}),
   supabase.from('invoices').select('id,invoice_number,invoice_date,due_date,status,total,amount_paid,balance_due').eq('customer_id',id).eq('business_id',c.business_id).order('invoice_date',{ascending:false}),
   supabase.from('quotations').select('id,quotation_number,quotation_date,status,total').eq('customer_id',id).eq('business_id',c.business_id).order('quotation_date',{ascending:false}),
   supabase.from('payments').select('id,payment_date,amount,method,reference,invoice_id').eq('customer_id',id).eq('business_id',c.business_id).eq('direction','inbound').order('payment_date',{ascending:false}),
   supabase.from('receipts').select('id,receipt_number,receipt_date,amount,payment_method,reference_number').eq('customer_id',id).eq('business_id',c.business_id).order('receipt_date',{ascending:false})
  ]);
  if(cu.error||!cu.data)setError(cu.error?.message||'Customer not found'); else setCustomer(cu.data);
  setSummary(su.data as Summary|null);setEntries((st.data||[]) as Entry[]);setInvoices((iv.data||[]) as Invoice[]);setQuotes((qu.data||[]) as Quote[]);setPayments((pa.data||[]) as Payment[]);setReceipts((re.data||[]) as Receipt[]);setLoading(false);
 })()},[id]);
 const opening=useMemo(()=>{if(!entries.length)return 0;return Number(entries[0].running_balance)-Number(entries[0].debit)+Number(entries[0].credit)},[entries]);
 if(loading)return <main className="min-h-screen bg-[#f6f7fb] p-7"><div className="mx-auto max-w-7xl text-sm text-slate-400">Loading Customer 360…</div></main>;
 if(error||!customer)return <main className="min-h-screen bg-[#f6f7fb] p-7"><div className="mx-auto max-w-3xl"><Card className="p-8"><h1 className="text-xl font-semibold">Customer unavailable</h1><p className="mt-2 text-sm text-slate-500">{error||'The customer could not be found.'}</p><a className="mt-5 inline-block rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" href="/next-workspace/customers">Back to customers</a></Card></div></main>;
 const whatsapp=customer.phone?`https://wa.me/${customer.phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${customer.display_name}, your current outstanding balance is ${money(Number(summary?.outstanding||0))}.` )}`:null;
 const tabs=['overview','transactions','quotations','invoices','payments','receipts','statement','communication'];
 return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl">
  <div className="mb-5 flex flex-wrap items-center gap-3"><a href="/next-workspace/customers" className="text-sm font-semibold text-slate-500">← Customers</a><span className="text-slate-300">/</span><span className="text-sm text-slate-500">Customer 360</span></div>
  <Card className="p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Customer 360</p><h1 className="mt-1 text-3xl font-semibold">{customer.display_name}</h1><p className="mt-1 text-sm text-slate-500">{customer.phone||'No phone'} · {customer.email||'No email'} {customer.tax_id?`· ${customer.tax_id}`:''}</p></div><div className="flex flex-wrap gap-2"><a href="/next-workspace/sales" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">＋ Invoice</a><a href="/next-workspace/quotation" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">＋ Quotation</a><button onClick={()=>window.print()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Print / PDF</button>{whatsapp&&<a target="_blank" rel="noreferrer" href={whatsapp} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">WhatsApp</a>}</div></div>
   <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-4 shadow-none"><span className="text-xs text-slate-400">Outstanding</span><b className="mt-1 block text-2xl">{money(Number(summary?.outstanding||0))}</b></Card><Card className="p-4 shadow-none"><span className="text-xs text-slate-400">Overdue</span><b className="mt-1 block text-2xl text-amber-700">{money(Number(summary?.overdue||0))}</b></Card><Card className="p-4 shadow-none"><span className="text-xs text-slate-400">Lifetime sales</span><b className="mt-1 block text-2xl">{money(Number(summary?.lifetime_invoiced||0))}</b></Card><Card className="p-4 shadow-none"><span className="text-xs text-slate-400">Last payment</span><b className="mt-1 block text-xl">{summary?.last_payment_date||'—'}</b></Card></div>
  </Card>
  <div className="mt-5 flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-t-xl px-4 py-3 text-xs font-semibold capitalize ${tab===t?'bg-white text-slate-950 shadow-sm':'text-slate-500'}`}>{t}</button>)}</div>
  {tab==='overview'&&<div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Financial relationship</h2><div className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><span className="text-slate-400">Invoices</span><b className="block mt-1">{summary?.invoice_count||0}</b></div><div><span className="text-slate-400">Quotations</span><b className="block mt-1">{summary?.quotation_count||0}</b></div><div><span className="text-slate-400">Payments</span><b className="block mt-1">{summary?.lifetime_payments?money(Number(summary.lifetime_payments)):'₹0'}</b></div><div><span className="text-slate-400">Receipts</span><b className="block mt-1">{summary?.receipt_count||0}</b></div></div></Card><Card className="p-6"><h2 className="font-semibold">Collection preferences</h2><div className="mt-4 text-sm"><p>Payment reminders: <b>{customer.payment_reminders_enabled?'On':'Off'}</b></p><p className="mt-2">Reminder: <b>{customer.reminder_days_before_due} days before due</b></p><p className="mt-2">Payment terms: <b>{customer.payment_terms_days ? `Net ${customer.payment_terms_days}` : 'Due on receipt'}</b></p><p className="mt-2">Default discount: <b>{customer.default_discount_type==='percent'?`${customer.default_discount_value}%`:customer.default_discount_type==='amount'?money(customer.default_discount_value):'None'}</b></p></div></Card><Card className="p-6 lg:col-span-2"><h2 className="font-semibold">Recent activity</h2><div className="mt-4 divide-y divide-slate-100">{entries.slice(-8).reverse().map(e=><div key={e.source_id} className="flex items-center justify-between py-3 text-sm"><div><b className="capitalize">{e.entry_type}</b><span className="ml-2 text-slate-400">{e.reference} · {e.entry_date}</span></div><span className="font-semibold">{e.debit?money(Number(e.debit)):`-${money(Number(e.credit))}`}</span></div>)}{!entries.length&&<p className="py-8 text-center text-sm text-slate-400">No financial activity yet.</p>}</div></Card></div>}
  {tab==='transactions'&&<StatementTable entries={entries}/>} 
  {tab==='statement'&&<div className="mt-5"><Card className="p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-slate-400">Statement of account</p><h2 className="mt-1 text-xl font-semibold">{customer.display_name}</h2><p className="mt-1 text-sm text-slate-500">Opening balance {money(opening)} · Outstanding {money(Number(summary?.outstanding||0))}</p></div><button onClick={()=>window.print()} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Download / Print PDF</button></div><div className="mt-6"><StatementTable entries={entries}/></div></Card></div>}
  {tab==='invoices'&&<ListTable title="Invoices" empty="No invoices yet." headers={['Invoice','Date','Due','Status','Total','Outstanding']} rows={invoices.map(i=>[i.invoice_number,i.invoice_date,i.due_date,i.status,money(Number(i.total)),money(Number(i.balance_due))])}/>} 
  {tab==='quotations'&&<ListTable title="Quotations" empty="No quotations yet." headers={['Quotation','Date','Status','Total']} rows={quotes.map(q=>[q.quotation_number,q.quotation_date,q.status,money(Number(q.total))])}/>} 
  {tab==='payments'&&<ListTable title="Payments" empty="No payments yet." headers={['Date','Amount','Method','Reference']} rows={payments.map(p=>[p.payment_date,money(Number(p.amount)),p.method,p.reference||'—'])}/>} 
  {tab==='receipts'&&<ListTable title="Receipts" empty="No receipts yet." headers={['Receipt','Date','Amount','Method','Reference']} rows={receipts.map(r=>[r.receipt_number,r.receipt_date,money(Number(r.amount)),r.payment_method||'—',r.reference_number||'—'])}/>} 
  {tab==='communication'&&<Card className="mt-5 p-6"><h2 className="font-semibold">Communication</h2><p className="mt-2 text-sm text-slate-500">Reminder and delivery history will appear here as automation runs are recorded.</p><div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm"><b>Reminder preference</b><p className="mt-1 text-slate-500">{customer.payment_reminders_enabled?`Enabled · ${customer.reminder_days_before_due} days before due`:'Disabled'}</p></div></Card>}
 </div></main>
}
function StatementTable({entries}:{entries:Entry[]}){return <Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Document</th><th className="px-5 py-3">Debit</th><th className="px-5 py-3">Credit</th><th className="px-5 py-3">Balance</th></tr></thead><tbody>{entries.map(e=><tr key={`${e.entry_type}-${e.source_id}`} className="border-t border-slate-100"><td className="px-5 py-4">{e.entry_date}</td><td className="px-5 py-4"><b className="capitalize">{e.entry_type}</b><span className="ml-2 text-xs text-slate-400">{e.reference}</span></td><td className="px-5 py-4">{Number(e.debit)?money(Number(e.debit)):'—'}</td><td className="px-5 py-4">{Number(e.credit)?money(Number(e.credit)):'—'}</td><td className="px-5 py-4 font-semibold">{money(Number(e.running_balance))}</td></tr>)}{!entries.length&&<tr><td colSpan={5} className="px-5 py-14 text-center text-sm text-slate-400">No statement activity yet.</td></tr>}</tbody></table></div></Card>}
function ListTable({title,headers,rows,empty}:{title:string;headers:string[];rows:string[][];empty:string}){return <Card className="mt-5 overflow-hidden"><div className="p-5"><h2 className="font-semibold">{title}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-400"><tr>{headers.map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-slate-100">{r.map((v,j)=><td key={j} className="px-5 py-4">{j===3&&['paid','accepted','sent'].includes(v.toLowerCase())?<Badge>{v}</Badge>:v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="px-5 py-14 text-center text-sm text-slate-400">{empty}</td></tr>}</tbody></table></div></Card>}
