import { SALES_TEMPLATES, OPERATIONS_TEMPLATES, STATUTORY_TEMPLATES } from '@/app/next-workspace/reports/templates';
export { SALES_TEMPLATES, OPERATIONS_TEMPLATES, STATUTORY_TEMPLATES };
export const REPORT_TEMPLATES=[...SALES_TEMPLATES,...OPERATIONS_TEMPLATES,...STATUTORY_TEMPLATES];
export const REPORT_TEMPLATE_MAP=new Map(REPORT_TEMPLATES.map(template=>[template.id,template]));