'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));

type Bank={id:string;name:string;institution_name:string|null;account_last4:string|null;currency_code:string;is_connected:boolean};
type Tx={id:string;bank_account_id:string;transaction_date:string;description:string|null;reference:string|null;amount:number;direction:string;status:string;balance_after:number|null};
type Rec={id:string;bank_account_id:string;period_start:string;period_end:string;statement_ending_balance:number;book_ending_balance:number;difference:number;status:string;locked_at:string|null};

export default function Banking(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[banks,setBanks]=useState<Bank[]>([]),[tx,setTx]=useState<Tx[]>([]),[rec,setRec]=useState<Rec[]>([]),[q,setQ]=useState(''),[account,setAccount]=useState('all'),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const [ba,bt,br]=await Promise.all([supabase.from('bank_accounts').select('id,name,institution_name,account_last4,currency_code,is_connected').eq('business_id',b.business_id).eq('is_active',true).order('name'),supabase.from('bank_transactions').select('id,bank_account_id,transaction_date,description,reference,amount,direction,status,balance_after').in('bank_account_id',[]),supabase.from('bank_reconciliations').select('id,bank_account_id,period_start,period_end,statement_ending_balance,book_ending_balance,difference,status,locked_at').eq('business_id',b.business_id).order('period_end',{ascending:false}).limit(20)]);const accounts=ba.data||[];setBanks(accounts);if(accounts.length){const r=await supabase.from('bank_transactions').select('id,bank_account_id,transaction_date,description,reference,amount,direction,status,balance_after').in('bank_account_id',accounts.map(x=>x.id)).order('transaction_date',{ascending:false}).limit(100);setTx(r.data||[])}setRec(br.data||[]);setLoading(false)})()},[]);
 const filtered=useMemo(()=>tx.filter(x=>(account==='all'||x.bank_account_id===account)&&`${x.description||''} ${x.reference||''} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[tx,account,q]);
 const unmatched=tx.filter(x=>!['matched','reconciled'].includes(String(x.status).toLowerCase())).length;
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading banking…</div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1320px]">
  <header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Money</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Banking</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">See your bank activity, match transactions and keep the bank balance tied to the books.</p></div><div className="flex gap-2"><button onClick={()=>location.href='/next-workspace/data-migration'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Import statement</button><button onClick={()=>location.href='/next-workspace/accounting'} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Accounting</button></div></header>
  <div className="grid gap-4 sm:grid-cols-3"><Kpi title="Bank accounts" value={String(banks.length)} note={`${banks.filter(x=>x.is_connected).length} connected`}/><Kpi title="Needs review" value={String(unmatched)} note="Unmatched or imported transactions" tone="amber"/><Kpi title="Last reconciliation" value={rec[0]?.status||'Not started'} note={rec[0]?`${rec[0].period_start} → ${rec[0].period_end}`:'No reconciliation yet'} tone={rec[0]?.difference===0?'green':'violet'}/></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Bank accounts</h2><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-bold text-violet-700">{banks.length}</span></div><div className="space-y-2">{banks.map(b=><button key={b.id} onClick={()=>setAccount(b.id)} className={`w-full rounded-xl border p-3 text-left ${account===b.id?'border-violet-200 bg-violet-50':'border-slate-100 hover:bg-violet-50/50'}`}><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-100 text-violet-700">₹</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{b.name}</b><span className="text-xs text-slate-500">{b.institution_name||'Bank'} {b.account_last4?`••${b.account_last4}`:''}</span></span><span className={`h-2 w-2 rounded-full ${b.is_connected?'bg-emerald-500':'bg-slate-300'}`}/></div></button>)}{!banks.length&&<div className="rounded-xl bg-violet-50 p-4 text-xs leading-5 text-violet-800">No bank account is configured yet. Add or import a bank account before reconciliation.</div>}<button onClick={()=>location.href='/next-workspace/data-migration'} className="w-full rounded-xl border border-dashed border-violet-200 px-3 py-2.5 text-xs font-semibold text-violet-700 hover:bg-violet-50">＋ Add / import account</button></div></section>
   <section className="rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="border-b border-slate-100 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="relative flex-1"><span className="absolute left-3 top-2.5 text-slate-400">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search bank transactions…" className="w-full rounded-xl border border-slate-200 bg-[#fbfaff] py-2.5 pl-9 pr-4 text-sm outline-none"/></div><select value={account} onChange={e=>setAccount(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="all">All accounts</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div></div><div className="hidden grid-cols-[110px_1fr_120px_120px] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>Date</span><span>Description</span><span>Status</span><span className="text-right">Amount</span></div><div className="divide-y divide-slate-100">{filtered.slice(0,50).map(x=><div key={x.id} className="grid gap-2 px-4 py-4 sm:grid-cols-[110px_1fr_120px_120px] sm:items-center sm:gap-3 sm:px-5"><span className="text-xs text-slate-500">{x.transaction_date}</span><span className="min-w-0"><b className="block truncate text-sm">{x.description||'Bank transaction'}</b><span className="text-xs text-slate-400">{x.reference||'No reference'}</span></span><span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${String(x.status).toLowerCase().includes('match')?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{String(x.status||'review').replaceAll('_',' ')}</span></span><b className={`text-sm sm:text-right ${String(x.direction).toLowerCase().includes('out')||Number(x.amount)<0?'text-slate-800':'text-emerald-700'}`}>{money(Number(x.amount||0))}</b></div>)}{!filtered.length&&<div className="p-10 text-center text-sm text-slate-500">No bank transactions match your filter.</div>}</div></section></div>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Reconciliation</h2><p className="mt-1 text-xs text-slate-500">A reconciliation locks the reviewed period and verifies the bank balance against the books.</p></div>{rec[0]&&<span className={`rounded-full px-3 py-1 text-xs font-semibold ${rec[0].difference===0?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{rec[0].difference===0?'Balanced':'Difference '+money(rec[0].difference)}</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#faf8ff] p-4"><span className="text-xs text-slate-500">Statement ending</span><b className="mt-1 block text-lg">{rec[0]?money(rec[0].statement_ending_balance):'—'}</b></div><div className="rounded-xl bg-[#faf8ff] p-4"><span className="text-xs text-slate-500">Book ending</span><b className="mt-1 block text-lg">{rec[0]?money(rec[0].book_ending_balance):'—'}</b></div><div className="rounded-xl bg-[#faf8ff] p-4"><span className="text-xs text-slate-500">Lock status</span><b className="mt-1 block text-lg">{rec[0]?.locked_at?'Locked':'Open'}</b></div></div></section>
 </div></main>;
}
function Kpi({title,value,note,tone='violet'}:{title:string;value:string;note:string;tone?:string}){const cls=tone==='green'?'bg-emerald-50 text-emerald-700':tone==='amber'?'bg-amber-50 text-amber-700':'bg-violet-50 text-violet-700';return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><span className="text-xs font-semibold text-slate-500">{title}</span><span className={`rounded-lg px-2 py-1 text-[10px] font-bold ${cls}`}>●</span></div><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></section>}
