'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.045)] ${className}`}>{children}</section>;

type Account={id:string;code:string;name:string;account_type:string;normal_balance:string};
type Line={account_id:string;debit:number;credit:number};
type Entry={id:string;entry_date:string;description:string;source_type:string;status:string;total_debit:number;total_credit:number};

export default function AccountingCockpit(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[balances,setBalances]=useState<Record<string,number>>({}),[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const[a,j,l]=await Promise.all([supabase.from('accounts').select('id,code,name,account_type,normal_balance').eq('business_id',b.business_id).eq('is_active',true).order('code'),supabase.from('journal_entries').select('id,entry_date,description,source_type,status,total_debit,total_credit').eq('business_id',b.business_id).order('entry_date',{ascending:false}).limit(20),supabase.from('journal_lines').select('account_id,debit,credit,journal_entry_id')]);if(a.error||j.error||l.error){setError((a.error||j.error||l.error)?.message||'Unable to load accounts');setLoading(false);return}setAccounts(a.data||[]);setEntries(j.data||[]);const allowed=new Set((a.data||[]).map((x:any)=>x.id));const map:Record<string,number>={};for(const x of (l.data||[]) as Line[]){if(!allowed.has(x.account_id))continue;map[x.account_id]=(map[x.account_id]||0)+Number(x.debit||0)-Number(x.credit||0)}setBalances(map);setLoading(false)})()},[]);
 const groups=useMemo(()=>{const out:{label:string;items:Account[]}[]=[];const labels:any={asset:'Assets',liability:'Liabilities',equity:'Equity',income:'Income',expense:'Expenses'};for(const a of accounts){const label=labels[a.account_type]||'Other';let g=out.find(x=>x.label===label);if(!g){g={label,items:[]};out.push(g)}g.items.push(a)}return out},[accounts]);
 const trial=useMemo(()=>{let d=0,c=0;Object.entries(balances).forEach(([id,b])=>{const a=accounts.find(x=>x.id===id);if(!a)return;const v=Number(b||0);if(v>=0)d+=v;else c+=Math.abs(v)});return{d,c,balanced:Math.abs(d-c)<0.01}},[balances,accounts]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Loading accounting…</div>;
 if(!ctx)return null;
 return <main className="min-h-screen bg-[#f5f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Finance control centre</p><h1 className="mt-1 text-3xl font-semibold">Accounting</h1><p className="mt-1 text-sm text-slate-500">The books behind every business transaction.</p></div><button onClick={()=>location.href='/next-workspace'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Cockpit</button></header>
 {error&&<div className="mb-5 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-xs font-semibold text-slate-400">Active accounts</p><p className="mt-2 text-2xl font-semibold">{accounts.length}</p><p className="mt-1 text-xs text-slate-400">Your chart of accounts</p></Card><Card className="p-5"><p className="text-xs font-semibold text-slate-400">Posted entries</p><p className="mt-2 text-2xl font-semibold">{entries.filter(x=>x.status==='posted').length}</p><p className="mt-1 text-xs text-slate-400">Source transactions recorded</p></Card><Card className="p-5"><p className="text-xs font-semibold text-slate-400">Trial balance</p><p className={`mt-2 text-2xl font-semibold ${trial.balanced?'text-emerald-700':'text-amber-700'}`}>{trial.balanced?'Balanced':'Review'}</p><p className="mt-1 text-xs text-slate-400">Debit {money(trial.d)} · Credit {money(trial.c)}</p></Card></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Chart of accounts</h2><p className="mt-1 text-xs text-slate-400">Accounting complexity stays here, not in everyday billing.</p></div><button onClick={()=>location.href='/next-workspace/tax'} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">Tax & ITR →</button></div><div className="mt-4 space-y-5">{groups.map(g=><div key={g.label}><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{g.label}</p><div className="divide-y divide-slate-100 rounded-2xl border border-slate-100">{g.items.slice(0,8).map(a=><div key={a.id} className="flex items-center gap-3 p-3"><span className="w-14 font-mono text-xs text-slate-400">{a.code}</span><span className="flex-1 text-sm font-medium">{a.name}</span><b className="text-sm">{money(Math.abs(balances[a.id]||0))}</b></div>)}</div></div>)}</div></Card>
 <div className="space-y-5"><Card className="p-5"><h2 className="font-semibold">Year-end readiness</h2><p className="mt-1 text-xs text-slate-400">Close books only after the checks are clean.</p><div className="mt-4 space-y-2">{[['Bank reconciliation','Review unmatched bank transactions'],['Receivables','Review overdue and doubtful balances'],['Payables','Review supplier balances'],['Inventory','Confirm stock valuation'],['Tax profile','Confirm tax regime and filing profile'],['Adjustments','Record year-end tax/accounting adjustments']].map(([a,b])=><div key={a} className="flex gap-3 rounded-2xl bg-slate-50 p-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white text-slate-500">✓</span><div><b className="block text-sm">{a}</b><span className="text-xs text-slate-500">{b}</span></div></div>)}</div><button onClick={()=>location.href='/next-workspace/tax'} className="mt-4 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Open year-end & ITR</button></Card><Card className="p-5"><h2 className="font-semibold">Recent journal activity</h2><div className="mt-3 space-y-2">{entries.slice(0,6).map(e=><div key={e.id} className="rounded-2xl border border-slate-100 p-3"><div className="flex justify-between gap-3"><b className="text-sm">{e.description||e.source_type||'Journal entry'}</b><span className="text-[10px] font-semibold uppercase text-slate-400">{e.status}</span></div><p className="mt-1 text-xs text-slate-500">{e.entry_date} · {money(Number(e.total_debit||0))}</p></div>)}{!entries.length&&<p className="rounded-2xl bg-slate-50 p-4 text-xs text-slate-500">No journal entries yet. They will appear automatically as transactions are posted.</p>}</div></Card></div></div></div></main>
}
