'use client';

import { useEffect, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

export default function InventoryPreferences(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null);const [items,setItems]=useState<any[]>([]);const [id,setId]=useState('');const [enabled,setEnabled]=useState(true);const [type,setType]=useState('percent');const [value,setValue]=useState(0);const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false);
 async function load(){const c=await supabase.rpc('get_my_business_context');const b=(c.data?.[0]||null) as BusinessContext|null;if(!b)return;setCtx(b);const r=await supabase.from('products_services').select('id,name,sku,sales_price,discount_enabled,max_discount_type,max_discount_value').eq('business_id',b.business_id).eq('is_active',true).order('name');setItems(r.data||[])}useEffect(()=>{load()},[]);
 function choose(x:any){setId(x.id);setEnabled(x.discount_enabled!==false);setType(x.max_discount_type||'percent');setValue(x.max_discount_value??0);setMsg('')}
 async function save(){if(!ctx||!id)return;setSaving(true);const r=await supabase.from('products_services').update({discount_enabled:enabled,max_discount_type:type,max_discount_value:value}).eq('id',id).eq('business_id',ctx.business_id);setMsg(r.error?r.error.message:'Product discount rules saved.');setSaving(false);if(!r.error)load()}
 return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-4xl"><header className="mb-6"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Inventory controls</p><h1 className="mt-1 text-3xl font-semibold">Product discount rules</h1><p className="mt-1 text-sm text-slate-500">Decide whether discounts are offered for each product and what default limit the sales team should see.</p></header><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><label className="block"><span className="text-xs font-semibold text-slate-500">Product / service</span><select value={id} onChange={e=>choose(items.find(x=>x.id===e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="">Select product…</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}{x.sku?` · ${x.sku}`:''}</option>)}</select></label>{id&&<div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><h2 className="font-semibold">Discount allowed?</h2><p className="mt-1 text-xs text-slate-400">This is a control/default, not a hidden restriction.</p><div className="mt-5 flex gap-3"><button onClick={()=>setEnabled(true)} className={`flex-1 rounded-xl border px-4 py-3 font-semibold ${enabled?'border-slate-950 bg-slate-950 text-white':'border-slate-200'}`}>Yes</button><button onClick={()=>setEnabled(false)} className={`flex-1 rounded-xl border px-4 py-3 font-semibold ${!enabled?'border-slate-950 bg-slate-950 text-white':'border-slate-200'}`}>No</button></div></div><div className="rounded-2xl border border-slate-200 p-5"><h2 className="font-semibold">Suggested maximum</h2><div className="mt-4 grid grid-cols-2 gap-3"><label><span className="text-xs font-semibold text-slate-500">Type</span><select value={type} onChange={e=>setType(e.target.value)} disabled={!enabled} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 disabled:bg-slate-100"><option value="percent">Percent (%)</option><option value="amount">Amount (₹)</option></select></label><label><span className="text-xs font-semibold text-slate-500">Value</span><input type="number" min="0" step="0.01" value={value} onChange={e=>setValue(Number(e.target.value))} disabled={!enabled} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 disabled:bg-slate-100"/></label></div><p className="mt-2 text-xs text-slate-400">A sales user may request more; the application can require approval rather than silently blocking the sale.</p></div></div>}<div className="mt-6 flex items-center justify-end gap-3"><span className="text-sm text-emerald-700">{msg}</span><button disabled={!id||saving} onClick={save} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save product rule'}</button></div></section></div></main>
}