'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/lib/workspace-context';
import { ErrorState, LoadingState } from '../workspace-ui';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));

type Invoice={total:number;balance_due:number;status:string};
type Bill={total:number;balance_due:number;status:string};

export default function BusinessHealth(){
 const { business, loading: workspaceLoading }=useWorkspace();
 const[invoices,setInvoices]=useState<Invoice[]>([]),[bills,setBills]=useState<Bill[]>([]),[customerCount,setCustomerCount]=useState(0),[productCount,setProductCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!business){setLoading(false);return}let alive=true;(async()=>{const [i,b,c,p]=await Promise.all([supabase.from('invoices').select('total,balance_due,status').eq('business_id',business.business_id),supabase.from('bills').select('total,balance_due,status').eq('business_id',business.business_id),supabase.from('customers').select('id',{count:'exact',head:true}).eq('business_id',business.business_id).eq('is_active',true),supabase.from('products_services').select('id',{count:'exact',head:true}).eq('business_id',business.business_id).eq('is_active',true)]);if(!alive)return;const e=i.error||b.error||c.error||p.error;if(e)setError(e.message);setInvoices(i.data||[]);setBills(b.data||[]);setCustomerCount(c.count||0);setProductCount(p.count||0);setLoading(false)})();return()=>{alive=false}},[business]);
 const health=useMemo(()=>{const receivable=invoices.reduce((a,x)=>a+Number(x.balance_due||0),0);const payable=bills.reduce((a,x)=>a+Number(x.balance_due||0),0);const overdue=invoices.filter(x=>x.status==='overdue').length;const partiallyPaid=invoices.filter(x=>x.status==='partially_paid').length;const paid=invoices.filter(x=>x.status==='paid').length;const score=Math.max(0,Math.min(100,75-(overdue*8)-(payable>receivable&&payable>0?10:0)+(paid>0?8:0)+(customerCount>0?7:0)));return{receivable,payable,overdue,partiallyPaid,paid,score}},[invoices,bills,customerCount]);
 if(workspaceLoading||loading)return <LoadingState label="Calculating business health…"/>;
 if(!business)return <div className="p-6"><ErrorState message="No business workspace is active."/></div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]"><header className="mb-7"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Business intelligence</p><h1 className="mt-1 text-3xl font-semibold">Business Health</h1><p className="mt-2 text-sm text-slate-500">A simple view of the signals that deserve attention—not an accounting report.</p></header>{error&&<div className="mb-5"><ErrorState message={error}/></div>}<section className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="rounded-3xl bg-slate-950 p-6 text-white"><span className="text-xs font-semibold text-slate-300">Health score</span><div className="mt-5 text-6xl font-semibold">{health.score}</div><p className="mt-2 text-sm text-slate-300">out of 100</p><p className="mt-6 text-sm leading-6 text-slate-300">{health.overdue?`${health.overdue} overdue invoice${health.overdue===1?'':'s'} need attention.`:'No overdue invoices detected in the current data.'}</p></div><div className="grid gap-4 sm:grid-cols-2"><Signal title="To collect" value={money(health.receivable)} tone={health.receivable?'amber':'good'} note="Customer money still outstanding"/><Signal title="To pay" value={money(health.payable)} tone={health.payable?'amber':'good'} note="Supplier balance outstanding"/><Signal title="Customers" value={String(customerCount)} tone="neutral" note="Active relationships"/><Signal title="Products" value={String(productCount)} tone="neutral" note="Active catalogue"/></div></section><section className="mt-6 grid gap-4 md:grid-cols-3"><Insight title="Collections" body={health.overdue?`Prioritise ${health.overdue} overdue invoice${health.overdue===1?'':'s'} before adding new credit.`:'Collections are currently clear.'} href="/next-workspace/collections"/><Insight title="Cash position" body={health.payable>health.receivable?'Supplier obligations are higher than current customer balances. Watch cash timing.':'Customer balances currently cover supplier balances at a simple outstanding-balance level.'} href="/next-workspace/banking"/><Insight title="Reporting" body="Use the reports workspace for the accounting view behind these business signals." href="/next-workspace/reports"/></section></div></main>;
}
function Signal({title,value,note,tone}:{title:string;value:string;note:string;tone:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-semibold text-slate-500">{title}</span><b className={`mt-3 block text-2xl ${tone==='amber'?'text-amber-700':tone==='good'?'text-emerald-700':'text-slate-950'}`}>{value}</b><span className="mt-1 block text-xs text-slate-400">{note}</span></section>}
function Insight({title,body,href}:{title:string;body:string;href:string}){return <button onClick={()=>{window.location.href=href}} className="rounded-2xl border border-slate-200 bg-white p-5 text-left hover:border-violet-200 hover:bg-violet-50/30"><b className="text-sm">{title}</b><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p><span className="mt-4 block text-xs font-semibold text-violet-700">Open →</span></button>}
