'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/lib/workspace-context';
import { EmptyState, ErrorState, LoadingState } from '../workspace-ui';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
type Bill={id:string;bill_number:string;bill_date:string;due_date:string;status:string;total:number;amount_paid:number;balance_due:number;vendor_id:string};
type Vendor={id:string;display_name:string};

export default function Purchases(){
 const { business, loading: workspaceLoading, error: workspaceError, refresh } = useWorkspace();
 const[bills,setBills]=useState<Bill[]>([]),[vendors,setVendors]=useState<Vendor[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!business){setLoading(false);return}let alive=true;(async()=>{setLoading(true);setError('');const [bi,ve]=await Promise.all([supabase.from('bills').select('id,bill_number,bill_date,due_date,status,total,amount_paid,balance_due,vendor_id').eq('business_id',business.business_id).order('bill_date',{ascending:false}).limit(100),supabase.from('vendors').select('id,display_name').eq('business_id',business.business_id).eq('is_active',true).order('display_name')]);if(!alive)return;const firstError=bi.error||ve.error;if(firstError)setError(firstError.message);setBills(bi.data||[]);setVendors(ve.data||[]);setLoading(false)})();return()=>{alive=false}},[business]);
 const name=(id:string)=>vendors.find(v=>v.id===id)?.display_name||'Vendor';
 const filtered=useMemo(()=>bills.filter(x=>(status==='all'||x.status===status)&&`${x.bill_number} ${name(x.vendor_id)} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[bills,vendors,q,status]);
 const payable=bills.reduce((a,x)=>a+Number(x.balance_due||0),0);
 if(workspaceLoading||loading)return <LoadingState label="Loading purchases & bills…"/>;
 if(workspaceError&&!business)return <div className="p-6"><ErrorState message={workspaceError} onRetry={()=>void refresh()}/></div>;
 if(!business)return <div className="p-6"><EmptyState title="No business workspace" description="Activate a business workspace before managing purchases." action="Business settings" onAction={()=>{window.location.href='/next-workspace/business-settings'}}/></div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1320px]">
  <header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Money out</p><h1 className="mt-1 text-3xl font-semibold">Purchases & Bills</h1><p className="mt-2 text-sm text-slate-500">Record what you buy, understand what it affects, then pay and reconcile it.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{window.location.href='/next-workspace/purchase-flow'}} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">＋ New purchase</button><button onClick={()=>{window.location.href='/next-workspace/vendors'}} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Vendors</button><button onClick={()=>{window.location.href='/next-workspace/inventory'}} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Products & stock</button></div></header>
  {error&&<div className="mb-5"><ErrorState message={error}/></div>}
  <div className="grid gap-4 sm:grid-cols-3"><K title="Bills" value={String(bills.length)} note="Recorded purchases"/><K title="To pay" value={money(payable)} note="Outstanding supplier balance"/><K title="Overdue" value={String(bills.filter(x=>x.status==='overdue').length)} note="Needs attention" tone="rose"/></div>
  <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><div className="relative flex-1"><span className="absolute left-3 top-2.5 text-slate-400">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search bills or vendors…" className="w-full rounded-xl border border-slate-200 bg-[#fbfaff] py-2.5 pl-9 pr-4 text-sm outline-none"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="draft">Draft</option><option value="posted">Posted</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select></div><div className="hidden grid-cols-[120px_1fr_110px_120px_130px] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>Bill</span><span>Vendor</span><span>Date</span><span>Status</span><span className="text-right">Balance</span></div><div className="divide-y divide-slate-100">{filtered.map(b=><div key={b.id} className="grid gap-2 px-4 py-4 sm:grid-cols-[120px_1fr_110px_120px_130px] sm:items-center sm:gap-3 sm:px-5"><span className="text-sm font-semibold">{b.bill_number}</span><span><b className="block text-sm">{name(b.vendor_id)}</b><span className="text-xs text-slate-400">Due {b.due_date}</span></span><span className="text-xs text-slate-500">{b.bill_date}</span><span><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-semibold text-violet-700">{b.status.replaceAll('_',' ')}</span></span><span className="text-sm font-semibold sm:text-right">{money(b.balance_due)}</span></div>)}{!filtered.length&&<EmptyState title="No purchases yet" description="Create your first purchase to start tracking supplier balances, expenses, inventory and GST." action="Create purchase" onAction={()=>{window.location.href='/next-workspace/purchase-flow'}}/>}</div></section>
 </div></main>;
}
function K({title,value,note,tone}:{title:string;value:string;note:string;tone?:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-semibold text-slate-500">{title}</span><b className={`mt-3 block text-2xl tracking-tight ${tone==='rose'?'text-rose-700':''}`}>{value}</b><span className="mt-1 block text-xs text-slate-400">{note}</span></section>}
