'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
const steps=['Customer','Items','Review','Send','Accept','Invoice'];

export default function Quotation(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[taxes,setTaxes]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]),[template,setTemplate]=useState(''),[step,setStep]=useState(1),[customer,setCustomer]=useState(''),[valid,setValid]=useState(''),[lines,setLines]=useState<any[]>([]),[note,setNote]=useState(''),[terms,setTerms]=useState('Payment due within the agreed credit period.'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[quote,setQuote]=useState<any>(null);
 useEffect(()=>{(async()=>{const r=await supabase.rpc('get_my_business_context');const c=r.data?.[0] as BusinessContext|undefined;if(!c){location.href='/';return}setCtx(c);const[cs,ps,ts,tm,dp]=await Promise.all([
  supabase.from('customers').select('id,display_name').eq('business_id',c.business_id).eq('is_active',true).order('display_name'),
  supabase.from('products_services').select('id,name,sales_price,default_tax_rate_id,discount_enabled,max_discount_type,max_discount_value').eq('business_id',c.business_id).eq('is_active',true).order('name'),
  supabase.from('tax_rates').select('id,name,rate').eq('business_id',c.business_id).eq('is_active',true),
  supabase.from('document_templates').select('id,template_name').eq('document_type','quotation').eq('is_active',true).order('template_name'),
  supabase.from('business_document_preferences').select('template_id').eq('business_id',c.business_id).eq('document_type','quotation').maybeSingle()
 ]);setCustomers(cs.data||[]);setProducts(ps.data||[]);setTaxes(ts.data||[]);setTemplates(tm.data||[]);setTemplate(dp.data?.template_id||tm.data?.[0]?.id||'')})()},[]);
 const add=()=>{const p=products[0];if(p)setLines(x=>[...x,{product_service_id:p.id,description:p.name,quantity:1,unit_price:Number(p.sales_price||0),discount_type:'',discount_value:0,tax_rate_id:p.default_tax_rate_id||''}])};
 const update=(i:number,key:string,value:any)=>setLines(x=>x.map((z,j)=>j===i?{...z,[key]:value}:z));
 const totals=useMemo(()=>{let s=0,d=0,t=0;for(const l of lines){const b=Number(l.quantity||0)*Number(l.unit_price||0);const ld=l.discount_type==='percentage'?b*Number(l.discount_value||0)/100:l.discount_type==='fixed'?Math.min(b,Number(l.discount_value||0)):0;const tr=taxes.find(x=>x.id===l.tax_rate_id)?.rate||0;s+=b;d+=ld;t+=(b-ld)*tr/100}return{subtotal:s,discount:d,tax:t,total:s-d+t}},[lines,taxes]);
 const save=async()=>{if(!ctx||!customer||!lines.length)return;setBusy(true);setMsg('');const r=await supabase.rpc('create_quotation_from_items',{p_business_id:ctx.business_id,p_customer_id:customer,p_quotation_date:new Date().toISOString().slice(0,10),p_valid_until:valid||null,p_items:lines,p_notes:note||null,p_terms:terms||null,p_template_id:template||null});if(r.error)setMsg(r.error.message);else{const q=await supabase.from('quotations').select('*').eq('id',r.data).single();setQuote(q.data);setStep(4);setMsg('Quotation saved as draft.');}setBusy(false)};
 const status=async(s:string)=>{if(!quote)return;setBusy(true);const r=await supabase.from('quotations').update({status:s}).eq('id',quote.id);if(r.error)setMsg(r.error.message);else{setQuote({...quote,status:s});setStep(s==='sent'?5:6);setMsg(`Quotation marked ${s}.`)}setBusy(false)};
 const convert=async()=>{if(!quote)return;setBusy(true);const r=await supabase.rpc('convert_quotation_to_invoice',{p_quotation_id:quote.id,p_invoice_date:new Date().toISOString().slice(0,10)});if(r.error)setMsg(r.error.message);else{setStep(6);setMsg(`Converted to invoice ${r.data}.`)}setBusy(false)};
 if(!ctx)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Loading quotation…</div>;
 return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl">
  <header className="mb-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Sales workflow</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Create quotation</h1><p className="mt-1 text-sm text-slate-500">Prepare it once. Send it. Convert it to an invoice when accepted.</p></div><button onClick={()=>location.href='/next-workspace'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Dashboard</button></div></header>
  <div className="mb-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-3"><div className="flex min-w-max items-center justify-between gap-2">{steps.map((s,i)=><div key={s} className="flex items-center gap-2"><button onClick={()=>i+1<=step&&setStep(i+1)} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold ${i+1===step?'bg-slate-950 text-white':i+1<step?'bg-emerald-50 text-emerald-700':'bg-slate-50 text-slate-400'}`}><span className="grid h-6 w-6 place-items-center rounded-full bg-white/70 text-[10px]">{i+1<step?'✓':i+1}</span>{s}</button>{i<steps.length-1&&<span className="text-slate-300">→</span>}</div>)}</div></div>
  {msg&&<div className="mb-5 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-medium text-white">{msg}</div>}
  {step<=3&&<section className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
   {step===1&&<><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Step 1</p><h2 className="mt-2 text-xl font-semibold">Choose the customer</h2><p className="mt-1 text-sm text-slate-500">Everything else will follow this customer.</p><select value={customer} onChange={e=>setCustomer(e.target.value)} className="mt-6 w-full rounded-xl border border-slate-200 p-3"><option value="">Select customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><div className="mt-6 flex justify-end"><button disabled={!customer} onClick={()=>setStep(2)} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue →</button></div></>}
   {step===2&&<><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Step 2</p><h2 className="mt-2 text-xl font-semibold">Add items</h2></div><button onClick={add} disabled={!products.length} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">＋ Add item</button></div><div className="mt-5 space-y-3">{lines.map((l,i)=>{const p=products.find(x=>x.id===l.product_service_id);return <div key={i} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3 md:grid-cols-[1.5fr_.5fr_.8fr_.8fr_auto]"><select value={l.product_service_id} onChange={e=>{const np=products.find(x=>x.id===e.target.value);if(np)setLines(x=>x.map((z,j)=>j===i?{...z,product_service_id:np.id,description:np.name,unit_price:np.sales_price,tax_rate_id:np.default_tax_rate_id||''}:z))}} className="rounded-xl border p-2.5">{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min="1" value={l.quantity} onChange={e=>update(i,'quantity',Number(e.target.value))} className="rounded-xl border p-2.5"/><input type="number" min="0" value={l.unit_price} onChange={e=>update(i,'unit_price',Number(e.target.value))} className="rounded-xl border p-2.5"/><select value={l.tax_rate_id} onChange={e=>update(i,'tax_rate_id',e.target.value)} className="rounded-xl border p-2.5"><option value="">No tax</option>{taxes.map(t=><option key={t.id} value={t.id}>{t.name} {t.rate}%</option>)}</select><button onClick={()=>setLines(x=>x.filter((_,j)=>j!==i))} className="rounded-xl border border-rose-100 px-3 text-sm font-semibold text-rose-600">Remove</button></div>{p?.discount_enabled&&<div className="mt-3 grid max-w-md grid-cols-[1fr_1fr] gap-2"><select value={l.discount_type} onChange={e=>update(i,'discount_type',e.target.value)} className="rounded-xl border p-2.5 text-xs"><option value="">No discount</option><option value="percentage">Discount %</option><option value="fixed">Discount ₹</option></select><input type="number" min="0" value={l.discount_value} onChange={e=>update(i,'discount_value',Number(e.target.value))} className="rounded-xl border p-2.5 text-xs" placeholder="Value"/></div>}</div>})}</div><div className="mt-6 flex justify-between"><button onClick={()=>setStep(1)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">← Customer</button><button disabled={!lines.length} onClick={()=>setStep(3)} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Review →</button></div></>}
   {step===3&&<><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Step 3</p><h2 className="mt-2 text-xl font-semibold">Review quotation</h2><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm"><div className="flex justify-between"><span>Customer</span><b>{customers.find(c=>c.id===customer)?.display_name}</b></div><div className="mt-2 flex justify-between"><span>Valid until</span><b>{valid||'Not specified'}</b></div><div className="mt-2 flex justify-between"><span>Total</span><b>{money(totals.total)}</b></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input type="date" value={valid} onChange={e=>setValid(e.target.value)} className="rounded-xl border p-3 text-sm"/><select value={template} onChange={e=>setTemplate(e.target.value)} className="rounded-xl border p-3 text-sm">{templates.map(t=><option key={t.id} value={t.id}>{t.template_name}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Notes" className="min-h-24 rounded-xl border p-3 text-sm"/><textarea value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Terms & conditions" className="min-h-24 rounded-xl border p-3 text-sm"/></div><div className="mt-5 flex justify-between"><button onClick={()=>setStep(2)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">← Items</button><button disabled={busy} onClick={save} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">{busy?'Saving…':'Save quotation'}</button></div></>}
  </section><aside className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Live total</p><p className="mt-2 text-3xl font-semibold">{money(totals.total)}</p><div className="mt-5 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(totals.subtotal)}</b></div><div className="flex justify-between"><span>Discount</span><b>{money(totals.discount)}</b></div><div className="flex justify-between"><span>Tax</span><b>{money(totals.tax)}</b></div></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold">Document template</p><p className="mt-1 text-sm">{templates.find(t=>t.id===template)?.template_name||'Default'}</p><p className="mt-1 text-xs text-slate-400">You can change this before saving.</p></div></aside></section>}
  {step>=4&&quote&&<section className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50 text-emerald-700">✓</div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">Quotation {quote.quotation_number}</p><h2 className="mt-2 text-2xl font-semibold">{quote.status==='draft'?'Draft saved':quote.status==='sent'?'Ready for acceptance':quote.status==='accepted'?'Accepted':'Invoice created'}</h2><p className="mt-2 text-sm text-slate-500">The next action is shown below. You don't need to remember the workflow.</p></div><div className="mt-7 grid gap-3">{quote.status==='draft'&&<button disabled={busy} onClick={()=>status('sent')} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Mark as sent →</button>}{quote.status==='sent'&&<button disabled={busy} onClick={()=>status('accepted')} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Mark accepted →</button>}{quote.status==='accepted'&&<button disabled={busy} onClick={convert} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Convert to invoice →</button>}{quote.status!=='draft'&&<button onClick={()=>location.href='/next-workspace/sales'} className="rounded-xl border px-5 py-3 text-sm font-semibold">Open Sales</button>}</div></section>}
 </div></main>
}
