'use client';

import { useEffect, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Address = {line1?:string;line2?:string;city?:string;state?:string;postal_code?:string;country?:string};
type Business = {
  id:string; name:string; legal_name:string|null; business_type:string|null; registration_number:string|null;
  tax_registration_number:string|null; country_code:string; currency_code:string; fiscal_year_start_month:number;
  timezone:string|null; address:Address; phone:string|null; email:string|null; website:string|null;
  tax_settings:Record<string,any>; numbering_settings:Record<string,any>; inventory_enabled:boolean;
  brand_primary_color:string; brand_secondary_color:string; brand_accent_color:string;
};
type Settings = {cash_bill_enabled:boolean};
type TaxProfile = {tax_regime:string;gst_registration_type:string|null;gstin:string|null;pan:string|null;tax_state:string|null;accounting_basis:string;books_mode:string;presumptive_section:string|null};

const input='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100';
const select=input;
const Card=({children,className='' }:{children:React.ReactNode;className?:string})=><section className={`rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_5px_24px_rgba(70,60,120,.045)] ${className}`}>{children}</section>;
const Field=({label,children,help}:{label:string;children:React.ReactNode;help?:string})=><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}{help&&<span className="mt-1 block text-[11px] text-slate-400">{help}</span>}</label>;
const emptyAddress:Address={line1:'',line2:'',city:'',state:'',postal_code:'',country:'India'};

export default function BusinessSettings(){
 const [business,setBusiness]=useState<Business|null>(null),[settings,setSettings]=useState<Settings|null>(null),[tax,setTax]=useState<TaxProfile|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);const c=await supabase.rpc('get_my_business_context');const active=(c.data||[])[0] as BusinessContext|undefined;if(!active){setLoading(false);return}const[b,s,t]=await Promise.all([
   supabase.from('businesses').select('id,name,legal_name,business_type,registration_number,tax_registration_number,country_code,currency_code,fiscal_year_start_month,timezone,address,phone,email,website,tax_settings,numbering_settings,inventory_enabled,brand_primary_color,brand_secondary_color,brand_accent_color').eq('id',active.business_id).single(),
   supabase.from('business_settings').select('cash_bill_enabled').eq('business_id',active.business_id).maybeSingle(),
   supabase.from('business_tax_profiles').select('tax_regime,gst_registration_type,gstin,pan,tax_state,accounting_basis,books_mode,presumptive_section').eq('business_id',active.business_id).maybeSingle()
 ]);if(b.error)setError(b.error.message);setBusiness(b.data?{...(b.data as Business),address:{...emptyAddress,...((b.data as any).address||{})}}:null);setSettings((s.data||{cash_bill_enabled:false}) as Settings);setTax((t.data||{tax_regime:'NONE',gst_registration_type:'NONE',gstin:'',pan:'',tax_state:'Maharashtra',accounting_basis:'ACCRUAL',books_mode:'FULL',presumptive_section:'NONE'}) as TaxProfile);setLoading(false)};
 useEffect(()=>{load()},[]);
 const patch=(k:string,v:any)=>setBusiness(x=>x?({...x,[k]:v}):x); const patchAddress=(k:keyof Address,v:string)=>setBusiness(x=>x?({...x,address:{...(x.address||{}),[k]:v}}):x); const patchS=(k:string,v:any)=>setSettings(x=>x?({...x,[k]:v}):x); const patchT=(k:string,v:any)=>setTax(x=>x?({...x,[k]:v}):x);
 async function save(){if(!business||!settings||!tax)return;setSaving(true);setMessage('');setError('');const taxEnabled=tax.tax_regime!=='NONE'&&!(tax.tax_regime==='GST'&&tax.gst_registration_type==='COMPOSITION');const [b,s,t]=await Promise.all([
   supabase.from('businesses').update({name:business.name,legal_name:business.legal_name,business_type:business.business_type,registration_number:business.registration_number,tax_registration_number:business.tax_registration_number,country_code:business.country_code,currency_code:business.currency_code,fiscal_year_start_month:business.fiscal_year_start_month,timezone:business.timezone,address:business.address,phone:business.phone,email:business.email,website:business.website,inventory_enabled:business.inventory_enabled,brand_primary_color:business.brand_primary_color,brand_secondary_color:business.brand_secondary_color,brand_accent_color:business.brand_accent_color,tax_settings:{...(business.tax_settings||{}),enabled:taxEnabled,mode:tax.tax_regime,region:tax.tax_state||null}}).eq('id',business.id),
   supabase.from('business_settings').upsert({cash_bill_enabled:settings.cash_bill_enabled,business_id:business.id},{onConflict:'business_id'}),
   supabase.from('business_tax_profiles').upsert({...tax,business_id:business.id},{onConflict:'business_id'})
 ]);const e=b.error||s.error||t.error;if(e)setError(e.message);else setMessage('Business settings saved.');setSaving(false)}
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading business settings…</div>;
 if(!business)return <div className="p-8"><Card><h1 className="text-xl font-semibold">Business not found</h1><p className="mt-2 text-sm text-slate-500">Create or select a business workspace first.</p></Card></div>;
 const a=business.address||emptyAddress;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-7"><div className="mx-auto max-w-6xl"><header className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Business setup</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Business settings</h1><p className="mt-2 text-sm text-slate-500">Manage the business identity, contact details, tax profile and counter-billing behavior used across Moneymatters.</p></header>
 {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-5 lg:grid-cols-2">
  <Card className="lg:col-span-2"><h2 className="text-lg font-semibold">Business profile & contact</h2><p className="mt-1 text-xs text-slate-500">These details are customer-facing and are used automatically on invoices, estimates, receipts and other documents.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
   <Field label="Business name"><input className={input} value={business.name||''} onChange={e=>patch('name',e.target.value)}/></Field>
   <Field label="Legal name"><input className={input} value={business.legal_name||''} onChange={e=>patch('legal_name',e.target.value)}/></Field>
   <Field label="Business type"><select className={select} value={business.business_type||'individual'} onChange={e=>patch('business_type',e.target.value)}><option value="individual">Individual</option><option value="sole_proprietorship">Sole proprietorship</option><option value="partnership">Partnership</option><option value="llp">LLP</option><option value="private_limited">Private limited</option><option value="public_limited">Public limited</option><option value="trust">Trust</option><option value="society">Society</option><option value="other">Other</option></select></Field>
   <Field label="Business phone"><input type="tel" className={input} value={business.phone||''} onChange={e=>patch('phone',e.target.value)} placeholder="e.g. +91 98765 43210"/></Field>
   <Field label="Business email"><input type="email" className={input} value={business.email||''} onChange={e=>patch('email',e.target.value)} placeholder="billing@business.com"/></Field>
   <Field label="Website"><input type="url" className={input} value={business.website||''} onChange={e=>patch('website',e.target.value)} placeholder="https://example.com"/></Field>
   <Field label="Registration number"><input className={input} value={business.registration_number||''} onChange={e=>patch('registration_number',e.target.value)}/></Field>
   <Field label="PAN / tax registration"><input className={input} value={business.tax_registration_number||''} onChange={e=>patch('tax_registration_number',e.target.value)}/></Field>
   <Field label="Currency"><select className={select} value={business.currency_code} onChange={e=>patch('currency_code',e.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></Field>
   <Field label="Timezone"><select className={select} value={business.timezone||'Asia/Kolkata'} onChange={e=>patch('timezone',e.target.value)}><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Dubai</option><option>Asia/Singapore</option></select></Field>
   <Field label="Financial year starts"><select className={select} value={business.fiscal_year_start_month} onChange={e=>patch('fiscal_year_start_month',Number(e.target.value))}><option value="1">January</option><option value="4">April</option><option value="7">July</option><option value="10">October</option></select></Field>
  </div><div className="mt-6"><div className="mb-3 text-xs font-semibold text-slate-600">Business address</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Address line 1"><input className={input} value={a.line1||''} onChange={e=>patchAddress('line1',e.target.value)} placeholder="Shop / office / building"/></Field><Field label="Address line 2"><input className={input} value={a.line2||''} onChange={e=>patchAddress('line2',e.target.value)} placeholder="Area / landmark"/></Field><Field label="City"><input className={input} value={a.city||''} onChange={e=>patchAddress('city',e.target.value)} placeholder="City"/></Field><Field label="State"><input className={input} value={a.state||''} onChange={e=>patchAddress('state',e.target.value)} placeholder="State"/></Field><Field label="PIN / Postal code"><input className={input} value={a.postal_code||''} onChange={e=>patchAddress('postal_code',e.target.value)} placeholder="PIN code"/></Field><Field label="Country"><input className={input} value={a.country||''} onChange={e=>patchAddress('country',e.target.value)} placeholder="Country"/></Field></div></div></Card>
  <Card><h2 className="text-lg font-semibold">Tax & books</h2><p className="mt-1 text-xs text-slate-500">Tax registration and accounting basis are business-level configuration. Document tax visibility is controlled in Document Settings.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Tax regime"><select className={select} value={tax?.tax_regime||'NONE'} onChange={e=>patchT('tax_regime',e.target.value)}><option value="NONE">Non-tax / simple books</option><option value="GST">GST</option><option value="VAT">VAT</option><option value="SALES_TAX">Sales tax</option><option value="OTHER">Other</option></select></Field><Field label="GST registration"><select className={select} value={tax?.gst_registration_type||'NONE'} onChange={e=>patchT('gst_registration_type',e.target.value)}><option>NONE</option><option>REGULAR</option><option>COMPOSITION</option><option>CASUAL</option><option>NON_RESIDENT</option><option>SEZ</option></select></Field><Field label="GSTIN"><input className={input} value={tax?.gstin||''} onChange={e=>patchT('gstin',e.target.value)} placeholder="15-character GSTIN"/></Field><Field label="PAN"><input className={input} value={tax?.pan||''} onChange={e=>patchT('pan',e.target.value)} placeholder="ABCDE1234F"/></Field><Field label="Tax state"><input className={input} value={tax?.tax_state||''} onChange={e=>patchT('tax_state',e.target.value)}/></Field><Field label="Accounting basis"><select className={select} value={tax?.accounting_basis||'ACCRUAL'} onChange={e=>patchT('accounting_basis',e.target.value)}><option>ACCRUAL</option><option>CASH</option></select></Field><Field label="Books mode"><select className={select} value={tax?.books_mode||'FULL'} onChange={e=>patchT('books_mode',e.target.value)}><option>FULL</option><option>SIMPLE</option><option>PRESUMPTIVE</option></select></Field><Field label="Presumptive section"><select className={select} value={tax?.presumptive_section||'NONE'} onChange={e=>patchT('presumptive_section',e.target.value)}><option>NONE</option><option>44AD</option><option>44ADA</option><option>44AE</option></select></Field></div></Card>
  <Card><h2 className="text-lg font-semibold">Sales & counter billing</h2><p className="mt-1 text-xs text-slate-500">Optional fast billing for small businesses and counter sales where creating a customer for every cash buyer is unnecessary.</p><div className="mt-5 rounded-2xl border border-violet-100 bg-violet-50/50 p-4"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" checked={Boolean(settings?.cash_bill_enabled)} onChange={e=>patchS('cash_bill_enabled',e.target.checked)} className="mt-1 h-4 w-4 accent-violet-600"/><span><b className="block text-sm">Enable Cash Bill</b><span className="mt-1 block text-xs leading-5 text-slate-500">Adds Cash Bill under Sales in the sidebar. Use it for walk-in/counter sales without maintaining a customer record for every transaction.</span></span></label><div className="mt-4 rounded-xl bg-white p-3 text-xs text-slate-500"><b className="text-slate-700">When disabled:</b> Cash Bill stays hidden and normal Sales & Payments continues to use named customers.</div></div></Card>
  <Card className="lg:col-span-2 border-violet-100 bg-violet-50/40"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-violet-950">Document presentation is managed separately</h2><p className="mt-1 text-xs text-violet-800">Templates, appearance, logo visibility, Pay Now / QR, bank details, numbering, due days and default terms are now kept together in Document Settings.</p></div><a href="/next-workspace/brand" className="shrink-0 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Open Document Settings →</a></div></Card>
 </div><div className="sticky bottom-3 mt-5 flex items-center justify-end gap-3 rounded-2xl border border-violet-100 bg-white/95 p-3 shadow-lg backdrop-blur"><span className="mr-auto text-sm text-emerald-700">{message}</span><button disabled={saving} onClick={save} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-50">{saving?'Saving…':'Save business settings'}</button></div></div></main>;
}
