'use client';

import { useEffect, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Business = {
  id:string; name:string; legal_name:string|null; business_type:string|null; registration_number:string|null;
  tax_registration_number:string|null; country_code:string; currency_code:string; fiscal_year_start_month:number;
  timezone:string|null; address:Record<string,any>; tax_settings:Record<string,any>; numbering_settings:Record<string,any>;
  inventory_enabled:boolean; brand_primary_color:string; brand_secondary_color:string; brand_accent_color:string;
};
type Settings = {invoice_prefix:string; bill_prefix:string; estimate_prefix:string; receipt_prefix:string; invoice_due_days:number; invoice_notes:string|null; default_payment_terms:string|null};
type TaxProfile = {tax_regime:string;gst_registration_type:string|null;gstin:string|null;pan:string|null;tax_state:string|null;accounting_basis:string;books_mode:string;presumptive_section:string|null};
const input='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100';
const select=input;
const Card=({children,className='' }:{children:React.ReactNode;className?:string})=><section className={`rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_5px_24px_rgba(70,60,120,.045)] ${className}`}>{children}</section>;
const Field=({label,children,help}:{label:string;children:React.ReactNode;help?:string})=><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}{help&&<span className="mt-1 block text-[11px] text-slate-400">{help}</span>}</label>;

export default function BusinessSettings(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[business,setBusiness]=useState<Business|null>(null),[settings,setSettings]=useState<Settings|null>(null),[tax,setTax]=useState<TaxProfile|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);const c=await supabase.rpc('get_my_business_context');const active=(c.data||[])[0] as BusinessContext|undefined;if(!active){setLoading(false);return}setCtx(active);const[b,s,t]=await Promise.all([supabase.from('businesses').select('id,name,legal_name,business_type,registration_number,tax_registration_number,country_code,currency_code,fiscal_year_start_month,timezone,address,tax_settings,numbering_settings,inventory_enabled,brand_primary_color,brand_secondary_color,brand_accent_color').eq('id',active.business_id).single(),supabase.from('business_settings').select('invoice_prefix,bill_prefix,estimate_prefix,receipt_prefix,invoice_due_days,invoice_notes,default_payment_terms').eq('business_id',active.business_id).maybeSingle(),supabase.from('business_tax_profiles').select('tax_regime,gst_registration_type,gstin,pan,tax_state,accounting_basis,books_mode,presumptive_section').eq('business_id',active.business_id).maybeSingle()]);if(b.error)setError(b.error.message);setBusiness(b.data as Business);setSettings((s.data||{invoice_prefix:'INV-',bill_prefix:'BILL-',estimate_prefix:'EST-',receipt_prefix:'RCT-',invoice_due_days:0,invoice_notes:'',default_payment_terms:''}) as Settings);setTax((t.data||{tax_regime:'NONE',gst_registration_type:'NONE',gstin:'',pan:'',tax_state:'Maharashtra',accounting_basis:'ACCRUAL',books_mode:'FULL',presumptive_section:'NONE'}) as TaxProfile);setLoading(false)};
 useEffect(()=>{load()},[]);
 const patch=(k:string,v:any)=>setBusiness(x=>x?({...x,[k]:v}):x); const patchS=(k:string,v:any)=>setSettings(x=>x?({...x,[k]:v}):x); const patchT=(k:string,v:any)=>setTax(x=>x?({...x,[k]:v}):x);
 async function save(){if(!business||!settings||!tax)return;setSaving(true);setMessage('');setError('');const [b,s,t]=await Promise.all([supabase.from('businesses').update({name:business.name,legal_name:business.legal_name,business_type:business.business_type,registration_number:business.registration_number,tax_registration_number:business.tax_registration_number,country_code:business.country_code,currency_code:business.currency_code,fiscal_year_start_month:business.fiscal_year_start_month,timezone:business.timezone,address:business.address,inventory_enabled:business.inventory_enabled,brand_primary_color:business.brand_primary_color,brand_secondary_color:business.brand_secondary_color,brand_accent_color:business.brand_accent_color}).eq('id',business.id),supabase.from('business_settings').upsert({...settings,business_id:business.id},{onConflict:'business_id'}),supabase.from('business_tax_profiles').upsert({...tax,business_id:business.id},{onConflict:'business_id'})]);const e=b.error||s.error||t.error;if(e)setError(e.message);else setMessage('Business settings saved.');setSaving(false)}
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading business settings…</div>;
 if(!business)return <div className="p-8"><Card><h1 className="text-xl font-semibold">Business not found</h1><p className="mt-2 text-sm text-slate-500">Create or select a business workspace first.</p></Card></div>;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-7"><div className="mx-auto max-w-6xl"><header className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Business setup</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Business settings</h1><p className="mt-2 text-sm text-slate-500">One place for your legal identity, tax profile, numbering and accounting defaults.</p></header>
 {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-5 lg:grid-cols-2">
  <Card><h2 className="text-lg font-semibold">Business profile</h2><p className="mt-1 text-xs text-slate-500">Shown on invoices, estimates, receipts and customer-facing documents.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Business name"><input className={input} value={business.name||''} onChange={e=>patch('name',e.target.value)}/></Field><Field label="Legal name"><input className={input} value={business.legal_name||''} onChange={e=>patch('legal_name',e.target.value)}/></Field><Field label="Business type"><select className={select} value={business.business_type||'individual'} onChange={e=>patch('business_type',e.target.value)}><option value="individual">Individual</option><option value="sole_proprietorship">Sole proprietorship</option><option value="partnership">Partnership</option><option value="llp">LLP</option><option value="private_limited">Private limited</option><option value="public_limited">Public limited</option><option value="trust">Trust</option><option value="society">Society</option><option value="other">Other</option></select></Field><Field label="Registration number"><input className={input} value={business.registration_number||''} onChange={e=>patch('registration_number',e.target.value)}/></Field><Field label="PAN / tax registration"><input className={input} value={business.tax_registration_number||''} onChange={e=>patch('tax_registration_number',e.target.value)}/></Field><Field label="Currency"><select className={select} value={business.currency_code} onChange={e=>patch('currency_code',e.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></Field><Field label="Timezone"><select className={select} value={business.timezone||'Asia/Kolkata'} onChange={e=>patch('timezone',e.target.value)}><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Dubai</option><option>Asia/Singapore</option></select></Field><Field label="Financial year starts"><select className={select} value={business.fiscal_year_start_month} onChange={e=>patch('fiscal_year_start_month',Number(e.target.value))}><option value="1">January</option><option value="4">April</option><option value="7">July</option><option value="10">October</option></select></Field></div></Card>
  <Card><h2 className="text-lg font-semibold">Tax & books</h2><p className="mt-1 text-xs text-slate-500">Tax is configuration; the accounting engine remains double-entry underneath.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Tax regime"><select className={select} value={tax?.tax_regime||'NONE'} onChange={e=>patchT('tax_regime',e.target.value)}><option value="NONE">Non-tax / simple books</option><option value="GST">GST</option><option value="VAT">VAT</option><option value="SALES_TAX">Sales tax</option><option value="OTHER">Other</option></select></Field><Field label="GST registration"><select className={select} value={tax?.gst_registration_type||'NONE'} onChange={e=>patchT('gst_registration_type',e.target.value)}><option>NONE</option><option>REGULAR</option><option>COMPOSITION</option><option>CASUAL</option><option>NON_RESIDENT</option><option>SEZ</option></select></Field><Field label="GSTIN"><input className={input} value={tax?.gstin||''} onChange={e=>patchT('gstin',e.target.value)} placeholder="15-character GSTIN"/></Field><Field label="PAN"><input className={input} value={tax?.pan||''} onChange={e=>patchT('pan',e.target.value)} placeholder="ABCDE1234F"/></Field><Field label="Tax state"><input className={input} value={tax?.tax_state||''} onChange={e=>patchT('tax_state',e.target.value)}/></Field><Field label="Accounting basis"><select className={select} value={tax?.accounting_basis||'ACCRUAL'} onChange={e=>patchT('accounting_basis',e.target.value)}><option>ACCRUAL</option><option>CASH</option></select></Field><Field label="Books mode"><select className={select} value={tax?.books_mode||'FULL'} onChange={e=>patchT('books_mode',e.target.value)}><option>FULL</option><option>SIMPLE</option><option>PRESUMPTIVE</option></select></Field><Field label="Presumptive section"><select className={select} value={tax?.presumptive_section||'NONE'} onChange={e=>patchT('presumptive_section',e.target.value)}><option>NONE</option><option>44AD</option><option>44ADA</option><option>44AE</option></select></Field></div></Card>
  <Card><h2 className="text-lg font-semibold">Document numbering & defaults</h2><p className="mt-1 text-xs text-slate-500">Control how new business documents are numbered and what payment terms they use.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Invoice prefix"><input className={input} value={settings?.invoice_prefix||''} onChange={e=>patchS('invoice_prefix',e.target.value)}/></Field><Field label="Estimate prefix"><input className={input} value={settings?.estimate_prefix||''} onChange={e=>patchS('estimate_prefix',e.target.value)}/></Field><Field label="Bill prefix"><input className={input} value={settings?.bill_prefix||''} onChange={e=>patchS('bill_prefix',e.target.value)}/></Field><Field label="Receipt prefix"><input className={input} value={settings?.receipt_prefix||''} onChange={e=>patchS('receipt_prefix',e.target.value)}/></Field><Field label="Invoice due days"><input type="number" min="0" className={input} value={settings?.invoice_due_days??0} onChange={e=>patchS('invoice_due_days',Number(e.target.value))}/></Field><Field label="Default payment terms"><input className={input} value={settings?.default_payment_terms||''} onChange={e=>patchS('default_payment_terms',e.target.value)} placeholder="Due on receipt / Net 7 / Net 30"/></Field><div className="sm:col-span-2"><Field label="Default invoice note"><textarea className={`${input} min-h-24`} value={settings?.invoice_notes||''} onChange={e=>patchS('invoice_notes',e.target.value)} placeholder="Thank you for your business."/></Field></div></div></Card>
  <Card><h2 className="text-lg font-semibold">Next steps</h2><p className="mt-1 text-xs text-slate-500">Finish the operational parts without hunting through settings.</p><div className="mt-5 grid gap-2"><a className="rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:bg-violet-50" href="/next-workspace/brand">Brand & logo <span className="float-right text-violet-700">→</span></a><a className="rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:bg-violet-50" href="/next-workspace/preferences">Automation & discount preferences <span className="float-right text-violet-700">→</span></a><a className="rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:bg-violet-50" href="/next-workspace/documents">Document templates <span className="float-right text-violet-700">→</span></a><a className="rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:bg-violet-50" href="/next-workspace/whatsapp">WhatsApp / WAPI <span className="float-right text-violet-700">→</span></a></div></Card>
 </div><div className="sticky bottom-3 mt-5 flex items-center justify-end gap-3 rounded-2xl border border-violet-100 bg-white/95 p-3 shadow-lg backdrop-blur"><span className="mr-auto text-sm text-emerald-700">{message}</span><button disabled={saving} onClick={save} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-50">{saving?'Saving…':'Save business settings'}</button></div></div></main>;
}