'use client';

import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';

const nav=[
 ['Overview','/next-workspace','⌂'],
 ['Sales','/next-workspace/sales','↗'],
 ['Quotations','/next-workspace/quotation','▤'],
 ['Customers','/next-workspace/customers','♙'],
 ['Inventory','/next-workspace/inventory','▦'],
 ['Accounting','/next-workspace/accounting','∑'],
 ['Tax & ITR','/next-workspace/tax','%'],
 ['Reports','/next-workspace/reports','▥'],
 ['Branding','/next-workspace/brand','✦'],
 ['Preferences','/next-workspace/preferences','⚙'],
];
const flows:Record<string,{title:string;steps:string[];help:string;next:string}>={
 '/next-workspace/sales':{title:'Sales',steps:['Customer','Items','Review','Post','Payment','Receipt'],help:'Start with the customer, add items, review the total, post the invoice, then collect payment. Accounting happens automatically after posting.',next:'Create an invoice'},
 '/next-workspace/quotation':{title:'Quotations',steps:['Customer','Items','Review','Send','Accept','Invoice'],help:'Create a quote once, send it, and convert an accepted quote into an invoice without re-entering the items.',next:'Create a quotation'},
 '/next-workspace/customers':{title:'Customers',steps:['Find','Profile','Transactions','Statement','Payment'],help:'Customer 360 keeps contact details, quotations, invoices, payments, statements and communication together.',next:'Add a customer'},
 '/next-workspace/inventory':{title:'Products & Services',steps:['Item','Pricing','Tax','Discount','Stock','Save'],help:'Create products or services once. Prices, tax, discount rules and stock settings flow into sales.',next:'Add a product or service'},
 '/next-workspace/accounting':{title:'Accounting',steps:['Transactions','Journal','Ledger','Trial Balance','Reports','Year End'],help:'Business transactions post into double-entry accounting. Use this area for review, reconciliation and closing controls.',next:'Review accounting'},
 '/next-workspace/tax':{title:'Tax & ITR',steps:['Tax Profile','Books','Adjustments','Summary','ITR Working','Export'],help:'Tax is a configuration layer. GST and other tax fields appear only when they apply to the business.',next:'Set tax profile'},
 '/next-workspace/reports':{title:'Reports',steps:['Choose','Period','Review','Drill Down','Export'],help:'Every important report can be reviewed first and then traced back to the underlying transactions.',next:'Open reports'},
 '/next-workspace/brand':{title:'Brand & Documents',steps:['Business','Logo','Invoice','Quotation','Receipt'],help:'Control business branding and choose document templates without changing accounting behaviour.',next:'Set document branding'},
 '/next-workspace/preferences':{title:'Preferences',steps:['Business','Tax','Reminders','Discounts','Documents'],help:'Business defaults reduce repetitive entry. Customer and transaction settings can still override them when needed.',next:'Set preferences'},
};

export default function WorkspaceLayout({children}:{children:React.ReactNode}){
 const pathname=usePathname();
 const[open,setOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[helpOpen,setHelpOpen]=useState(false),[welcome,setWelcome]=useState(false);
 const flow=flows[pathname];
 const active=nav.findIndex(([,href])=>href===pathname);
 useEffect(()=>{try{setCollapsed(localStorage.getItem('mm_sidebar_collapsed')==='1');setWelcome(localStorage.getItem('mm_onboarding_seen')!=='1')}catch{}},[]);
 useEffect(()=>{setOpen(false);setHelpOpen(false)},[pathname]);
 const go=(href:string)=>{setOpen(false);window.location.href=href};
 const finishWelcome=()=>{try{localStorage.setItem('mm_onboarding_seen','1')}catch{}setWelcome(false)};
 if(pathname==='/next-workspace')return <>{children}{welcome&&<Welcome onClose={finishWelcome} onGo={(href)=>{finishWelcome();go(href)}}/>}</>;
 return <div className="min-h-screen bg-[#fbfaff] text-slate-950">
  <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center gap-3 px-3 sm:px-5"><button onClick={()=>setOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white lg:hidden">☰</button><button onClick={()=>{const n=!collapsed;setCollapsed(n);try{localStorage.setItem('mm_sidebar_collapsed',n?'1':'0')}catch{}}} className="hidden h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white lg:grid">☰</button><button onClick={()=>go('/next-workspace')} className="flex items-center gap-2.5 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-600 text-sm font-black text-white">M</span><span className="hidden sm:block"><b className="block text-sm">Moneymatters</b><small className="text-[10px] text-slate-500">Business workspace</small></span></button>{flow&&<div className="hidden border-l border-slate-200 pl-4 md:block"><span className="text-sm font-semibold">{flow.title}</span></div>}<div className="ml-auto flex items-center gap-2"><button onClick={()=>go('/next-workspace')} className="hidden rounded-xl px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-violet-50 md:block">Dashboard</button><button onClick={()=>setHelpOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-sm font-bold hover:bg-violet-50">?</button><button onClick={()=>go('/next-workspace/preferences')} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-sm hover:bg-violet-50">⚙</button></div></div></header>
  <div className="mx-auto grid max-w-[1500px]" style={{gridTemplateColumns:`minmax(0,${collapsed?'76px':'230px'}) minmax(0,1fr)`}}>
   <aside className="hidden min-h-[calc(100vh-64px)] border-r border-slate-200 bg-white p-3 lg:block"><p className={`px-3 pb-2 pt-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400 ${collapsed?'text-center':''}`}>{collapsed?'MM':'Workspace'}</p>{nav.map(([label,href,icon],i)=><button title={collapsed?label:undefined} key={href} onClick={()=>go(href)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium ${collapsed?'justify-center px-2':''} ${active===i?'bg-violet-50 text-violet-800':'text-slate-600 hover:bg-violet-50 hover:text-violet-800'}`}><span className="grid w-5 shrink-0 place-items-center">{icon}</span>{!collapsed&&<span className="truncate">{label}</span>}</button>)}</aside>
   {open&&<button aria-label="Close navigation" onClick={()=>setOpen(false)} className="fixed inset-0 z-[60] bg-violet-950/20 backdrop-blur-sm lg:hidden"/>}
   <aside className={`fixed inset-y-0 left-0 z-[70] w-[290px] transform border-r border-slate-200 bg-white p-4 shadow-2xl transition-transform lg:hidden ${open?'translate-x-0':'-translate-x-full'}`}><div className="mb-5 flex items-center justify-between"><div><b className="text-sm">Moneymatters</b><p className="text-[10px] text-slate-500">Business workspace</p></div><button onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-700">×</button></div>{nav.map(([label,href,icon],i)=><button key={href} onClick={()=>go(href)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium ${active===i?'bg-violet-50 text-violet-800':'text-slate-600 hover:bg-violet-50'}`}><span className="grid w-5 place-items-center">{icon}</span>{label}</button>)}</aside>
   <main className="min-w-0">{flow&&<FlowBar steps={flow.steps}/>} {children}</main>
  </div>
  {flow&&<button onClick={()=>setHelpOpen(true)} className="fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full bg-violet-600 px-4 py-3 text-sm font-semibold text-white shadow-lg"><span className="grid h-6 w-6 place-items-center rounded-full bg-white/15">?</span><span className="hidden sm:inline">Help</span></button>}
  {helpOpen&&<HelpModal title={flow?.title||'Moneymatters'} text={flow?.help||'Use the dashboard to start work. Moneymatters keeps the accounting behind the workflow.'} next={flow?.next} onClose={()=>setHelpOpen(false)}/>} {welcome&&<Welcome onClose={finishWelcome} onGo={(href)=>{finishWelcome();go(href)}}/>}
 </div>;
}
function FlowBar({steps}:{steps:string[]}){return <div className="border-b border-slate-200 bg-white px-3 py-2.5 sm:px-5"><div className="mx-auto flex max-w-[1180px] items-center gap-2 overflow-x-auto"><span className="mr-1 text-[10px] font-bold uppercase tracking-[.16em] text-violet-500">Flow</span>{steps.map((s,i)=><div key={s} className="flex shrink-0 items-center gap-1.5"><span className="grid h-7 w-7 place-items-center rounded-full bg-violet-50 text-[10px] font-bold text-violet-700">{i+1}</span><span className="whitespace-nowrap text-xs font-semibold text-slate-600">{s}</span>{i<steps.length-1&&<span className="mx-1 text-slate-300">→</span>}</div>)}</div></div>}
function HelpModal({title,text,next,onClose}:{title:string;text:string;next?:string;onClose:()=>void}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-violet-950/20 p-4 backdrop-blur-sm" onMouseDown={onClose}><section onMouseDown={e=>e.stopPropagation()} className="w-full max-w-md rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-500">Quick help</p><h2 className="mt-1 text-xl font-semibold">{title}</h2></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-700">×</button></div></div><div className="p-5"><p className="text-sm leading-6 text-slate-600">{text}</p>{next&&<div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-violet-500">Suggested next step</p><p className="mt-1 text-sm font-semibold text-violet-900">{next}</p></div>}<button onClick={onClose} className="mt-5 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white">Got it</button></div></section></div>}
function Welcome({onClose,onGo}:{onClose:()=>void;onGo:(href:string)=>void}){return <div className="fixed inset-0 z-[110] grid place-items-center bg-violet-950/20 p-4 backdrop-blur-sm"><section className="w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="bg-violet-600 p-7 text-white"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white text-lg font-black text-violet-700">M</span><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-white/70">Welcome to Moneymatters</p><h1 className="mt-2 text-2xl font-semibold">Run the business. We handle the books.</h1><p className="mt-2 text-sm leading-6 text-white/80">Start with a customer, quote or invoice. Accounting stays connected in the background.</p></div><div className="grid gap-3 p-5 sm:grid-cols-3"><button onClick={()=>onGo('/next-workspace/sales')} className="rounded-xl border border-slate-200 p-4 text-left hover:bg-violet-50"><b className="text-sm">Sell</b><span className="mt-1 block text-xs leading-5 text-slate-500">Create an invoice.</span></button><button onClick={()=>onGo('/next-workspace/customers')} className="rounded-xl border border-slate-200 p-4 text-left hover:bg-violet-50"><b className="text-sm">Customers</b><span className="mt-1 block text-xs leading-5 text-slate-500">Add your customers.</span></button><button onClick={()=>onGo('/next-workspace/quotation')} className="rounded-xl border border-slate-200 p-4 text-left hover:bg-violet-50"><b className="text-sm">Quote</b><span className="mt-1 block text-xs leading-5 text-slate-500">Send an estimate.</span></button><button onClick={onClose} className="sm:col-span-3 rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white">Start with the dashboard</button></div></section></div>}
