'use client';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';

const groups=[{name:'Business',items:[['Home','/next-workspace'],['Sales & Payments','/next-workspace/sales'],['Estimates','/next-workspace/quotation'],['Customers','/next-workspace/customers'],['Vendors','/next-workspace/vendors'],['Products & Services','/next-workspace/inventory'],['Purchases & Bills','/next-workspace/purchases'],['Recurring','/next-workspace/recurring']]},{name:'Money & Accounting',items:[['Banking','/next-workspace/banking'],['Payments','/next-workspace/payments'],['Receipts','/next-workspace/receipts'],['Accounting','/next-workspace/accounting'],['Tax & ITR','/next-workspace/tax'],['Reports','/next-workspace/reports']]},{name:'Setup & Automation',items:[['Business Settings','/next-workspace/business-settings'],['Brand & Templates','/next-workspace/brand'],['Documents','/next-workspace/documents'],['WhatsApp','/next-workspace/whatsapp'],['Preferences','/next-workspace/preferences'],['Data & Migration','/next-workspace/data-migration'],['My Profile','/next-workspace/profile']]}];
const createItems=[['Invoice','/next-workspace/sales'],['Estimate','/next-workspace/quotation'],['Payment','/next-workspace/payments'],['Expense','/next-workspace/purchases'],['Customer','/next-workspace/customers'],['Vendor','/next-workspace/vendors'],['Product / Service','/next-workspace/inventory'],['New Business','/next-workspace/create-business']];
const titles:Record<string,string>={'/next-workspace':'Home','/next-workspace/sales':'Sales & Payments','/next-workspace/quotation':'Estimates','/next-workspace/customers':'Customers','/next-workspace/vendors':'Vendors','/next-workspace/inventory':'Products & Services','/next-workspace/purchases':'Purchases & Bills','/next-workspace/recurring':'Recurring','/next-workspace/banking':'Banking','/next-workspace/payments':'Payments','/next-workspace/receipts':'Receipts','/next-workspace/accounting':'Accounting','/next-workspace/tax':'Tax & ITR','/next-workspace/reports':'Reports','/next-workspace/business-settings':'Business Settings','/next-workspace/brand':'Brand & Templates','/next-workspace/documents':'Documents','/next-workspace/whatsapp':'WhatsApp','/next-workspace/preferences':'Preferences','/next-workspace/data-migration':'Data & Migration','/next-workspace/profile':'My Profile','/next-workspace/create-business':'New Business'};

export default function WorkspaceLayout({children}:{children:React.ReactNode}){
 const pathname=usePathname();
 const[mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),[create,setCreate]=useState(false),[account,setAccount]=useState(false),[userName,setUserName]=useState('Account');
 const[openGroups,setOpenGroups]=useState<Record<string,boolean>>({'Business':true,'Money & Accounting':true,'Setup & Automation':true});
 const go=(href:string)=>{setMobile(false);setCreate(false);setAccount(false);window.location.href=href};
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUserName(data.user?.user_metadata?.display_name||data.user?.email?.split('@')[0]||'Account'))},[]);
 useEffect(()=>{for(const g of groups){if(g.items.some(([,href])=>href===pathname))setOpenGroups(v=>({...v,[g.name]:true}))}},[pathname]);
 return <div className="min-h-screen bg-[#fbfaff] text-[#24213a]">
  <header className="sticky top-0 z-50 h-16 border-b border-violet-100 bg-white/95 backdrop-blur">
   <div className="mx-auto flex h-full max-w-[1520px] items-center gap-3 px-3 sm:px-5 lg:px-6">
    <button onClick={()=>setCollapsed(v=>!v)} className="hidden h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-violet-50 lg:grid" title={collapsed?'Expand sidebar':'Collapse sidebar'}>{collapsed?'☰':'‹'}</button>
    <button onClick={()=>setMobile(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 lg:hidden" title="Open menu">☰</button>
    <button onClick={()=>go('/next-workspace')} className="flex items-center gap-2.5 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-600 text-sm font-black text-white">M</span><span className="hidden sm:block"><b className="block text-sm tracking-tight">Moneymatters</b><small className="text-[10px] text-slate-500">Business workspace</small></span></button>
    <div className="hidden min-w-0 flex-1 md:block"><div className="mx-auto max-w-xl"><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-[#fbfaff] px-3 py-2"><span className="text-slate-400">⌕</span><input placeholder="Search customers, invoices, products…" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></div></div></div>
    <div className="relative ml-auto"><button onClick={()=>setCreate(v=>!v)} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-700">＋ Create</button>{create&&<div className="absolute right-0 mt-2 w-72 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl">{createItems.map(([label,href])=><button key={href} onClick={()=>go(href)} className="flex w-full items-center rounded-xl px-3 py-2.5 text-left text-sm font-medium hover:bg-violet-50"><span className="mr-3 grid h-8 w-8 place-items-center rounded-lg bg-violet-50 text-violet-700">＋</span>{label}</button>)}</div>}</div>
    <div className="relative"><button onClick={()=>setAccount(v=>!v)} className="flex items-center gap-2 rounded-xl border border-transparent px-2 py-1.5 hover:border-violet-100 hover:bg-violet-50" title="Account"><span className="hidden text-right sm:block"><b className="block max-w-[110px] truncate text-xs font-semibold">{userName}</b><small className="block text-[10px] text-slate-400">Account</small></span><span className="grid h-9 w-9 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">{userName.slice(0,2).toUpperCase()}</span><span className="text-xs text-slate-400">⌄</span></button>{account&&<div className="absolute right-0 mt-2 w-64 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><div className="border-b border-slate-100 px-3 py-3"><b className="block text-sm">{userName}</b><span className="text-xs text-slate-400">Manage your account and businesses</span></div><button onClick={()=>go('/next-workspace/profile')} className="mt-1 flex w-full items-center rounded-xl px-3 py-2.5 text-left text-sm hover:bg-violet-50">My Profile</button><button onClick={()=>go('/next-workspace/business-settings')} className="flex w-full items-center rounded-xl px-3 py-2.5 text-left text-sm hover:bg-violet-50">Business Settings</button><button onClick={()=>go('/next-workspace/create-business')} className="flex w-full items-center rounded-xl px-3 py-2.5 text-left text-sm hover:bg-violet-50">＋ Create another business</button><button onClick={async()=>{await supabase.auth.signOut();window.location.href='/';}} className="mt-1 w-full rounded-xl px-3 py-2.5 text-left text-sm text-rose-600 hover:bg-rose-50">Sign out</button></div>}</div>
   </div>
  </header>
  <div className="mx-auto grid max-w-[1520px] lg:grid-cols-[auto_minmax(0,1fr)]">
   <aside className={`hidden min-h-[calc(100vh-64px)] border-r border-violet-100 bg-white px-3 py-5 transition-[width] duration-300 ease-in-out lg:block ${collapsed?'w-[76px]':'w-[240px]'}`}><Nav pathname={pathname} go={go} collapsed={collapsed} openGroups={openGroups} setOpenGroups={setOpenGroups}/></aside>
   {mobile&&<><button aria-label="Close menu" onClick={()=>setMobile(false)} className="fixed inset-0 z-[60] bg-violet-950/20 lg:hidden"/><aside className="fixed inset-y-0 left-0 z-[70] w-[300px] overflow-y-auto border-r border-violet-100 bg-white px-4 py-5 shadow-2xl animate-[slideIn_.2s_ease-out] lg:hidden"><div className="mb-5 flex items-center justify-between"><b>Moneymatters</b><button onClick={()=>setMobile(false)} className="grid h-9 w-9 place-items-center rounded-lg bg-violet-50 text-violet-700">×</button></div><Nav pathname={pathname} go={go} collapsed={false} openGroups={openGroups} setOpenGroups={setOpenGroups}/></aside></>}
   <main className="min-w-0"><div className="border-b border-violet-100 bg-white px-4 py-3 sm:px-6"><div className="mx-auto flex max-w-[1250px] items-center gap-2"><span className="text-xs font-semibold text-slate-400">Moneymatters</span><span className="text-slate-300">/</span><span className="text-sm font-semibold">{titles[pathname]||'Workspace'}</span></div></div>{children}</main>
  </div>
  <style jsx global>{`@keyframes slideIn{from{transform:translateX(-100%);opacity:.7}to{transform:translateX(0);opacity:1}}`}</style>
 </div>
}

function Nav({pathname,go,collapsed,openGroups,setOpenGroups}:{pathname:string;go:(href:string)=>void;collapsed:boolean;openGroups:Record<string,boolean>;setOpenGroups:React.Dispatch<React.SetStateAction<Record<string,boolean>>>}){
 return <nav>{groups.map(g=><section key={g.name} className="mb-3">
  <button onClick={()=>!collapsed&&setOpenGroups(v=>({...v,[g.name]:!v[g.name]}))} title={collapsed?g.name:undefined} className={`flex w-full items-center rounded-xl px-3 py-2 text-left text-[10px] font-bold uppercase tracking-[.16em] text-slate-400 hover:bg-violet-50 ${collapsed?'justify-center':''}`}><span className="mr-2">{openGroups[g.name]&&!collapsed?'⌄':'›'}</span>{!collapsed&&g.name}</button>
  <div className={`overflow-hidden transition-all duration-200 ${collapsed?'max-h-0 opacity-0':openGroups[g.name]?'max-h-[600px] opacity-100':'max-h-0 opacity-0'}`}>
   <div className="pt-1">{g.items.map(([label,href])=><button key={href} onClick={()=>go(href)} title={collapsed?label:undefined} className={`mb-1 flex w-full items-center rounded-xl px-3 py-2.5 text-left text-sm font-medium transition ${pathname===href?'bg-violet-50 text-violet-800 ring-1 ring-violet-100':'text-slate-600 hover:bg-violet-50 hover:text-violet-800'}`}><span className="mr-3 h-1.5 w-1.5 shrink-0 rounded-full bg-current opacity-50"/>{!collapsed&&label}</button>)}</div>
  </div>
 </section>)}</nav>
}
