'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Customer = { id:string; display_name:string; phone:string|null; email:string|null };
type Invoice = { id:string; invoice_number:string; invoice_date:string; status:string; total:number; balance_due:number; customer_id:string };
type Product = { id:string; name:string; sku:string|null; sales_price:number; inventory_tracked:boolean };

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const date=(v:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short'}).format(new Date(v));
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border border-slate-200/80 bg-white shadow-[0_12px_40px_rgba(15,23,42,.045)] ${className}`}>{children}</section>}
function Pill({children,tone='slate'}:{children:React.ReactNode;tone?:'green'|'amber'|'blue'|'slate'}){const c={green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',blue:'bg-blue-50 text-blue-700',slate:'bg-slate-100 text-slate-600'};return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${c[tone]}`}>{children}</span>}

export default function NextWorkspace(){
 const [session,setSession]=useState<any>(null),[ctx,setCtx]=useState<BusinessContext|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){const r=await supabase.rpc('get_my_business_context');setCtx(r.data?.[0]||null)}setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s){const r=await supabase.rpc('get_my_business_context');setCtx(r.data?.[0]||null)}else setCtx(null)});return()=>subscription.unsubscribe()},[]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#f5f7fb] text-sm text-slate-500">Loading Moneymatters…</div>;
 if(!session)return <Gate title="Sign in required" text="Sign in to Moneymatters first, then open the new workspace." action="Open Moneymatters" onClick={()=>location.href='/'}/>;
 if(!ctx)return <Gate title="Finish business setup" text="Your account is authenticated, but no active business workspace is available yet." action="Open setup" onClick={()=>location.href='/'}/>;
 return <Workspace ctx={ctx} />;
}
function Gate({title,text,action,onClick}:{title:string;text:string;action:string;onClick:()=>void}){return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top_left,#dbeafe,transparent_30%),#f8fafc] p-6"><Card className="max-w-lg p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-950 font-black text-white">M</div><h1 className="mt-5 text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><button onClick={onClick} className="mt-6 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{action}</button></Card></main>}

function Workspace({ctx}:{ctx:BusinessContext}){
 const [customers,setCustomers]=useState<Customer[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[products,setProducts]=useState<Product[]>([]),[search,setSearch]=useState(''),[showActions,setShowActions]=useState(false),[refresh,setRefresh]=useState(0),[mobile,setMobile]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const [c,i,p]=await Promise.all([supabase.from('customers').select('id,display_name,phone,email').eq('business_id',ctx.business_id).eq('is_active',true).order('created_at',{ascending:false}).limit(12),supabase.from('invoices').select('id,invoice_number,invoice_date,status,total,balance_due,customer_id').eq('business_id',ctx.business_id).order('created_at',{ascending:false}).limit(12),supabase.from('products_services').select('id,name,sku,sales_price,inventory_tracked').eq('business_id',ctx.business_id).eq('is_active',true).order('created_at',{ascending:false}).limit(12)]);setErrorText(c.error||i.error||p.error);setCustomers(c.data||[]);setInvoices(i.data||[]);setProducts(p.data||[])};
 const setErrorText=(e:any)=>{if(e)setNotice(e.message||'Unable to load live business data')};
 useEffect(()=>{load()},[refresh,ctx.business_id]);
 const metrics=useMemo(()=>{const sales=invoices.reduce((a,x)=>a+Number(x.total||0),0),receivables=invoices.reduce((a,x)=>a+Number(x.balance_due||0),0),open=invoices.filter(x=>!['paid','void'].includes(x.status)).length;return {sales,receivables,open,customers:customers.length,products:products.length}},[invoices,customers,products]);
 const customerName=(id:string)=>customers.find(x=>x.id===id)?.display_name||'Customer';
 const filtered=invoices.filter(x=>`${x.invoice_number} ${customerName(x.customer_id)} ${x.status}`.toLowerCase().includes(search.toLowerCase()));
 const action=(label:string,desc:string,target:string)=><button onClick={()=>{setShowActions(false);location.href=`/?open=${target}`}} className="flex w-full items-start gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100">＋</span><span><b className="block text-sm">{label}</b><small className="text-xs text-slate-500">{desc}</small></span></button>;
 return <div className="min-h-screen bg-[#f5f7fb] text-slate-950">
 <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center gap-3 px-4 lg:px-7"><button onClick={()=>setMobile(!mobile)} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 lg:hidden">☰</button><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-sm font-black text-white">M</div><div><b className="text-sm">Moneymatters</b><span className="block text-[10px] text-slate-400">{ctx.business_name}</span></div></div><div className="mx-auto hidden w-full max-w-xl md:block"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search invoices, customers, products…" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm outline-none focus:bg-white focus:ring-2 focus:ring-slate-100"/></div><div className="relative"><button onClick={()=>setShowActions(!showActions)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">＋ Create</button>{showActions&&<div className="absolute right-0 mt-2 w-72 rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">{action('Invoice','Fast customer billing.','invoice')}{action('Quotation','Prepare a branded quote.','quotation')}{action('Customer','Add a customer.','customer')}{action('Product','Create a product or service.','product')}{action('Expense','Record a business expense.','expense')}{action('Payment','Record money received or paid.','payment')}</div>}</div></div></header>
 <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[230px_1fr]"><aside className={`${mobile?'block fixed inset-y-16 left-0 z-20 w-72':'hidden'} border-r border-slate-200 bg-white p-4 lg:block lg:static lg:min-h-[calc(100vh-64px)]`}><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Business cockpit</p>{[['Overview','/next-workspace'],['Sales','/next-workspace/sales'],['Customers','/next-workspace/customers'],['Purchases','/?module=Purchases'],['Expenses','/?module=Expenses'],['Inventory','/?module=Inventory'],['Banking','/?module=Banking'],['Accounting','/next-workspace/accounting'],['Tax & ITR','/next-workspace/tax'],['Reports','/next-workspace/reports'],['Settings','/?module=Settings']].map(([n,u])=><button key={n} onClick={()=>location.href=u} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium ${n==='Overview'?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-100'}`}><span className="w-5 text-center">{n==='Overview'?'⌂':'•'}</span>{n}</button>)}<div className="mt-8 rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-semibold">Automation first</p><p className="mt-2 text-xs leading-5 text-slate-300">Routine work should run automatically; financial actions can require approval.</p></div></aside>
 <main className="min-w-0 p-4 lg:p-7"><div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Business cockpit</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}.</h1><p className="mt-1 text-sm text-slate-500">Live business signals, not decorative numbers.</p></div><div className="flex gap-2"><button onClick={()=>setRefresh(x=>x+1)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">↻ Refresh</button><button onClick={()=>setShowActions(true)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Quick action</button></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Sales" value={money(metrics.sales)} note={`${invoices.length} recent invoices`} /><Metric title="Receivables" value={money(metrics.receivables)} note={`${metrics.open} open invoices`} tone="amber"/><Metric title="Customers" value={String(metrics.customers)} note="Active customers"/><Metric title="Products" value={String(metrics.products)} note="Active items & services"/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-1 text-xs text-slate-400">Live records from this business.</p></div><Pill tone="green">LIVE</Pill></div><div className="divide-y divide-slate-100">{filtered.length?filtered.map(i=><div key={i.id} className="flex items-center gap-4 p-4 sm:p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700">↗</div><div className="min-w-0 flex-1"><b className="block truncate text-sm">{i.invoice_number}</b><span className="text-xs text-slate-500">{customerName(i.customer_id)} · {date(i.invoice_date)}</span></div><div className="text-right"><b className="block text-sm">{money(Number(i.total))}</b><Pill tone={i.status==='paid'?'green':i.status==='overdue'?'amber':'slate'}>{i.status.replace('_',' ')}</Pill></div></div>):<div className="p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100">＋</div><h3 className="mt-3 text-sm font-semibold">No sales activity yet</h3><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-slate-400">Create your first quotation or invoice. This area will populate from real posted records.</p><button onClick={()=>location.href='/?open=invoice'} className="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white">Create invoice</button></div>}</div></Card>
 <div className="space-y-5"><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Needs attention</h2><p className="mt-1 text-xs text-slate-400">Only real exceptions appear here.</p></div><Pill>0 alerts</Pill></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold">Everything is clear</p><p className="mt-1 text-xs leading-5 text-slate-500">Overdue invoices, low stock and unmatched banking items will appear here as real records exist.</p></div></Card><Card className="p-5"><h2 className="font-semibold">Start faster</h2><div className="mt-3 grid gap-2">{action('Create invoice','Fast customer billing.','invoice')}{action('Add customer','Save contact once, reuse everywhere.','customer')}{action('Add product','Set price, tax and stock rules.','product')}</div></Card></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-3"><Insight title="Receivables" value={metrics.receivables?`Collect ${money(metrics.receivables)}`:'No receivables yet'} text="Collection actions will become visible as outstanding balances appear."/><Insight title="Inventory" value={products.length?'Ready to track':'Set up your first item'} text="Tracked products can drive stock movements when purchases and invoices are posted."/><Insight title="Automation" value="Approval-first" text="Routine reminders can run automatically while high-impact financial actions can require approval."/></div>
 {notice&&<div className="fixed bottom-5 right-5 z-50 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{notice}</div>}</main></div></div>
}
function Metric({title,value,note,tone='blue'}:{title:string;value:string;note:string;tone?:'blue'|'amber'}){return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-400">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone==='amber'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'}`}>•</span></div></Card>}
function Insight({title,value,text}:{title:string;value:string;text:string}){return <Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{title}</p><h3 className="mt-3 text-lg font-semibold">{value}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></Card>}
