'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';
import { deriveWorkspaceConfiguration, type WorkspaceConfiguration } from '@/lib/business-adaptation';

type Customer={id:string;display_name:string};
type Invoice={id:string;invoice_number:string;invoice_date:string;status:string;total:number;balance_due:number;customer_id:string};
type Product={id:string;name:string;sales_price:number;inventory_tracked:boolean};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
function Card({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-slate-200 bg-white shadow-[0_2px_10px_rgba(25,20,55,.035)] ${className}`}>{children}</section>}
function ActionIcon({type}:{type:'invoice'|'estimate'|'payment'|'expense'|'customer'|'product'|'inventory'|'tax'}){const common={viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};const icons={invoice:<><path d="M6 3.75h8l4 4V20.25H6z"/><path d="M14 3.75v4h4"/><path d="M9 12h6M9 15.5h4"/></>,estimate:<><path d="M7 3.75h10v16.5H7z"/><path d="M10 7.5h4M10 11h4M10 14.5h2.5"/><path d="M15.5 18.5l1.5 1.5 3-3"/></>,payment:<><rect x="3.5" y="6" width="17" height="12" rx="2"/><path d="M3.5 10h17"/><path d="M7.5 14h3"/></>,expense:<><path d="M5 4.5h11l3 3v12H5z"/><path d="M16 4.5v3h3"/><path d="M9 12h6M9 15.5h3"/><path d="M17 13v4M15 15h4"/></>,customer:<><circle cx="12" cy="8" r="3"/><path d="M5.5 19.5c.7-3.1 2.9-4.7 6.5-4.7s5.8 1.6 6.5 4.7"/><path d="M18 8.5h3M19.5 7v3"/></>,product:<><path d="M12 3.5l8 4.25v8.5L12 20.5l-8-4.25v-8.5z"/><path d="M4.5 8l7.5 4 7.5-4M12 12v8"/></>,inventory:<><path d="M4 7.5h16v12H4z"/><path d="M8 7.5V5h8v2.5M8 12h8M8 15.5h5"/></>,tax:<><path d="M6 4h12v16H6z"/><path d="M9 8h6M9 12h6M9 16h3"/></>};return <svg {...common} className="h-5 w-5">{icons[type]}</svg>}
function Metric({title,value,note,href,tone,icon}:{title:string;value:string;note:string;href:string;tone:'brand'|'success'|'warning'|'info';icon:React.ReactNode}){return <button onClick={()=>{window.location.href=href}} data-tone={tone} data-clickable="true" className="workspace-kpi group w-full text-left"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{title}</span><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/80 text-slate-600 shadow-sm transition group-hover:scale-105">{icon}</span></div><div className="mt-2 flex items-end justify-between gap-2"><strong className="text-xl font-bold tracking-tight text-slate-950">{value}</strong><span className="text-[10px] font-semibold text-slate-400 group-hover:text-violet-600">Open →</span></div><p className="mt-0.5 text-[11px] text-slate-500">{note}</p></button>}
function Empty({onClick}:{onClick:()=>void}){return <div className="grid min-h-[180px] place-items-center p-6 text-center"><div><div className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700">＋</div><h3 className="mt-3 text-sm font-semibold">No invoices yet</h3><p className="mt-1 text-xs text-slate-500">Create your first invoice and it will appear here.</p><button onClick={onClick} className="mt-3 rounded-lg bg-violet-600 px-3.5 py-2 text-xs font-semibold text-white">Create invoice</button></div></div>}
function iconFor(id:string):'invoice'|'estimate'|'payment'|'expense'|'customer'|'product'|'inventory'|'tax'{if(id==='inventory')return'inventory';if(id==='tax')return'tax';if(id==='invoice')return'invoice';if(id==='customer')return'customer';if(id==='payment')return'payment';if(id==='expense')return'expense';if(id==='estimate')return'estimate';return'product'}
function statusTone(status:string){if(status==='paid'||status==='partially_paid')return'status-success';if(status==='overdue')return'status-danger';if(status==='sent'||status==='pending')return'status-warning';return'status-neutral'}

export default function NextWorkspace(){
 const[contexts,setContexts]=useState<BusinessContext[]>([]),[ctx,setCtx]=useState<BusinessContext|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[products,setProducts]=useState<Product[]>([]),[configuration,setConfiguration]=useState<WorkspaceConfiguration|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const go=(href:string)=>{window.location.href=href};
 useEffect(()=>{let alive=true;(async()=>{const session=(await supabase.auth.getSession()).data.session;if(!session){window.location.replace('/');return}const r=await supabase.rpc('get_my_business_context');if(!alive)return;if(r.error||!r.data?.length){setError(r.error?.message||'No business workspace is available for this account.');setLoading(false);return}const rows=r.data as BusinessContext[];setContexts(rows);const saved=typeof window!=='undefined'?localStorage.getItem('moneymatters.activeBusinessId'):null;const selected=rows.find(x=>x.business_id===saved)||rows[0];setCtx(selected);if(typeof window!=='undefined')localStorage.setItem('moneymatters.activeBusinessId',selected.business_id);setLoading(false)})();return()=>{alive=false}},[]);
 useEffect(()=>{if(!ctx)return;let alive=true;(async()=>{const r=await supabase.from('businesses').select('id,category_id,subcategory_id,selling_model,inventory_enabled,tax_enabled,sales_channels,team_size,business_categories(name),business_subcategories(name)').eq('id',ctx.business_id).maybeSingle();if(!alive)return;if(r.data)setConfiguration(deriveWorkspaceConfiguration({businessId:ctx.business_id,categoryId:r.data.category_id,categoryName:r.data.business_categories?.[0]?.name ?? null,subcategoryId:r.data.subcategory_id,subcategoryName:r.data.business_subcategories?.[0]?.name ?? null,sellingModel:r.data.selling_model,inventoryEnabled:r.data.inventory_enabled,taxEnabled:r.data.tax_enabled,salesChannels:r.data.sales_channels,teamSize:r.data.team_size}));})();return()=>{alive=false}},[ctx]);
 useEffect(()=>{if(!ctx)return;(async()=>{setError('');const[c,i,p]=await Promise.all([supabase.from('customers').select('id,display_name').eq('business_id',ctx.business_id).eq('is_active',true).order('created_at',{ascending:false}).limit(100),supabase.from('invoices').select('id,invoice_number,invoice_date,status,total,balance_due,customer_id').eq('business_id',ctx.business_id).order('created_at',{ascending:false}).limit(100),supabase.from('products_services').select('id,name,sales_price,inventory_tracked').eq('business_id',ctx.business_id).eq('is_active',true).order('created_at',{ascending:false}).limit(100)]);const firstError=c.error||i.error||p.error;if(firstError)setError(firstError.message);setCustomers(c.data||[]);setInvoices(i.data||[]);setProducts(p.data||[])})()},[ctx,refresh]);
 const metrics=useMemo(()=>{const sales=invoices.reduce((a,x)=>a+Number(x.total||0),0);const collect=invoices.reduce((a,x)=>a+Number(x.balance_due||0),0);const overdue=invoices.filter(x=>x.status==='overdue');return{sales,collect,overdue}},[invoices]);
 const customerName=(id:string)=>customers.find(x=>x.id===id)?.display_name||'Customer';
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading your workspace…</div>;
 if(!ctx)return <div className="mx-auto max-w-3xl p-8"><Card className="p-8 text-center"><h1 className="text-2xl font-semibold">Business setup required</h1><p className="mt-2 text-sm text-slate-500">{error||'Create a business before using the workspace.'}</p><button onClick={()=>go('/')} className="mt-5 rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white">Open setup</button></Card></div>;
 return <main className="min-w-0 p-3 sm:p-5 lg:p-6"><div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Business cockpit</p><h1 className="mt-0.5 text-2xl font-bold tracking-tight text-slate-950 sm:text-[28px]">Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}.</h1><p className="mt-1 text-xs text-slate-500">Here is what needs your attention today.</p></div><div className="flex items-center gap-2">{contexts.length>1&&<select value={ctx.business_id} onChange={e=>{const next=contexts.find(x=>x.business_id===e.target.value);if(next){setCtx(next);localStorage.setItem('moneymatters.activeBusinessId',next.business_id)}}} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold shadow-sm"><option value={ctx.business_id}>{ctx.business_name}</option>{contexts.filter(x=>x.business_id!==ctx.business_id).map(x=><option key={x.business_id} value={x.business_id}>{x.business_name}</option>)}</select>}<button onClick={()=>setRefresh(x=>x+1)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 shadow-sm">↻ Refresh</button></div></div>{error&&<div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 text-xs text-amber-800">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Money in" value={money(metrics.sales)} note="Total invoice value" href="/next-workspace/sales" tone="brand" icon={<ActionIcon type="invoice"/>}/><Metric title="To collect" value={money(metrics.collect)} note={`${metrics.overdue.length} overdue`} href="/next-workspace/payments" tone={metrics.overdue.length?'warning':'success'} icon={<ActionIcon type="payment"/>}/><Metric title="Customers" value={String(customers.length)} note="Active relationships" href="/next-workspace/customers" tone="info" icon={<ActionIcon type="customer"/>}/><Metric title="Products & services" value={String(products.length)} note="Active catalogue" href="/next-workspace/items" tone="success" icon={<ActionIcon type="product"/>}/></div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-violet-600">Quick actions</p><h2 className="mt-0.5 text-sm font-bold text-slate-900">Run your daily work</h2></div>{configuration&&<span className="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-bold text-violet-700">{configuration.sellingModel==='both'?'Products + Services':configuration.sellingModel==='services'?'Services':'Products'}</span>}</div><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-3 lg:grid-cols-4">{(configuration?.quickActions||[]).slice(0,8).map(action=><button key={action.id} onClick={()=>go(action.href)} className="group rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-violet-200 hover:bg-violet-50/60 hover:shadow-[0_6px_16px_rgba(91,67,180,.08)]"><span className="grid h-9 w-9 place-items-center rounded-lg bg-violet-50 text-violet-700 group-hover:bg-violet-100"><ActionIcon type={iconFor(action.id)}/></span><b className="mt-2 block truncate text-xs text-slate-900">{action.label}</b><span className="mt-0.5 block line-clamp-2 text-[10px] leading-4 text-slate-500">{action.description}</span></button>)}</div></Card><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Attention</p><h2 className="mt-0.5 text-sm font-bold">Needs attention</h2></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${metrics.overdue.length?'status-danger':'status-success'}`}>{metrics.overdue.length?`${metrics.overdue.length} overdue`:'All clear'}</span></div><div className="mt-3 space-y-2">{metrics.overdue.length?<button onClick={()=>go('/next-workspace/sales')} className="flex w-full items-center justify-between rounded-lg bg-rose-50 p-2.5 text-left"><span><b className="block text-xs text-rose-900">Overdue invoices</b><span className="text-[10px] text-rose-700">Follow up now</span></span>→</button>:<div className="rounded-lg bg-emerald-50 p-2.5"><b className="block text-xs text-emerald-900">No overdue invoices</b><span className="text-[10px] text-emerald-700">Current set is clear</span></div>}<button onClick={()=>go('/next-workspace/banking')} className="flex w-full items-center justify-between rounded-lg bg-blue-50 p-2.5 text-left"><span><b className="block text-xs text-blue-900">Banking</b><span className="text-[10px] text-blue-700">Reconcile transactions</span></span>→</button></div></Card></div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Activity</p><h2 className="mt-0.5 text-sm font-bold">Recent sales</h2></div><button onClick={()=>go('/next-workspace/sales')} className="text-xs font-bold text-violet-700 hover:text-violet-900">View all →</button></div>{invoices.length?<div className="divide-y divide-slate-100">{invoices.slice(0,7).map(i=><button key={i.id} onClick={()=>go('/next-workspace/sales')} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-50"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-violet-50 text-xs font-bold text-violet-700">₹</span><span className="min-w-0 flex-1"><b className="block truncate text-xs text-slate-900">{i.invoice_number}</b><span className="block truncate text-[10px] text-slate-500">{customerName(i.customer_id)} · {i.invoice_date}</span></span><span className="hidden text-right sm:block"><b className="block text-xs text-slate-900">{money(i.total)}</b><span className="text-[10px] text-slate-400">{money(i.balance_due)} due</span></span><span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${statusTone(i.status)}`}>{i.status.replaceAll('_',' ')}</span><span className="text-slate-300">›</span></button>)}</div>:<Empty onClick={()=>go('/next-workspace/sales')}/>}</Card><Card className="p-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Finance</p><h2 className="mt-0.5 text-sm font-bold">Shortcuts</h2><div className="mt-3 grid gap-2"><button onClick={()=>go('/next-workspace/customers')} className="rounded-lg border border-slate-200 p-2.5 text-left text-xs font-semibold hover:border-violet-200 hover:bg-violet-50">Customer statements <span className="float-right text-violet-700">→</span></button><button onClick={()=>go('/next-workspace/reports')} className="rounded-lg border border-slate-200 p-2.5 text-left text-xs font-semibold hover:border-violet-200 hover:bg-violet-50">Profit & loss <span className="float-right text-violet-700">→</span></button><button onClick={()=>go('/next-workspace/accounting')} className="rounded-lg border border-slate-200 p-2.5 text-left text-xs font-semibold hover:border-violet-200 hover:bg-violet-50">Trial balance <span className="float-right text-violet-700">→</span></button><button onClick={()=>go('/next-workspace/payments')} className="rounded-lg border border-slate-200 p-2.5 text-left text-xs font-semibold hover:border-violet-200 hover:bg-violet-50">Payments <span className="float-right text-violet-700">→</span></button></div></Card></div>
 {configuration?.recommendations.length?<div className="mt-4 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-center"><p className="shrink-0 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">MoneyMatters recommends</p><div className="grid flex-1 gap-1 text-[11px] text-slate-600 sm:grid-cols-2 lg:grid-cols-4">{configuration.recommendations.slice(0,4).map(item=><span key={item} className="rounded-md bg-slate-50 px-2 py-1">{item}</span>)}</div></div></div>:null}</main>;
}
