'use client';

import { useEffect,useMemo,useState } from 'react';
import { supabase,type BusinessContext } from '@/lib/supabase';
import { Alert,Button,Card,DateInput,Field,FormSection,Input,MoneyInput,PageHeader,Select } from '@/components/moneymatters';

type Vendor={id:string;display_name:string;payment_terms_days:number};
type Product={id:string;name:string;sku:string|null;purchase_price:number;purchase_enabled:boolean;inventory_tracked:boolean;default_tax_rate_id:string|null;expense_account_id:string|null};
type TaxRate={id:string;name:string;rate:number};
type Row={product_service_id:string;description:string;quantity:number;unit_price:number;discount:number;discount_type:'amount'|'percentage';tax_rate_id:string;tax_rate:number};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const empty=():Row=>({product_service_id:'',description:'',quantity:1,unit_price:0,discount:0,discount_type:'amount',tax_rate_id:'',tax_rate:0});
export default function NewPurchaseBill(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[vendors,setVendors]=useState<Vendor[]>([]),[products,setProducts]=useState<Product[]>([]),[taxRates,setTaxRates]=useState<TaxRate[]>([]),[vendorId,setVendorId]=useState(''),[billNumber,setBillNumber]=useState(''),[billDate,setBillDate]=useState(today()),[dueDate,setDueDate]=useState(today()),[supplyType,setSupplyType]=useState('intra_state'),[reverseCharge,setReverseCharge]=useState(false),[taxInclusive,setTaxInclusive]=useState(false),[notes,setNotes]=useState(''),[rows,setRows]=useState<Row[]>([empty()]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const[v,p,t,n]=await Promise.all([supabase.from('vendors').select('id,display_name,payment_terms_days').eq('business_id',b.business_id).eq('is_active',true).order('display_name'),supabase.from('products_services').select('id,name,sku,purchase_price,purchase_enabled,inventory_tracked,default_tax_rate_id,expense_account_id').eq('business_id',b.business_id).eq('is_active',true).eq('purchase_enabled',true).order('name'),supabase.from('tax_rates').select('id,name,rate').eq('business_id',b.business_id).eq('is_active',true).order('rate'),supabase.rpc('next_document_number',{p_business_id:b.business_id,p_document_type:'bill'})]);setVendors(v.data||[]);setProducts(p.data||[]);setTaxRates(t.data||[]);if(n.data)setBillNumber(n.data);const e=v.error||p.error||t.error||n.error;if(e)setError(e.message);setLoading(false)})()},[]);
 const onVendor=(id:string)=>{setVendorId(id);const v=vendors.find(x=>x.id===id);if(v){const d=new Date(billDate);d.setDate(d.getDate()+Number(v.payment_terms_days||0));setDueDate(d.toISOString().slice(0,10));}};
 const update=(i:number,p:Partial<Row>)=>setRows(rs=>rs.map((r,n)=>n===i?{...r,...p}:r));
 const choose=(i:number,id:string)=>{const p=products.find(x=>x.id===id);const t=p&&taxRates.find(x=>x.id===p.default_tax_rate_id);update(i,p?{product_service_id:id,description:p.name,unit_price:Number(p.purchase_price||0),tax_rate_id:t?.id||'',tax_rate:Number(t?.rate||0)}:{product_service_id:'',description:'',unit_price:0,tax_rate_id:'',tax_rate:0});};
 const calc=useMemo(()=>{let subtotal=0,discountTotal=0,taxTotal=0;const lines=rows.filter(r=>r.description.trim()).map(r=>{const gross=Math.max(Number(r.quantity||0)*Number(r.unit_price||0),0);const disc=r.discount_type==='percentage'?gross*Number(r.discount||0)/100:Number(r.discount||0);const net=Math.max(gross-disc,0);const rate=Number(r.tax_rate||0);const base=taxInclusive&&rate>0?net/(1+rate/100):net;const tax=taxInclusive&&rate>0?net-base:base*rate/100;const total=base+tax;subtotal+=base;discountTotal+=disc;taxTotal+=tax;return{...r,discountAmount:disc,taxAmount:tax,lineTotal:total};});return{lines,subtotal,discountTotal,taxTotal,total:subtotal+taxTotal};},[rows,taxInclusive]);
 const save=async(post:boolean)=>{if(!ctx||!vendorId){setError('Select a supplier/vendor.');return}if(!calc.lines.length||calc.total<=0){setError('Add at least one bill line with a positive value.');return}setSaving(true);setError('');try{const u=await supabase.auth.getUser();const{data:bill,error:be}=await supabase.from('bills').insert({business_id:ctx.business_id,vendor_id:vendorId,bill_number:billNumber,bill_date:billDate,due_date:dueDate,status:'draft',currency_code:ctx.currency_code,subtotal:calc.subtotal,discount_total:calc.discountTotal,tax_total:calc.taxTotal,total:calc.total,amount_paid:0,balance_due:calc.total,notes:notes||null,terms:null,place_of_supply_state_code:null,supply_type:supplyType,reverse_charge:reverseCharge,tax_inclusive:taxInclusive,created_by:u.data.user?.id||null}).select('id').single();if(be||!bill)throw be||new Error('Unable to create bill');const{error:ie}=await supabase.from('bill_items').insert(calc.lines.map((r,i)=>({bill_id:bill.id,product_service_id:r.product_service_id||null,description:r.description,quantity:Number(r.quantity),unit_price:Number(r.unit_price),discount:Number(r.discountAmount),discount_type:r.discount_type,tax_rate_id:r.tax_rate_id||null,tax_amount:Number(r.taxAmount),line_total:Number(r.lineTotal),expense_account_id:products.find(p=>p.id===r.product_service_id)?.expense_account_id||null,sort_order:i})));if(ie)throw ie;if(post){const{error:pe}=await supabase.rpc('post_bill',{p_bill_id:bill.id});if(pe)throw pe;}location.href=`/next-workspace/purchases/${bill.id}`;}catch(e:any){setError(e?.message||'Unable to save purchase bill.')}finally{setSaving(false)}};
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Preparing purchase bill…</div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]"><PageHeader eyebrow="Money out" title="New Purchase Bill" description="Create a multi-line supplier bill and let the existing accounting engine handle posting." actions={<Button variant="secondary" onClick={()=>location.href='/next-workspace/purchases'}>← Purchases</Button>}/>{error&&<div className="mb-5"><Alert tone="error" title="Purchase bill could not be saved">{error}</Alert></div>}
 <FormSection title="Bill details" description="Supplier terms and document controls."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Supplier / Vendor" required><Select value={vendorId} onChange={e=>onVendor(e.target.value)}><option value="">Select supplier…</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.display_name}</option>)}</Select></Field><Field label="Bill number"><Input value={billNumber} readOnly className="bg-slate-50"/></Field><Field label="Bill date" required><DateInput value={billDate} onChange={e=>setBillDate(e.target.value)}/></Field><Field label="Due date"><DateInput value={dueDate} onChange={e=>setDueDate(e.target.value)}/></Field></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Supply type"><Select value={supplyType} onChange={e=>setSupplyType(e.target.value)}><option value="intra_state">Intra-state</option><option value="inter_state">Inter-state</option><option value="export">Export</option><option value="other">Other</option></Select></Field><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={reverseCharge} onChange={e=>setReverseCharge(e.target.checked)}/> Reverse charge</label><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={taxInclusive} onChange={e=>setTaxInclusive(e.target.checked)}/> Prices include tax</label></div></FormSection>
 <FormSection className="mt-5" title="Line items" description="Inventory-tracked products are handled by post_bill(); non-inventory lines follow the existing expense/account mapping." actions={<Button size="sm" variant="secondary" onClick={()=>setRows(rs=>[...rs,empty()])}>＋ Add line</Button>}><div className="space-y-4">{rows.map((r,i)=><Card key={i} className="p-4"><div className="grid gap-4 lg:grid-cols-[2fr_100px_140px_170px_140px_auto] lg:items-end"><Field label="Product / service"><Select value={r.product_service_id} onChange={e=>choose(i,e.target.value)}><option value="">Select product/service…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.sku?` · ${p.sku}`:''}</option>)}</Select></Field><Field label="Qty"><MoneyInput value={r.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></Field><Field label="Unit price"><MoneyInput value={r.unit_price} onChange={e=>update(i,{unit_price:Number(e.target.value)})}/></Field><Field label="Discount"><div className="flex gap-1"><MoneyInput value={r.discount} onChange={e=>update(i,{discount:Number(e.target.value)})}/><Select value={r.discount_type} onChange={e=>update(i,{discount_type:e.target.value as Row['discount_type']})} className="w-20"><option value="amount">₹</option><option value="percentage">%</option></Select></div></Field><Field label="GST / Tax"><Select value={r.tax_rate_id} onChange={e=>{const t=taxRates.find(x=>x.id===e.target.value);update(i,{tax_rate_id:e.target.value,tax_rate:Number(t?.rate||0)})}}><option value="">No tax</option>{taxRates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.rate}%</option>)}</Select></Field><Button variant="danger" size="sm" disabled={rows.length===1} onClick={()=>setRows(rs=>rs.filter((_,n)=>n!==i))}>Remove</Button></div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto] md:items-center"><Input value={r.description} onChange={e=>update(i,{description:e.target.value})} placeholder="Line description"/><div className="text-sm font-semibold">{money(calc.lines[i]?.lineTotal||0)}</div></div></Card>)}</div></FormSection>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_380px]"><FormSection title="Notes" description="Optional internal note or supplier terms."><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" placeholder="Add notes…"/></FormSection><Card className="p-5"><div className="space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(calc.subtotal)}</span></div><div className="flex justify-between text-slate-500"><span>Discount</span><span>-{money(calc.discountTotal)}</span></div><div className="flex justify-between"><span>Tax</span><span>{money(calc.taxTotal)}</span></div><div className="border-t border-slate-100 pt-3 flex justify-between text-base font-semibold"><span>Total</span><span>{money(calc.total)}</span></div></div><div className="mt-5 grid gap-2"><Button variant="secondary" disabled={saving} onClick={()=>save(false)}>{saving?'Saving…':'Save draft'}</Button><Button disabled={saving} onClick={()=>save(true)}>{saving?'Posting…':'Save & post bill'}</Button></div><p className="mt-3 text-[11px] leading-5 text-slate-400">Posting delegates to the existing <b>post_bill()</b> RPC; the browser does not create journal, AP or inventory entries.</p></Card></div>
 </div></main>;
}
