'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Vendor = { id: string; display_name: string; payment_terms_days: number };
type Product = { id: string; name: string; sku: string | null; purchase_price: number; purchase_enabled: boolean; inventory_tracked: boolean; default_tax_rate_id: string | null; expense_account_id: string | null };
type TaxRate = { id: string; name: string; rate: number };
type Account = { id: string; code: string; name: string; account_type: string };
type Row = { product_service_id: string; description: string; quantity: number; unit_price: number; discount: number; discount_type: 'amount' | 'percentage'; tax_rate_id: string; tax_rate: number };

const money = (n:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
const today = () => new Date().toISOString().slice(0,10);
const emptyRow = (): Row => ({product_service_id:'',description:'',quantity:1,unit_price:0,discount:0,discount_type:'amount',tax_rate_id:'',tax_rate:0});

export default function NewPurchaseBill(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[vendors,setVendors]=useState<Vendor[]>([]),[products,setProducts]=useState<Product[]>([]),[taxRates,setTaxRates]=useState<TaxRate[]>([]),[accounts,setAccounts]=useState<Account[]>([]);
 const [vendorId,setVendorId]=useState(''),[billDate,setBillDate]=useState(today()),[dueDate,setDueDate]=useState(today()),[billNumber,setBillNumber]=useState(''),[supplyType,setSupplyType]=useState('intra_state'),[reverseCharge,setReverseCharge]=useState(false),[taxInclusive,setTaxInclusive]=useState(false),[notes,setNotes]=useState('');
 const [rows,setRows]=useState<Row[]>([emptyRow()]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);const [v,p,t,a,n]=await Promise.all([
   supabase.from('vendors').select('id,display_name,payment_terms_days').eq('business_id',b.business_id).eq('is_active',true).order('display_name'),
   supabase.from('products_services').select('id,name,sku,purchase_price,purchase_enabled,inventory_tracked,default_tax_rate_id,expense_account_id').eq('business_id',b.business_id).eq('is_active',true).eq('purchase_enabled',true).order('name'),
   supabase.from('tax_rates').select('id,name,rate').eq('business_id',b.business_id).eq('is_active',true).order('rate'),
   supabase.from('accounts').select('id,code,name,account_type').eq('business_id',b.business_id).eq('is_active',true).eq('account_type','asset').order('code'),
   supabase.rpc('next_document_number',{p_business_id:b.business_id,p_document_type:'bill'})
 ]);setVendors(v.data||[]);setProducts(p.data||[]);setTaxRates(t.data||[]);setAccounts(a.data||[]);if(n.data)setBillNumber(n.data);setLoading(false);const e=v.error||p.error||t.error||a.error||n.error;if(e)setError(e.message)})()},[]);
 const onVendor=(id:string)=>{setVendorId(id);const v=vendors.find(x=>x.id===id);if(v){const d=new Date(billDate);d.setDate(d.getDate()+Number(v.payment_terms_days||0));setDueDate(d.toISOString().slice(0,10));}};
 const updateRow=(i:number,patch:Partial<Row>)=>setRows(r=>r.map((x,n)=>n===i?{...x,...patch}:x));
 const selectProduct=(i:number,id:string)=>{const p=products.find(x=>x.id===id);if(!p){updateRow(i,{product_service_id:'',description:'',unit_price:0,tax_rate_id:'',tax_rate:0});return}const tr=taxRates.find(x=>x.id===p.default_tax_rate_id);updateRow(i,{product_service_id:id,description:p.name,unit_price:Number(p.purchase_price||0),tax_rate_id:tr?.id||'',tax_rate:Number(tr?.rate||0)});};
 const calc=useMemo(()=>{let subtotal=0,discountTotal=0,taxTotal=0;const lines=rows.filter(r=>r.description.trim()).map(r=>{const gross=Math.max(Number(r.quantity||0)*Number(r.unit_price||0),0);const discount=r.discount_type==='percentage'?gross*Number(r.discount||0)/100:Number(r.discount||0);const base=Math.max(gross-discount,0);let tax=base*Number(r.tax_rate||0)/100;if(taxInclusive){tax=base-(base/(1+Number(r.tax_rate||0)/100));}const lineTotal=taxInclusive?base:base+tax;subtotal+=base;discountTotal+=discount;taxTotal+=tax;return {...r,discountAmount:discount,taxAmount:tax,lineTotal};});return{lines,subtotal,discountTotal,taxTotal,total:subtotal+taxTotal};},[rows,taxInclusive]);
 const save=async(post:boolean)=>{if(!ctx||!vendorId){setError('Select a supplier/vendor.');return}if(!calc.lines.length||calc.total<=0){setError('Add at least one bill line with a positive value.');return}setSaving(true);setError('');try{const {data:bill,error:be}=await supabase.from('bills').insert({business_id:ctx.business_id,vendor_id:vendorId,bill_number:billNumber,bill_date:billDate,due_date:dueDate,status:'draft',currency_code:ctx.currency_code,subtotal:calc.subtotal,discount_total:calc.discountTotal,tax_total:calc.taxTotal,total:calc.total,amount_paid:0,balance_due:calc.total,notes:notes||null,terms:null,place_of_supply_state_code:null,supply_type:supplyType,reverse_charge:reverseCharge,tax_inclusive:taxInclusive,created_by:(await supabase.auth.getUser()).data.user?.id||null}).select('id').single();if(be||!bill)throw be||new Error('Unable to create bill');
   const {error:ie}=await supabase.from('bill_items').insert(calc.lines.map((r,i)=>({bill_id:bill.id,product_service_id:r.product_service_id||null,description:r.description,quantity:Number(r.quantity),unit_price:Number(r.unit_price),discount:Number(r.discountAmount),discount_type:r.discount_type,tax_rate_id:r.tax_rate_id||null,tax_amount:Number(r.taxAmount),line_total:Number(r.lineTotal),expense_account_id:products.find(p=>p.id===r.product_service_id)?.expense_account_id||null,sort_order:i})));if(ie)throw ie;
   if(post){const {error:pe}=await supabase.rpc('post_bill',{p_bill_id:bill.id});if(pe)throw pe;}
   location.href=`/next-workspace/purchases/${bill.id}`;
 }catch(e:any){setError(e?.message||'Unable to save purchase bill.')}finally{setSaving(false)}};
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Preparing purchase bill…</div>;
 return <main className="min-h-screen bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]">
  <header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-600">Money out</p><h1 className="mt-1 text-3xl font-semibold">New Purchase Bill</h1><p className="mt-2 text-sm text-slate-500">Draft first, then post through the accounting engine when ready.</p></div><button onClick={()=>location.href='/next-workspace/purchases'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Purchases</button></header>
  {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-4"><Field label="Supplier / Vendor"><select value={vendorId} onChange={e=>onVendor(e.target.value)} className="input"><option value="">Select supplier…</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.display_name}</option>)}</select></Field><Field label="Bill number"><input value={billNumber} readOnly className="input bg-slate-50"/></Field><Field label="Bill date"><input type="date" value={billDate} onChange={e=>setBillDate(e.target.value)} className="input"/></Field><Field label="Due date"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="input"/></Field></div><div className="mt-4 grid gap-4 md:grid-cols-4"><Field label="Supply"><select value={supplyType} onChange={e=>setSupplyType(e.target.value)} className="input"><option value="intra_state">Intra-state</option><option value="inter_state">Inter-state</option><option value="export">Export</option><option value="other">Other</option></select></Field><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={reverseCharge} onChange={e=>setReverseCharge(e.target.checked)}/> Reverse charge</label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={taxInclusive} onChange={e=>setTaxInclusive(e.target.checked)}/> Prices include tax</label></div></section>
  <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><h2 className="font-semibold">Items</h2><p className="text-xs text-slate-500">Products post to inventory when inventory tracking is enabled; other lines post to expense.</p></div><button onClick={()=>setRows(r=>[...r,emptyRow()])} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">+ Add line</button></div><div className="hidden grid-cols-[2fr_90px_120px_120px_110px_130px] gap-3 border-b border-slate-100 px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Product / description</span><span>Qty</span><span>Unit price</span><span>Discount</span><span>Tax</span><span className="text-right">Line total</span></div><div className="divide-y divide-slate-100">{rows.map((r,i)=><div key={i} className="grid gap-3 p-4 md:grid-cols-[2fr_90px_120px_120px_110px_130px] md:items-center"><div><select value={r.product_service_id} onChange={e=>selectProduct(i,e.target.value)} className="input"><option value="">Select product/service…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.sku?` · ${p.sku}`:''}</option>)}</select><input value={r.description} onChange={e=>updateRow(i,{description:e.target.value})} placeholder="Description" className="input mt-2"/></div><input type="number" min="0" step="0.01" value={r.quantity} onChange={e=>updateRow(i,{quantity:Number(e.target.value)})} className="input"/><input type="number" min="0" step="0.01" value={r.unit_price} onChange={e=>updateRow(i,{unit_price:Number(e.target.value)})} className="input"/><div className="flex gap-1"><input type="number" min="0" step="0.01" value={r.discount} onChange={e=>updateRow(i,{discount:Number(e.target.value)})} className="input min-w-0"/><select value={r.discount_type} onChange={e=>updateRow(i,{discount_type:e.target.value as Row['discount_type']})} className="w-20 rounded-xl border border-slate-200 text-xs"><option value="amount">₹</option><option value="percentage">%</option></select></div><select value={r.tax_rate_id} onChange={e=>{const t=taxRates.find(x=>x.id===e.target.value);updateRow(i,{tax_rate_id:e.target.value,tax_rate:Number(t?.rate||0)})}} className="input"><option value="">No tax</option>{taxRates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.rate}%</option>)}</select><div className="flex items-center justify-between md:justify-end gap-2"><b className="text-sm">{money(calc.lines[i]?.lineTotal||0)}</b>{rows.length>1&&<button onClick={()=>setRows(r=>r.filter((_,n)=>n!==i))} className="text-xs text-rose-600">Remove</button>}</div></div>)}</div></section>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Notes</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} placeholder="Optional internal note or supplier terms…" className="input mt-3 w-full"/></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="space-y-3 text-sm"><Sum label="Subtotal" value={calc.subtotal}/><Sum label="Discount" value={-calc.discountTotal}/><Sum label="Tax" value={calc.taxTotal}/><div className="border-t border-slate-100 pt-3"><Sum label="Total" value={calc.total} bold/></div></div><div className="mt-5 grid gap-2"><button disabled={saving} onClick={()=>save(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold disabled:opacity-50">{saving?'Saving…':'Save draft'}</button><button disabled={saving} onClick={()=>save(true)} className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?'Posting…':'Save & post bill'}</button></div><p className="mt-3 text-[11px] leading-5 text-slate-400">Posting calls the existing <b>post_bill()</b> RPC. No journal, AP or inventory entries are created by the browser.</p></section></div>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">{label}</span>{children}</label>}
function Sum({label,value,bold=false}:{label:string;value:number;bold?:boolean}){return <div className={`flex justify-between ${bold?'text-base font-semibold':'text-slate-600'}`}><span>{label}</span><span>{money(value)}</span></div>}
function FieldStyles(){return null}
