-- Moneymatters migration/import/export v1
-- Source-controlled counterpart of the live migration hardening.
CREATE TABLE IF NOT EXISTS public.import_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  import_type text NOT NULL CHECK(import_type IN ('customers','vendors','products_services','accounts','invoices','bills','payments','bank_transactions','opening_balances')),
  source_format text NOT NULL CHECK(source_format IN ('csv','json','xlsx')), status text NOT NULL DEFAULT 'staged' CHECK(status IN ('staged','validated','committed','failed','rolled_back')),
  row_count integer NOT NULL DEFAULT 0, valid_count integer NOT NULL DEFAULT 0, error_count integer NOT NULL DEFAULT 0,
  payload jsonb NOT NULL DEFAULT '[]'::jsonb, validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb, result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), validated_at timestamptz, committed_at timestamptz, rolled_back_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.import_job_rows (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_job_id uuid NOT NULL REFERENCES public.import_jobs(id) ON DELETE CASCADE,
  row_number integer NOT NULL, row_data jsonb NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','valid','error','imported','skipped')),
  errors jsonb NOT NULL DEFAULT '[]'::jsonb, created_record_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(import_job_id,row_number)
);
CREATE INDEX IF NOT EXISTS import_jobs_business_idx ON public.import_jobs(business_id,created_at DESC);
CREATE INDEX IF NOT EXISTS import_job_rows_job_idx ON public.import_job_rows(import_job_id,row_number);
ALTER TABLE public.import_jobs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.import_job_rows ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.stage_import_job(p_business_id uuid,p_import_type text,p_source_format text,p_rows jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,mm_private AS $$ DECLARE jid uuid;r jsonb;i integer:=0;BEGIN IF NOT mm_private.has_business_permission(p_business_id,'accounting.view') THEN RAISE EXCEPTION 'Access denied';END IF;IF jsonb_typeof(p_rows)<>'array' THEN RAISE EXCEPTION 'Import rows must be a JSON array';END IF;INSERT INTO public.import_jobs(business_id,import_type,source_format,row_count,payload,created_by) VALUES(p_business_id,p_import_type,p_source_format,jsonb_array_length(p_rows),p_rows,auth.uid()) RETURNING id INTO jid;FOR r IN SELECT * FROM jsonb_array_elements(p_rows) LOOP i:=i+1;INSERT INTO public.import_job_rows(import_job_id,row_number,row_data) VALUES(jid,i,r);END LOOP;RETURN jid;END;$$;
CREATE OR REPLACE FUNCTION public.validate_import_job(p_import_job_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,mm_private AS $$ DECLARE j public.import_jobs%rowtype;r record;errs jsonb;ok integer:=0;bad integer:=0;BEGIN SELECT * INTO j FROM public.import_jobs WHERE id=p_import_job_id FOR UPDATE;IF j.id IS NULL THEN RAISE EXCEPTION 'Import job not found';END IF;IF NOT mm_private.has_business_permission(j.business_id,'accounting.view') THEN RAISE EXCEPTION 'Access denied';END IF;FOR r IN SELECT * FROM public.import_job_rows WHERE import_job_id=j.id ORDER BY row_number LOOP errs:='[]'::jsonb;IF j.import_type IN ('customers','vendors') AND coalesce(trim(r.row_data->>'display_name'),'')='' THEN errs:=errs||jsonb_build_array('display_name is required');END IF;IF j.import_type='products_services' AND coalesce(trim(r.row_data->>'name'),'')='' THEN errs:=errs||jsonb_build_array('name is required');END IF;IF jsonb_array_length(errs)=0 THEN UPDATE public.import_job_rows SET status='valid',errors='[]'::jsonb WHERE id=r.id;ok:=ok+1;ELSE UPDATE public.import_job_rows SET status='error',errors=errs WHERE id=r.id;bad:=bad+1;END IF;END LOOP;UPDATE public.import_jobs SET valid_count=ok,error_count=bad,status=CASE WHEN bad=0 THEN 'validated' ELSE 'failed' END,validation_errors=(SELECT coalesce(jsonb_agg(jsonb_build_object('row',row_number,'errors',errors)),'[]'::jsonb) FROM public.import_job_rows WHERE import_job_id=j.id AND status='error'),validated_at=now() WHERE id=j.id;RETURN jsonb_build_object('job_id',j.id,'valid_count',ok,'error_count',bad,'status',CASE WHEN bad=0 THEN 'validated' ELSE 'failed' END);END;$$;
CREATE OR REPLACE FUNCTION public.export_business_dataset(p_business_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,mm_private AS $$ DECLARE out jsonb;BEGIN IF NOT mm_private.has_business_permission(p_business_id,'accounting.view') THEN RAISE EXCEPTION 'Access denied';END IF;SELECT jsonb_build_object('schema_version','moneymatters-export-v1','exported_at',now(),'business_id',p_business_id,'customers',(SELECT coalesce(jsonb_agg(to_jsonb(c)-'business_id'),'[]'::jsonb) FROM public.customers c WHERE c.business_id=p_business_id),'vendors',(SELECT coalesce(jsonb_agg(to_jsonb(v)-'business_id'),'[]'::jsonb) FROM public.vendors v WHERE v.business_id=p_business_id),'products_services',(SELECT coalesce(jsonb_agg(to_jsonb(p)-'business_id'),'[]'::jsonb) FROM public.products_services p WHERE p.business_id=p_business_id),'accounts',(SELECT coalesce(jsonb_agg(to_jsonb(a)-'business_id'),'[]'::jsonb) FROM public.accounts a WHERE a.business_id=p_business_id),'invoices',(SELECT coalesce(jsonb_agg(to_jsonb(i)-'business_id'),'[]'::jsonb) FROM public.invoices i WHERE i.business_id=p_business_id),'invoice_items',(SELECT coalesce(jsonb_agg(to_jsonb(ii)),'[]'::jsonb) FROM public.invoice_items ii JOIN public.invoices i ON i.id=ii.invoice_id WHERE i.business_id=p_business_id),'bills',(SELECT coalesce(jsonb_agg(to_jsonb(b)-'business_id'),'[]'::jsonb) FROM public.bills b WHERE b.business_id=p_business_id),'bill_items',(SELECT coalesce(jsonb_agg(to_jsonb(bi)),'[]'::jsonb) FROM public.bill_items bi JOIN public.bills b ON b.id=bi.bill_id WHERE b.business_id=p_business_id),'payments',(SELECT coalesce(jsonb_agg(to_jsonb(p)-'business_id'),'[]'::jsonb) FROM public.payments p WHERE p.business_id=p_business_id),'bank_transactions',(SELECT coalesce(jsonb_agg(to_jsonb(bt)),'[]'::jsonb) FROM public.bank_transactions bt JOIN public.bank_accounts ba ON ba.id=bt.bank_account_id WHERE ba.business_id=p_business_id)) INTO out;RETURN out;END;$$;
REVOKE EXECUTE ON FUNCTION public.stage_import_job(uuid,text,text,jsonb) FROM public,anon; GRANT EXECUTE ON FUNCTION public.stage_import_job(uuid,text,text,jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_import_job(uuid) FROM public,anon; GRANT EXECUTE ON FUNCTION public.validate_import_job(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.export_business_dataset(uuid) FROM public,anon; GRANT EXECUTE ON FUNCTION public.export_business_dataset(uuid) TO authenticated;
