create or replace function public.seed_default_chart_of_accounts(p_business_id uuid)
returns integer language plpgsql set search_path=public as $$
declare n integer;
begin
 insert into public.accounts(business_id,code,name,account_type,normal_balance,is_system)
 values
 (p_business_id,'1000','Cash','asset','debit',true),(p_business_id,'1010','Bank','asset','debit',true),(p_business_id,'1100','Accounts Receivable','asset','debit',true),(p_business_id,'1200','Inventory','asset','debit',true),(p_business_id,'1300','Input Tax Credit','asset','debit',true),(p_business_id,'2000','Accounts Payable','liability','credit',true),(p_business_id,'2100','Tax Payable','liability','credit',true),(p_business_id,'3000','Owner Equity','equity','credit',true),(p_business_id,'3100','Retained Earnings','equity','credit',true),(p_business_id,'4000','Sales Revenue','income','credit',true),(p_business_id,'4100','Other Income','income','credit',true),(p_business_id,'5000','Cost of Goods Sold','expense','debit',true),(p_business_id,'6000','Operating Expenses','expense','debit',true),(p_business_id,'6100','Payroll Expense','expense','debit',true),(p_business_id,'6200','Bank & Payment Fees','expense','debit',true),
 (p_business_id,'6010','Premises Rent','expense','debit',true),(p_business_id,'6011','Electricity & Utilities','expense','debit',true),(p_business_id,'6012','Maintenance & Repairs','expense','debit',true),(p_business_id,'6013','Office Supplies','expense','debit',true),(p_business_id,'6014','Internet & Broadband','expense','debit',true),(p_business_id,'6015','Software & Subscriptions','expense','debit',true),(p_business_id,'6016','Telephone & Mobile','expense','debit',true),(p_business_id,'6017','Insurance','expense','debit',true),(p_business_id,'6018','Professional & Legal Fees','expense','debit',true),(p_business_id,'6019','Marketing & Advertising','expense','debit',true),(p_business_id,'6020','Travel & Local Conveyance','expense','debit',true),(p_business_id,'6021','Transport & Freight','expense','debit',true),(p_business_id,'6022','Vehicle Running & Fuel','expense','debit',true),(p_business_id,'6023','Employee Welfare','expense','debit',true),(p_business_id,'6024','General Operating Expense','expense','debit',true),
 (p_business_id,'1500','Furniture & Fixtures','asset','debit',true),(p_business_id,'1510','Computer & IT Equipment','asset','debit',true),(p_business_id,'1520','Other Fixed Assets','asset','debit',true)
 on conflict(business_id,code) do update set name=excluded.name,account_type=excluded.account_type,normal_balance=excluded.normal_balance,is_system=true,is_active=true;
 insert into public.expense_categories(business_id,name,account_id,is_active)
 select p_business_id,v.category,a.id,true from (values
 ('Office / Shop / Mall Rent','6010'),('Electricity & Utilities','6011'),('Maintenance & Repairs','6012'),('Office Supplies','6013'),('Broadband & Internet','6014'),('Software & Subscriptions','6015'),('Telephone & Mobile','6016'),('Insurance','6017'),('Professional & Legal Fees','6018'),('Marketing & Advertising','6019'),('Travel & Local Conveyance','6020'),('Transport & Freight','6021'),('Vehicle Running & Fuel','6022'),('Salaries & Wages','6100'),('Employee Welfare','6023'),('General Operating Expense','6024'),('Furniture & Fixtures (Asset Purchase)','1500'),('Computer / Laptop / IT Equipment (Asset Purchase)','1510'),('Other Fixed Asset (Asset Purchase)','1520'),('Bank & Payment Fees','6200')
 ) as v(category,code) join public.accounts a on a.business_id=p_business_id and a.code=v.code on conflict(business_id,name) do update set account_id=excluded.account_id,is_active=true;
 select count(*) into n from public.accounts where business_id=p_business_id;
 return n;
end; $$;