'use client';

import {Suspense,useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';

type Job={id:string;document_type:string;document_id:string;template_id:string|null;template_version:number|null;payload:any;status:string};
type Template={template_key:string;template_name:string};
const money=(n:any,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:String(c||'INR').trim(),maximumFractionDigits:2}).format(Number(n||0));
const text=(v:any)=>String(v??'');
const styles:Record<string,{header:string;table:string;rule:string;accent:string}>= {bold:{header:'bg-slate-900 text-white',table:'bg-slate-800 text-white',rule:'border-slate-900',accent:'text-slate-900'},classic:{header:'bg-white text-slate-900',table:'bg-slate-700 text-white',rule:'border-slate-900',accent:'text-slate-900'},compact:{header:'bg-slate-700 text-white',table:'bg-slate-700 text-white',rule:'border-slate-700',accent:'text-slate-800'},minimal:{header:'bg-white text-slate-900',table:'bg-slate-100 text-slate-700',rule:'border-slate-200',accent:'text-slate-700'},modern:{header:'bg-violet-50 text-slate-900 border-l-4 border-violet-600',table:'bg-violet-600 text-white',rule:'border-violet-600',accent:'text-violet-700'}};

function DocumentsContent(){
 const qs=useSearchParams();const type=qs.get('type')||'invoice';const id=qs.get('id')||'';
 const[job,setJob]=useState<Job|null>(null),[template,setTemplate]=useState<Template|null>(null),[docPref,setDocPref]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!id){setError('Document id is required.');setLoading(false);return}const r=await supabase.rpc('prepare_document_render',{p_document_type:type,p_document_id:id,p_template_id:null});if(r.error){setError(r.error.message);setLoading(false);return}const j=await supabase.from('document_render_jobs').select('id,document_type,document_id,template_id,template_version,payload,status').eq('id',r.data).single();if(j.error){setError(j.error.message);setLoading(false);return}setJob(j.data as Job);if(j.data?.template_id){const t=await supabase.from('document_templates').select('template_key,template_name').eq('id',j.data.template_id).maybeSingle();setTemplate(t.data as Template|null)}const b=j.data?.payload?.business?.id||j.data?.payload?.business_id;const p=await supabase.from('business_document_preferences').select('custom_fields,show_payment_qr,show_payment_link').eq('business_id',b).eq('document_type',type).maybeSingle();setDocPref(p.data||null);setLoading(false)})()},[type,id]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-slate-500">Preparing document…</div>;
 if(error)return <div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-rose-600">{error}</div>;
 const p=job?.payload||{},b=p.business||{},c=p.customer||{},items=p.items||[];const key=template?.template_key||'classic';const st=styles[key]||styles.classic;
 const gst=type==='invoice'&&(Number(p.tax_total)>0||!!b.tax_registration_number);const title=type==='invoice'?(gst?'TAX INVOICE':'INVOICE'):type==='quotation'?'ESTIMATE':type==='receipt'?'PAYMENT RECEIPT':type==='credit_note'?'CREDIT NOTE':'DEBIT NOTE';
 const number=p.invoice_number||p.quotation_number||p.receipt_number||p.credit_note_number||p.debit_note_number||'';const date=p.invoice_date||p.quotation_date||p.receipt_date||p.credit_note_date||p.debit_note_date||'';const total=p.total??p.amount??0;const balance=Number(p.balance_due??total);const cf=docPref?.custom_fields||{};const showPay=type==='invoice'&&(cf.show_pay_now??true);const showQr=type==='invoice'&&(cf.show_payment_qr??true);
 const isReceipt=type==='receipt';
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="mx-auto mb-4 flex max-w-[900px] items-center justify-between print:hidden"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Document center</p><h1 className="mt-1 text-xl font-semibold">{title} {number}</h1><p className="text-xs text-slate-500">{template?.template_name||'Classic'} · Template v{job?.template_version||1} · Print-ready</p></div><div className="flex gap-2"><button onClick={()=>history.back()} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Back</button><button onClick={()=>window.print()} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Print / Save PDF</button></div></div>
 <article className="mx-auto min-h-[1120px] max-w-[900px] bg-white p-10 shadow-xl print:min-h-0 print:max-w-none print:p-10 print:shadow-none" style={{fontFamily:'Arial,sans-serif'}}>
 {isReceipt?<Receipt title={text(cf.title||title)} number={number} date={date} p={p} b={b} c={c} total={total} cf={cf}/>:<><header className={`rounded-2xl p-6 ${st.header} ${key==='minimal'?'border-b':key==='classic'?'border-b-2':''}`}><div className="flex items-start justify-between gap-8"><div><div className="text-2xl font-black">{text(b.name||b.legal_name||'Business')}</div>{b.address&&<div className="mt-2 max-w-sm text-xs leading-5 opacity-75">{typeof b.address==='string'?b.address:JSON.stringify(b.address)}</div>}{b.tax_registration_number&&<div className="mt-2 text-xs font-semibold">GSTIN / Tax ID: {b.tax_registration_number}</div>}</div><div className="text-right"><div className={`text-3xl font-black ${key==='modern'?'text-violet-700':''}`}>{text(cf.title||title)}</div><div className="mt-3 text-sm"><b>No.</b> {number}</div><div className="mt-1 text-sm"><b>Date</b> {date}</div>{p.due_date&&<div className="mt-1 text-sm"><b>Due</b> {p.due_date}</div>}</div></div></header>
 <section className="mt-8 grid grid-cols-2 gap-8"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Bill to</p><div className="mt-2 text-base font-bold">{text(c.display_name||c.legal_name||'')}</div><div className="mt-1 text-xs text-slate-500">{c.email||''}{c.phone?` · ${c.phone}`:''}</div>{c.tax_id&&<div className="mt-1 text-xs font-semibold">GSTIN / Tax ID: {c.tax_id}</div>}</div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Status</p><div className="mt-2 text-sm font-semibold uppercase">{text(p.status||'')}</div></div></section>
 <table className={`mt-8 w-full border-collapse ${key==='compact'?'text-xs':'text-sm'}`}><thead><tr className={`border-y-2 ${st.rule} ${st.table}`}><th className="px-3 py-3 text-left">Description</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Rate</th><th className="px-3 py-3 text-right">Tax</th><th className="px-3 py-3 text-right">Amount</th></tr></thead><tbody>{items.map((x:any,i:number)=><tr key={i} className="border-b border-slate-200"><td className="px-3 py-3 pr-4">{text(x.description||x.name)}</td><td className="px-3 py-3 text-right">{x.quantity??1}</td><td className="px-3 py-3 text-right">{money(x.unit_price,p.currency_code)}</td><td className="px-3 py-3 text-right">{x.tax_rate??0}%</td><td className="px-3 py-3 text-right font-semibold">{money(x.line_total??(Number(x.quantity||1)*Number(x.unit_price||0)),p.currency_code)}</td></tr>)}</tbody></table>
 <div className={`mt-8 ml-auto w-full max-w-sm space-y-2 border-t-2 ${st.rule} pt-4 text-sm`}><div className="flex justify-between"><span>Subtotal</span><b>{money(p.subtotal,p.currency_code)}</b></div>{Number(p.discount_total)>0&&<div className="flex justify-between"><span>Discount</span><b>-{money(p.discount_total,p.currency_code)}</b></div>}{Number(p.tax_total)>0&&<div className="flex justify-between"><span>Tax</span><b>{money(p.tax_total,p.currency_code)}</b></div>}<div className={`flex justify-between pt-2 text-lg font-bold ${st.accent}`}><span>Total</span><b>{money(total,p.currency_code)}</b></div>{p.balance_due!=null&&<div className="flex justify-between"><span>Balance due</span><b>{money(p.balance_due,p.currency_code)}</b></div>}</div>
 {type==='invoice'&&(showPay||showQr)&&<section className="mt-10 break-inside-avoid rounded-2xl border-2 border-dashed border-violet-200 bg-violet-50/40 p-5"><div className="grid items-center gap-6 sm:grid-cols-[1fr_auto]"><div><p className="text-[10px] font-bold uppercase tracking-wider text-violet-600">ONLINE PAYMENT · PLACEHOLDER</p><h3 className="mt-1 text-xl font-bold">Pay this invoice online</h3><p className="mt-2 text-sm text-slate-500">Outstanding amount: <b className="text-slate-900">{money(balance,p.currency_code)}</b></p>{showPay&&<button disabled className="mt-4 rounded-xl bg-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-600">Pay Now · Payment API pending</button>}</div>{showQr&&<div className="grid h-36 w-36 place-items-center rounded-xl border-2 border-dashed border-slate-300 bg-white text-center text-xs text-slate-400">QR<br/>PLACEHOLDER<br/><span className="text-[9px]">Payment gateway</span></div>}</div></section>}
 {(p.notes||p.terms||cf.footer)&&<section className="mt-10 grid gap-6 border-t border-slate-200 pt-6 sm:grid-cols-2"><div>{p.notes&&<><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Notes</p><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{p.notes}</p></>}</div><div>{(p.terms||cf.footer)&&<><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Terms / Footer</p><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{p.terms||cf.footer}</p></>}</div></section>}
 <footer className="mt-16 border-t border-slate-200 pt-4 text-[10px] text-slate-400 flex justify-between"><span>{text(b.name||'Moneymatters')}</span><span>{text(cf.footer||'Generated from Moneymatters')}</span></footer></>}
 </article></main>;
}

function Receipt({title,number,date,p,b,c,total,cf}:{title:string;number:string;date:string;p:any;b:any;c:any;total:any;cf:any}){return <><header className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-600 text-2xl font-black text-white">✓</div><div className="mt-5 text-3xl font-black text-slate-900">{title.toUpperCase()}</div><div className="mt-1 text-sm text-slate-500">{number} · {date}</div></header><section className="mx-auto mt-10 max-w-xl rounded-3xl border border-slate-200 bg-slate-50 p-8 text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Amount received</p><div className="mt-2 text-5xl font-black text-slate-900">{money(total,p.currency_code)}</div><div className="mt-2 text-sm font-semibold text-emerald-700">Payment received</div></section><section className="mx-auto mt-8 max-w-xl rounded-2xl border border-slate-200 p-6"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Received from</p><b className="mt-1 block">{text(c.display_name||c.legal_name||'')}</b><span className="text-xs text-slate-500">{c.email||''}{c.phone?` · ${c.phone}`:''}</span></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Business</p><b className="mt-1 block">{text(b.name||b.legal_name||'Business')}</b><span className="text-xs text-slate-500">Payment received by this business</span></div></div><div className="mt-6 border-t border-slate-200 pt-5 grid gap-3 text-sm"><div className="flex justify-between"><span>Against invoice</span><b>{text(p.invoice_number||'—')}</b></div><div className="flex justify-between"><span>Payment method</span><b>{text(p.payment_method||p.method||'Payment received')}</b></div><div className="flex justify-between"><span>Reference</span><b>{text(p.payment_reference||p.reference||'—')}</b></div></div></section><section className="mx-auto mt-8 max-w-xl text-center text-xs text-slate-500">{cf.notes||'Thank you for your payment.'}</section><footer className="mt-16 border-t border-slate-200 pt-4 text-center text-[10px] text-slate-400">{cf.footer||'This receipt confirms payment received.'}</footer></>}

export default function DocumentsPage(){return <Suspense fallback={<div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-slate-500">Preparing document…</div>}><DocumentsContent/></Suspense>}
