'use client';

import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';

type Job={id:string;document_type:string;document_id:string;template_id:string|null;template_version:number|null;payload:any;status:string};
type Template={template_key:string;template_name:string};

type TemplateMeta={
  name:string;
  description:string;
  header:string;
  table:string;
  rule:string;
  accent:string;
  shell:string;
};

const money=(n:any,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:String(c||'INR').trim(),maximumFractionDigits:2}).format(Number(n||0));
const text=(v:any)=>String(v??'');
const safeAddress=(v:any)=>{if(!v)return [];if(typeof v==='string')return v.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(typeof v==='object')return [v.line1,v.line2,v.city,v.state,v.postal_code,v.country].filter(Boolean).map(String);return [String(v)]};

const templates:Record<string,TemplateMeta>={
  classic:{name:'Professional',description:'Clean business document with a strong hierarchy.',header:'',table:'bg-slate-800 text-white',rule:'border-slate-800',accent:'text-slate-900',shell:'border border-slate-200'},
  bold:{name:'Classic Business',description:'Traditional business invoice with a strong header band.',header:'bg-slate-900 text-white',table:'bg-slate-700 text-white',rule:'border-slate-900',accent:'text-slate-900',shell:'border border-slate-200'},
  modern:{name:'Modern',description:'Contemporary layout with a restrained Moneymatters accent.',header:'bg-violet-50 text-slate-900',table:'bg-violet-600 text-white',rule:'border-violet-600',accent:'text-violet-700',shell:'border border-violet-100'},
  minimal:{name:'Minimal',description:'Lightweight, highly readable document with minimal decoration.',header:'',table:'bg-slate-100 text-slate-700',rule:'border-slate-300',accent:'text-slate-800',shell:'border border-slate-200'},
  compact:{name:'Premium',description:'Structured premium layout for information-dense invoices.',header:'bg-slate-950 text-white',table:'bg-slate-950 text-white',rule:'border-slate-950',accent:'text-slate-950',shell:'border border-slate-200'},
};

function Address({value,className=''}:{value:any;className?:string}){return <div className={`space-y-0.5 ${className}`}>{safeAddress(value).map((x,i)=><div key={i}>{x}</div>)}</div>}
function BrandLogo({business}:{business:any}){const src=business?.logo_url||business?.logo||business?.logo_storage_url;return <div className="flex min-h-16 min-w-32 items-center">{src?<img src={src} alt={text(business?.name||'Business')} className="max-h-16 max-w-44 object-contain"/>:<div><div className="text-2xl font-black tracking-tight">{text(business?.name||business?.legal_name||'Business')}</div><div className="mt-1 text-[10px] uppercase tracking-[.18em] opacity-60">Business</div></div>}</div>}

function Totals({p,st,total}:{p:any;st:TemplateMeta;total:any}){return <div className={`ml-auto w-full max-w-sm border-t-2 ${st.rule} pt-4 text-sm`}><div className="space-y-2"><div className="flex justify-between"><span>Subtotal</span><b>{money(p.subtotal,p.currency_code)}</b></div>{Number(p.discount_total)>0&&<div className="flex justify-between"><span>Discount</span><b>-{money(p.discount_total,p.currency_code)}</b></div>}{Number(p.tax_total)>0&&<div className="flex justify-between"><span>Tax</span><b>{money(p.tax_total,p.currency_code)}</b></div>}<div className={`mt-2 flex justify-between border-t ${st.rule} pt-3 text-lg font-bold ${st.accent}`}><span>Total</span><b>{money(total,p.currency_code)}</b></div>{p.amount_paid!=null&&<div className="flex justify-between"><span>Amount paid</span><b>{money(p.amount_paid,p.currency_code)}</b></div>}{p.balance_due!=null&&<div className="flex justify-between font-semibold"><span>Amount due</span><b>{money(p.balance_due,p.currency_code)}</b></div>}</div></div>}

function PaymentBlock({p,cf,balance}:{p:any;cf:any;balance:number}){const showPay=cf.show_pay_now??true;const showQr=cf.show_payment_qr??true;if(!showPay&&!showQr)return null;return <section className="mt-8 break-inside-avoid rounded-2xl border-2 border-dashed border-violet-200 bg-violet-50/50 p-5"><div className="grid items-center gap-6 sm:grid-cols-[1fr_auto]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-600">Payment options</p><h3 className="mt-1 text-lg font-bold text-slate-900">Pay this invoice online</h3><p className="mt-1 text-xs text-slate-500">Amount due: <b className="text-slate-900">{money(balance,p.currency_code)}</b></p>{showPay&&<button disabled className="mt-3 rounded-xl bg-slate-300 px-5 py-2.5 text-xs font-bold text-slate-600">Pay Now · Gateway placeholder</button>}</div>{showQr&&<div className="grid h-28 w-28 place-items-center rounded-xl border-2 border-dashed border-slate-300 bg-white text-center text-[10px] font-semibold text-slate-400">QR<br/>PLACEHOLDER<div className="text-[8px] font-normal">Payment gateway</div></div>}</div></section>}

function InvoiceDocument({p,b,c,items,st,key,type,cf,total,balance}:{p:any;b:any;c:any;items:any[];st:TemplateMeta;key:string;type:string;cf:any;total:any;balance:number}){
 const businessLines=safeAddress(b.address||b.business_address);const customerLines=safeAddress(c.address||c.billing_address);const gst=type==='invoice'&&(Number(p.tax_total)>0||!!b.tax_registration_number);const title=type==='invoice'?(gst?'TAX INVOICE':'INVOICE'):type==='quotation'?'ESTIMATE':type==='credit_note'?'CREDIT NOTE':'DEBIT NOTE';const number=p.invoice_number||p.quotation_number||p.credit_note_number||p.debit_note_number||'';const date=p.invoice_date||p.quotation_date||p.credit_note_date||p.debit_note_date||'';
 const meta=<div className="space-y-1 text-xs"><div><span className="text-slate-400">Number</span><b className="ml-2">{number}</b></div><div><span className="text-slate-400">Issue date</span><b className="ml-2">{date}</b></div>{p.due_date&&<div><span className="text-slate-400">Due date</span><b className="ml-2">{p.due_date}</b></div>}{p.po_number&&<div><span className="text-slate-400">PO / Ref.</span><b className="ml-2">{p.po_number}</b></div>}</div>;
 const header=<header className={`rounded-2xl p-6 ${st.header} ${key==='classic'?'border-b-2 border-slate-900':key==='minimal'?'border-b border-slate-200':''}`}><div className="flex items-start justify-between gap-8"><div><BrandLogo business={b}/><div className="mt-3 text-xs leading-5 opacity-75">{businessLines.map((x,i)=><div key={i}>{x}</div>)}</div><div className="mt-2 space-y-0.5 text-xs opacity-75"><div>{b.phone||''}</div><div>{b.email||''}</div>{b.website&&<div>{b.website}</div>}{b.tax_registration_number&&<div className="font-semibold opacity-100">GSTIN / Tax ID: {b.tax_registration_number}</div>}</div></div><div className="text-right"><div className={`text-3xl font-black tracking-tight ${key==='modern'?'text-violet-700':''}`}>{text(cf.title||title)}</div>{cf.subheading&&<div className="mt-1 text-xs opacity-70">{text(cf.subheading)}</div>}<div className="mt-4">{meta}</div></div></div></header>;
 const bill=<section className="mt-7 grid gap-6 sm:grid-cols-[1.15fr_.85fr]"><div className={`rounded-xl p-4 ${key==='minimal'?'border border-slate-200':'bg-slate-50'}`}><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Bill to</p><div className="mt-2 text-base font-bold text-slate-900">{text(c.display_name||c.legal_name||'Customer')}</div>{customerLines.length>0&&<Address value={c.address||c.billing_address} className="mt-1 text-xs leading-5 text-slate-600"/>}<div className="mt-2 space-y-0.5 text-xs text-slate-500"><div>{c.phone||''}</div><div>{c.email||''}</div>{c.tax_id&&<div className="font-semibold text-slate-700">GSTIN / Tax ID: {c.tax_id}</div>}</div></div><div className={`rounded-xl p-4 ${key==='minimal'?'border border-slate-200':'bg-slate-50'}`}><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Invoice summary</p><div className="mt-3 grid gap-2 text-xs"><div className="flex justify-between"><span>Document</span><b>{title}</b></div><div className="flex justify-between"><span>Status</span><b className="uppercase">{text(p.status||'Draft')}</b></div>{p.payment_terms&&<div className="flex justify-between gap-4"><span>Payment terms</span><b className="text-right">{p.payment_terms}</b></div>}</div></div></section>;
 return <><article className={`mx-auto min-h-[1120px] max-w-[900px] bg-white p-8 shadow-xl print:min-h-0 print:max-w-none print:p-10 print:shadow-none ${st.shell}`} style={{fontFamily:'Arial,sans-serif'}}>{header}{bill}<table className={`mt-8 w-full border-collapse ${key==='compact'?'text-xs':'text-sm'}`}><thead><tr className={`border-y-2 ${st.rule} ${st.table}`}><th className="px-3 py-3 text-left">Item / Description</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Rate</th>{Number(p.tax_total)>0&&<th className="px-3 py-3 text-right">Tax</th>}<th className="px-3 py-3 text-right">Amount</th></tr></thead><tbody>{items.map((x:any,i:number)=><tr key={i} className="border-b border-slate-200 align-top"><td className="px-3 py-3 pr-5"><div className="font-semibold text-slate-800">{text(x.name||x.description)}</div>{x.description&&x.name&&<div className="mt-1 text-xs text-slate-500">{text(x.description)}</div>}{x.sku&&<div className="mt-1 text-[10px] text-slate-400">SKU: {x.sku}</div>}</td><td className="px-3 py-3 text-right">{x.quantity??1}{x.unit?` ${x.unit}`:''}</td><td className="px-3 py-3 text-right">{money(x.unit_price,p.currency_code)}</td>{Number(p.tax_total)>0&&<td className="px-3 py-3 text-right">{x.tax_rate??0}%</td>}<td className="px-3 py-3 text-right font-semibold">{money(x.line_total??(Number(x.quantity||1)*Number(x.unit_price||0)),p.currency_code)}</td></tr>)}</tbody></table><div className="mt-7"><Totals p={p} st={st} total={total}/></div>{type==='invoice'&&<PaymentBlock p={p} cf={cf} balance={balance}/>}<section className="mt-9 grid gap-6 border-t border-slate-200 pt-6 sm:grid-cols-[1fr_.9fr]"><div>{p.notes&&<><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Notes</p><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{p.notes}</p></>}</div><div>{(p.terms||cf.footer)&&<><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Terms & conditions</p><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{p.terms||cf.footer}</p></>}</div></section><footer className="mt-14 flex justify-between border-t border-slate-200 pt-4 text-[10px] text-slate-400"><span>{text(b.name||b.legal_name||'Business')}</span><span>{text(cf.footer||'This is a computer generated document.')}</span></footer></article></>;
}

function Receipt({title,number,date,p,b,c,total,cf}:{title:string;number:string;date:string;p:any;b:any;c:any;total:any;cf:any}){return <article className="mx-auto min-h-[1120px] max-w-[900px] bg-white p-10 shadow-xl print:min-h-0 print:max-w-none print:p-10 print:shadow-none" style={{fontFamily:'Arial,sans-serif'}}><header className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-600 text-2xl font-black text-white">✓</div><div className="mt-5 text-3xl font-black text-slate-900">{title.toUpperCase()}</div><div className="mt-1 text-sm text-slate-500">{number} · {date}</div></header><section className="mx-auto mt-10 max-w-xl rounded-3xl border border-slate-200 bg-slate-50 p-8 text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Amount received</p><div className="mt-2 text-5xl font-black text-slate-900">{money(total,p.currency_code)}</div><div className="mt-2 text-sm font-semibold text-emerald-700">Payment received</div></section><section className="mx-auto mt-8 max-w-xl rounded-2xl border border-slate-200 p-6"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Received from</p><b className="mt-1 block">{text(c.display_name||c.legal_name||'')}</b><span className="text-xs text-slate-500">{c.email||''}{c.phone?` · ${c.phone}`:''}</span></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Business</p><b className="mt-1 block">{text(b.name||b.legal_name||'Business')}</b><span className="text-xs text-slate-500">Payment received by this business</span></div></div><div className="mt-6 grid gap-3 border-t border-slate-200 pt-5 text-sm"><div className="flex justify-between"><span>Against invoice</span><b>{text(p.invoice_number||'—')}</b></div><div className="flex justify-between"><span>Payment method</span><b>{text(p.payment_method||p.method||'Payment received')}</b></div><div className="flex justify-between"><span>Reference</span><b>{text(p.payment_reference||p.reference||'—')}</b></div></div></section><section className="mx-auto mt-8 max-w-xl text-center text-xs text-slate-500">{cf.notes||'Thank you for your payment.'}</section><footer className="mt-16 border-t border-slate-200 pt-4 text-center text-[10px] text-slate-400">{cf.footer||'This receipt confirms payment received.'}</footer></article>}

function DocumentsContent(){
 const qs=useSearchParams();const type=qs.get('type')||'invoice';const id=qs.get('id')||'';const[job,setJob]=useState<Job|null>(null),[template,setTemplate]=useState<Template|null>(null),[docPref,setDocPref]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!id){setError('Document id is required.');setLoading(false);return}const r=await supabase.rpc('prepare_document_render',{p_document_type:type,p_document_id:id,p_template_id:null});if(r.error){setError(r.error.message);setLoading(false);return}const j=await supabase.from('document_render_jobs').select('id,document_type,document_id,template_id,template_version,payload,status').eq('id',r.data).single();if(j.error){setError(j.error.message);setLoading(false);return}setJob(j.data as Job);if(j.data?.template_id){const t=await supabase.from('document_templates').select('template_key,template_name').eq('id',j.data.template_id).maybeSingle();setTemplate(t.data as Template|null)}const b=j.data?.payload?.business?.id||j.data?.payload?.business_id;const p=await supabase.from('business_document_preferences').select('custom_fields,show_payment_qr,show_payment_link').eq('business_id',b).eq('document_type',type).maybeSingle();setDocPref(p.data||null);setLoading(false)})()},[type,id]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-slate-500">Preparing document…</div>;
 if(error)return <div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-rose-600">{error}</div>;
 const p=job?.payload||{},b=p.business||{},c=p.customer||{},items=p.items||[];const key=template?.template_key||'classic';const st=templates[key]||templates.classic;const cf=docPref?.custom_fields||{};const total=p.total??p.amount??0;const balance=Number(p.balance_due??total);const isReceipt=type==='receipt';const title=type==='invoice'?(Number(p.tax_total)>0||!!b.tax_registration_number?'TAX INVOICE':'INVOICE'):type==='quotation'?'ESTIMATE':type==='receipt'?'PAYMENT RECEIPT':type==='credit_note'?'CREDIT NOTE':'DEBIT NOTE';const number=p.invoice_number||p.quotation_number||p.receipt_number||p.credit_note_number||p.debit_note_number||'';const date=p.invoice_date||p.quotation_date||p.receipt_date||p.credit_note_date||p.debit_note_date||'';
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="mx-auto mb-4 flex max-w-[900px] items-center justify-between print:hidden"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Document center</p><h1 className="mt-1 text-xl font-semibold">{title} {number}</h1><p className="text-xs text-slate-500">{templates[key]?.name||template?.template_name||'Professional'} · Template v{job?.template_version||1} · Print-ready</p></div><div className="flex gap-2"><button onClick={()=>history.back()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Back</button><button onClick={()=>window.print()} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Print / Save PDF</button></div></div>{isReceipt?<Receipt title={text(cf.title||title)} number={number} date={date} p={p} b={b} c={c} total={total} cf={cf}/>:<InvoiceDocument p={p} b={b} c={c} items={items} st={st} key={key} type={type} cf={cf} total={total} balance={balance}/>}</main>;
}

export default function DocumentsPage(){return <Suspense fallback={<div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-slate-500">Preparing document…</div>}><DocumentsContent/></Suspense>}
