'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';
import { Alert, Button, Card, EmptyState, Field, FormSection, Input, MoneyInput, PageHeader, SearchInput, Select } from '@/components/moneymatters';
type Payment={id:string;payment_date:string;amount:number;method:string;reference:string|null;direction:string;invoice_id:string|null;customer_id:string|null;vendor_id:string|null};
type Customer={id:string;display_name:string}; type Invoice={id:string;invoice_number:string;balance_due:number;customer_id:string}; type Account={id:string;name:string;code:string};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
export default function Payments(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[rows,setRows]=useState<Payment[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[q,setQ]=useState(''),[direction,setDirection]=useState('all'),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[customerId,setCustomerId]=useState(''),[invoiceId,setInvoiceId]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('upi'),[accountId,setAccountId]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[receiptId,setReceiptId]=useState<string|null>(null);
 const load=async(b:BusinessContext)=>{const[p,cu,i,a]=await Promise.all([supabase.from('payments').select('id,payment_date,amount,method,reference,direction,invoice_id,customer_id,vendor_id').eq('business_id',b.business_id).order('payment_date',{ascending:false}).limit(200),supabase.from('customers').select('id,display_name').eq('business_id',b.business_id).eq('is_active',true).order('display_name'),supabase.from('invoices').select('id,invoice_number,balance_due,customer_id').eq('business_id',b.business_id).in('status',['sent','partially_paid','overdue']).order('invoice_date',{ascending:false}),supabase.from('accounts').select('id,name,code').eq('business_id',b.business_id).eq('is_active',true).order('code')]);setRows((p.data||[]) as Payment[]);setCustomers((cu.data||[]) as Customer[]);setInvoices((i.data||[]) as Invoice[]);setAccounts((a.data||[]) as Account[]);if(a.data?.length&&!accountId)setAccountId(a.data.find((x:any)=>x.code==='1000')?.id||a.data[0].id)};
 useEffect(()=>{(async()=>{const c=await supabase.rpc('get_my_business_context');const b=c.data?.[0] as BusinessContext|undefined;if(!b){location.href='/';return}setCtx(b);await load(b);setLoading(false)})()},[]);
 const customer=(id:string|null)=>customers.find(x=>x.id===id)?.display_name||'Business transaction'; const invoice=(id:string|null)=>invoices.find(x=>x.id===id)?.invoice_number||'—';
 const filtered=useMemo(()=>rows.filter(x=>(direction==='all'||x.direction===direction)&&`${customer(x.customer_id)} ${x.reference||''} ${x.method} ${invoice(x.invoice_id)}`.toLowerCase().includes(q.toLowerCase())),[rows,customers,invoices,q,direction]);
 const inbound=rows.filter(x=>x.direction==='inbound').reduce((a,x)=>a+Number(x.amount||0),0),outbound=rows.filter(x=>x.direction==='outbound').reduce((a,x)=>a+Number(x.amount||0),0); const customerInvoices=invoices.filter(i=>i.customer_id===customerId&&Number(i.balance_due)>0);
 const reset=()=>{setShow(false);setCustomerId('');setInvoiceId('');setAmount('');setReference('');setError('');setReceiptId(null)};
 const record=async()=>{if(!ctx||!customerId||!invoiceId||!accountId||Number(amount)<=0)return;const selected=invoices.find(i=>i.id===invoiceId);if(selected&&Number(amount)>Number(selected.balance_due)){setError(`Payment cannot exceed the outstanding balance of ${money(selected.balance_due)}.`);return}setBusy(true);setError('');setSuccess('');const r=await supabase.rpc('record_customer_payment',{p_business_id:ctx.business_id,p_customer_id:customerId,p_invoice_id:invoiceId,p_amount:Number(amount),p_method:method,p_account_id:accountId,p_reference:reference||null,p_payment_date:new Date().toISOString().slice(0,10),p_notes:'Recorded from Payments center'});if(r.error){setError(r.error.message)}else{const paymentId=typeof r.data==='string'?r.data:null;let rid:string|null=null;if(paymentId){const rr=await supabase.from('receipts').select('id').eq('business_id',ctx.business_id).eq('payment_id',paymentId).maybeSingle();rid=rr.data?.id||null}setReceiptId(rid);setSuccess('Payment recorded. The invoice balance, receipt and accounting entry have been updated.');setShow(false);setCustomerId('');setInvoiceId('');setAmount('');setReference('');await load(ctx)}setBusy(false)};
 if(loading)return <div className="grid min-h-[70vh] place-items-center text-sm text-slate-500">Loading payments…</div>;
 return <main className="min-h-[calc(100vh-100px)] bg-[#fbfaff] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1250px]">
  <PageHeader eyebrow="Money in & out" title="Payments" description="Record, track and reconcile money movement without manually posting journals." actions={<Button onClick={()=>{setShow(true);setError('');setSuccess('');setReceiptId(null)}}>＋ Record payment</Button>}/>
  {error&&<div className="mb-5"><Alert tone="error" title="Payment could not be recorded">{error}</Alert></div>}
  {success&&<div className="mb-5"><Alert tone="success" title="Payment recorded successfully">{success}<div className="mt-3 flex flex-wrap gap-2">{receiptId&&<Button size="sm" onClick={()=>location.href=`/next-workspace/documents?type=receipt&id=${receiptId}`}>View receipt</Button>}<Button size="sm" variant="secondary" onClick={()=>setSuccess('')}>Dismiss</Button></div></Alert></div>}
  {show&&<FormSection className="mb-6" title="Record customer payment" description="The existing accounting RPC updates the invoice balance, receipt and ledger entry together." actions={<Button variant="ghost" size="sm" aria-label="Close payment form" onClick={reset}>×</Button>}>
   <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Customer" required><Select value={customerId} onChange={e=>{setCustomerId(e.target.value);setInvoiceId('')}}><option value="">Select customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</Select></Field><Field label="Invoice" required><Select value={invoiceId} onChange={e=>{setInvoiceId(e.target.value);const i=invoices.find(x=>x.id===e.target.value);if(i)setAmount(String(i.balance_due))}} disabled={!customerId}><option value="">Select invoice…</option>{customerInvoices.map(i=><option key={i.id} value={i.id}>{i.invoice_number} · {money(i.balance_due)} due</option>)}</Select></Field><Field label="Amount" required help={invoiceId?`Outstanding: ${money(invoices.find(i=>i.id===invoiceId)?.balance_due||0)}`:undefined}><MoneyInput value={amount} onChange={e=>setAmount(e.target.value)} aria-label="Payment amount"/></Field><Field label="Method" required><Select value={method} onChange={e=>setMethod(e.target.value)}><option value="upi">UPI</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="payment_gateway">Payment gateway</option><option value="other">Other</option></Select></Field></div>
   <div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Deposit account" required><Select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Select account…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select></Field><Field label="Reference" help="UPI, bank or cheque reference (optional)"><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter reference" /></Field></div>
   <div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={reset}>Cancel</Button><Button disabled={busy||!customerId||!invoiceId||!accountId||Number(amount)<=0} onClick={record}>{busy?'Recording…':'Record payment'}</Button></div>
  </FormSection>}
  <div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Received</span><b className="mt-3 block text-2xl">{money(inbound)}</b><span className="text-xs text-slate-400">Customer payments</span></Card><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Paid out</span><b className="mt-3 block text-2xl">{money(outbound)}</b><span className="text-xs text-slate-400">Vendor payments</span></Card><Card className="p-5"><span className="text-xs font-semibold text-slate-500">Net movement</span><b className="mt-3 block text-2xl">{money(inbound-outbound)}</b><span className="text-xs text-slate-400">Recorded payments</span></Card></div>
  <Card className="mt-6 overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Search payments…"/><Select value={direction} onChange={e=>setDirection(e.target.value)} className="sm:w-44"><option value="all">All payments</option><option value="inbound">Received</option><option value="outbound">Paid</option></Select></div><div className="hidden grid-cols-[120px_1fr_150px_130px_130px] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>Date</span><span>Customer / Vendor</span><span>Invoice</span><span>Method</span><span className="text-right">Amount</span></div><div className="divide-y divide-slate-100">{filtered.map(p=><div key={p.id} className="grid gap-2 px-4 py-4 sm:grid-cols-[120px_1fr_150px_130px_130px] sm:items-center sm:px-5"><span className="text-xs text-slate-500">{p.payment_date}</span><span><b className="block text-sm">{customer(p.customer_id||p.vendor_id)}</b><span className="text-xs text-slate-400">{p.reference||'No reference'}</span></span><span className="text-sm font-medium">{invoice(p.invoice_id)}</span><span className="text-xs capitalize text-slate-500">{String(p.method).replaceAll('_',' ')}</span><b className={`text-sm sm:text-right ${p.direction==='inbound'?'text-emerald-700':'text-slate-800'}`}>{p.direction==='inbound'?'+':'−'}{money(p.amount)}</b></div>)}{!filtered.length&&<div className="p-12"><EmptyState title="No payments found" description="Try another search or change the direction filter."/></div>}</div></Card>
 </div></main>;
}
