import type { CanonicalInvoice } from '../canonical';
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const dec=(v:number)=>Number(v||0).toFixed(2);
export const FACTUR_X_GUIDELINE='urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:en16931';

export function serializeFacturXCii(inv:CanonicalInvoice){
  if(!inv.number||!/^\d{4}-\d{2}-\d{2}$/.test(inv.issueDate)) throw new Error('Factur-X requires invoice number and issue date.');
  const lines=inv.lines.map((l)=>`<ram:IncludedSupplyChainTradeLineItem><ram:AssociatedDocumentLineDocument><ram:LineID>${esc(l.id)}</ram:LineID></ram:AssociatedDocumentLineDocument><ram:SpecifiedTradeProduct><ram:Name>${esc(l.description)}</ram:Name></ram:SpecifiedTradeProduct><ram:SpecifiedLineTradeAgreement><ram:NetPriceProductTradePrice><ram:ChargeAmount>${dec(l.unitPrice)}</ram:ChargeAmount></ram:NetPriceProductTradePrice></ram:SpecifiedLineTradeAgreement><ram:SpecifiedLineTradeDelivery><ram:BilledQuantity>${dec(l.quantity)}</ram:BilledQuantity></ram:SpecifiedLineTradeDelivery><ram:SpecifiedLineTradeSettlement><ram:ApplicableTradeTax><ram:TypeCode>VAT</ram:TypeCode><ram:CategoryCode>${l.taxCategory==='ZERO_RATED'?'Z':l.taxCategory==='EXEMPT'?'E':l.taxCategory==='REVERSE_CHARGE'?'AE':'S'}</ram:CategoryCode><ram:RateApplicablePercent>${dec(l.taxRate||0)}</ram:RateApplicablePercent></ram:ApplicableTradeTax><ram:SpecifiedTradeSettlementLineMonetarySummation><ram:LineTotalAmount>${dec(l.netAmount)}</ram:LineTotalAmount></ram:SpecifiedTradeSettlementLineMonetarySummation></ram:SpecifiedLineTradeSettlement></ram:IncludedSupplyChainTradeLineItem>`).join('');
  const taxes=inv.taxLines.map((t)=>`<ram:ApplicableTradeTax><ram:CalculatedAmount>${dec(t.taxAmount)}</ram:CalculatedAmount><ram:TypeCode>VAT</ram:TypeCode><ram:BasisAmount>${dec(t.taxableAmount)}</ram:BasisAmount><ram:CategoryCode>${t.taxCategory==='ZERO_RATED'?'Z':t.taxCategory==='EXEMPT'?'E':t.taxCategory==='REVERSE_CHARGE'?'AE':'S'}</ram:CategoryCode><ram:RateApplicablePercent>${dec(t.rate)}</ram:RateApplicablePercent></ram:ApplicableTradeTax>`).join('');
  return `<?xml version="1.0" encoding="UTF-8"?><rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100"><rsm:ExchangedDocumentContext><ram:GuidelineSpecifiedDocumentContextParameter><ram:ID>${FACTUR_X_GUIDELINE}</ram:ID></ram:GuidelineSpecifiedDocumentContextParameter></rsm:ExchangedDocumentContext><rsm:ExchangedDocument><ram:ID>${esc(inv.number)}</ram:ID><ram:TypeCode>380</ram:TypeCode><ram:IssueDateTime><udt:DateTimeString format="102">${inv.issueDate.replaceAll('-','')}</udt:DateTimeString></ram:IssueDateTime></rsm:ExchangedDocument><rsm:SupplyChainTradeTransaction><ram:ApplicableHeaderTradeAgreement><ram:SellerTradeParty><ram:Name>${esc(inv.supplier.name)}</ram:Name><ram:PostalTradeAddress><ram:CountryID>${esc(inv.supplier.address.country_code)}</ram:CountryID><ram:PostcodeCode>${esc(inv.supplier.address.postal_code||'')}</ram:PostcodeCode><ram:CityName>${esc(inv.supplier.address.locality||'')}</ram:CityName><ram:LineOne>${esc(inv.supplier.address.address_line_1||'')}</ram:LineOne></ram:PostalTradeAddress></ram:SellerTradeParty><ram:BuyerTradeParty><ram:Name>${esc(inv.customer.name)}</ram:Name><ram:PostalTradeAddress><ram:CountryID>${esc(inv.customer.address.country_code)}</ram:CountryID><ram:PostcodeCode>${esc(inv.customer.address.postal_code||'')}</ram:PostcodeCode><ram:CityName>${esc(inv.customer.address.locality||'')}</ram:CityName><ram:LineOne>${esc(inv.customer.address.address_line_1||'')}</ram:LineOne></ram:PostalTradeAddress></ram:BuyerTradeParty></ram:ApplicableHeaderTradeAgreement><ram:ApplicableHeaderTradeDelivery></ram:ApplicableHeaderTradeDelivery><ram:ApplicableHeaderTradeSettlement><ram:InvoiceCurrencyCode>${esc(inv.currencyCode)}</ram:InvoiceCurrencyCode>${taxes}<ram:SpecifiedTradeSettlementHeaderMonetarySummation><ram:LineTotalAmount>${dec(inv.lines.reduce((s,l)=>s+l.netAmount,0))}</ram:LineTotalAmount><ram:TaxBasisTotalAmount>${dec(inv.total-inv.taxTotal)}</ram:TaxBasisTotalAmount><ram:TaxTotalAmount currencyID="${esc(inv.currencyCode)}">${dec(inv.taxTotal)}</ram:TaxTotalAmount><ram:GrandTotalAmount>${dec(inv.total)}</ram:GrandTotalAmount><ram:DuePayableAmount>${dec(inv.balanceDue)}</ram:DuePayableAmount></ram:SpecifiedTradeSettlementHeaderMonetarySummation></ram:ApplicableHeaderTradeSettlement>${lines}</ram:SupplyChainTradeTransaction></rsm:CrossIndustryInvoice>`;
}

export function validateFacturXCii(xml:string){
  for(const marker of ['<rsm:CrossIndustryInvoice','<ram:GuidelineSpecifiedDocumentContextParameter>','<ram:SellerTradeParty>','<ram:BuyerTradeParty>','<ram:ApplicableTradeTax>','<ram:SpecifiedTradeSettlementHeaderMonetarySummation>']) if(!xml.includes(marker)) throw new Error('CII validation failed: missing '+marker);
  if(!xml.includes(FACTUR_X_GUIDELINE)) throw new Error('CII validation failed: wrong Factur-X EN16931 guideline.');
  return xml;
}