'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.045)] ${className}`}>{children}</section>;
const startFY=()=>{const d=new Date();return new Date(d.getMonth()>=3?d.getFullYear():d.getFullYear()-1,3,1).toISOString().slice(0,10)};

type Invoice={total:number;balance_due:number;status:string;invoice_date:string;tax_total:number};
type Expense={amount:number;tax_amount:number;expense_date:string;description:string};
type Payment={amount:number;direction:string;payment_date:string;method:string};

export default function Reports(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[invoices,setInvoices]=useState<Invoice[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const r=await supabase.rpc('get_my_business_context');const c=r.data?.[0] as BusinessContext|undefined;if(!c){location.href='/';return}setCtx(c);const fy=startFY();const[a,b,p]=await Promise.all([supabase.from('invoices').select('total,balance_due,status,invoice_date,tax_total').eq('business_id',c.business_id).gte('invoice_date',fy),supabase.from('expenses').select('amount,tax_amount,expense_date,description').eq('business_id',c.business_id).gte('expense_date',fy),supabase.from('payments').select('amount,direction,payment_date,method').eq('business_id',c.business_id).gte('payment_date',fy)]);if(a.error||b.error||p.error)setError((a.error||b.error||p.error)?.message||'Unable to load reports');setInvoices(a.data||[]);setExpenses(b.data||[]);setPayments(p.data||[]);setLoading(false)})()},[]);
 const m=useMemo(()=>{const sales=invoices.filter(x=>!['draft','void'].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);const tax=invoices.filter(x=>!['draft','void'].includes(x.status)).reduce((s,x)=>s+Number(x.tax_total||0),0);const exp=expenses.reduce((s,x)=>s+Number(x.amount||0),0);const receivable=invoices.filter(x=>!['paid','void','draft'].includes(x.status)).reduce((s,x)=>s+Number(x.balance_due||0),0);const inMoney=payments.filter(x=>x.direction==='in').reduce((s,x)=>s+Number(x.amount||0),0);const outMoney=payments.filter(x=>x.direction==='out').reduce((s,x)=>s+Number(x.amount||0),0);return{sales,tax,exp,receivable,inMoney,outMoney,profit:sales-exp}},[invoices,expenses,payments]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Preparing reports…</div>;
 if(!ctx)return null;
 return <main className="min-h-screen bg-[#f5f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Business intelligence</p><h1 className="mt-1 text-3xl font-semibold">Reports</h1><p className="mt-1 text-sm text-slate-500">Simple business answers first; accounting detail remains available underneath.</p></div><button onClick={()=>location.href='/next-workspace'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Cockpit</button></header>{error&&<div className="mb-5 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Sales" value={money(m.sales)} note="Posted invoices · current FY"/><Metric title="Expenses" value={money(m.exp)} note="Recorded expenses" tone="amber"/><Metric title="Profit*" value={money(m.profit)} note="Sales less recorded expenses" tone={m.profit>=0?'green':'red'}/><Metric title="Receivable" value={money(m.receivable)} note="Open customer balances" tone="blue"/></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Profit & Loss snapshot</h2><p className="mt-1 text-xs text-slate-400">Current financial year · starting April.</p><div className="mt-5 space-y-3"><Line label="Sales" value={m.sales}/><Line label="Expenses" value={-m.exp}/><div className="border-t border-slate-200 pt-3"><Line label="Net operating result" value={m.profit} strong/></div></div><p className="mt-5 text-[11px] leading-5 text-slate-400">*This is a management snapshot from posted sales and recorded expenses. Final financial statements should use the complete ledger and year-end adjustments.</p></Card><Card className="p-6"><h2 className="font-semibold">Cash movement</h2><p className="mt-1 text-xs text-slate-400">Recorded customer/vendor/payment activity.</p><div className="mt-5 space-y-3"><Line label="Money received" value={m.inMoney}/><Line label="Money paid" value={-m.outMoney}/><div className="border-t border-slate-200 pt-3"><Line label="Net recorded movement" value={m.inMoney-m.outMoney} strong/></div></div></Card></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="p-6"><h2 className="font-semibold">Tax visibility</h2><div className="mt-4 grid grid-cols-2 gap-3"><Mini label="Output tax on sales" value={m.tax}/><Mini label="Expense tax recorded" value={expenses.reduce((s,x)=>s+Number(x.tax_amount||0),0)}/></div><button onClick={()=>location.href='/next-workspace/tax'} className="mt-5 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white">Open Tax & ITR centre →</button></Card><Card className="p-6"><h2 className="font-semibold">Drill-down reports</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{['General Ledger','Trial Balance','Balance Sheet','Receivables','Payables','Bank Reconciliation','Sales Register','Expense Register'].map(x=><button key={x} onClick={()=>location.href='/next-workspace/accounting'} className="rounded-xl border border-slate-200 px-3 py-3 text-left text-xs font-semibold hover:bg-slate-50">{x} <span className="float-right text-slate-400">→</span></button>)}</div></Card></div></div></main>
}
function Metric({title,value,note,tone='blue'}:{title:string;value:string;note:string;tone?:'blue'|'amber'|'green'|'red'}){const c={blue:'bg-blue-50 text-blue-700',amber:'bg-amber-50 text-amber-700',green:'bg-emerald-50 text-emerald-700',red:'bg-rose-50 text-rose-700'};return <Card className="p-5"><span className={`inline-flex rounded-xl px-2 py-1 text-[10px] font-bold ${c[tone]}`}>{title}</span><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></Card>}
function Line({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between gap-3 ${strong?'font-semibold':''}`}><span className="text-sm">{label}</span><span className={value<0?'text-rose-600':''}>{money(value)}</span></div>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold">{money(value)}</p></div>}
