'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,type BusinessContext} from '@/lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.045)] ${className}`}>{children}</section>;
const startFY=()=>{const d=new Date();return new Date(d.getMonth()>=3?d.getFullYear():d.getFullYear()-1,3,1).toISOString().slice(0,10)};

type Invoice={id:string;invoice_number:string;total:number;balance_due:number;status:string;invoice_date:string;tax_total:number;customer_id:string|null};
type Expense={id:string;amount:number;tax_amount:number;expense_date:string;description:string;vendor_id?:string|null};
type Payment={id:string;amount:number;direction:string;payment_date:string;method:string;reference:string|null;invoice_id:string|null;customer_id:string|null};

type ReportKey='sales'|'expenses'|'receivables'|'payments'|'tax';

export default function Reports(){
 const[ctx,setCtx]=useState<BusinessContext|null>(null),[invoices,setInvoices]=useState<Invoice[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[report,setReport]=useState<ReportKey>('sales'),[q,setQ]=useState(''),[from,setFrom]=useState(startFY()),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 useEffect(()=>{(async()=>{const r=await supabase.rpc('get_my_business_context');const c=r.data?.[0] as BusinessContext|undefined;if(!c){location.href='/';return}setCtx(c);const[a,b,p]=await Promise.all([supabase.from('invoices').select('id,invoice_number,total,balance_due,status,invoice_date,tax_total,customer_id').eq('business_id',c.business_id).gte('invoice_date',startFY()).lte('invoice_date',new Date().toISOString().slice(0,10)).order('invoice_date',{ascending:false}),supabase.from('expenses').select('id,amount,tax_amount,expense_date,description,vendor_id').eq('business_id',c.business_id).gte('expense_date',startFY()).lte('expense_date',new Date().toISOString().slice(0,10)).order('expense_date',{ascending:false}),supabase.from('payments').select('id,amount,direction,payment_date,method,reference,invoice_id,customer_id').eq('business_id',c.business_id).gte('payment_date',startFY()).lte('payment_date',new Date().toISOString().slice(0,10)).order('payment_date',{ascending:false})]);if(a.error||b.error||p.error)setError((a.error||b.error||p.error)?.message||'Unable to load reports');setInvoices(a.data||[]);setExpenses(b.data||[]);setPayments(p.data||[]);setLoading(false)})()},[]);
 const filteredInvoices=useMemo(()=>invoices.filter(x=>x.invoice_date>=from&&x.invoice_date<=to&&`${x.invoice_number} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[invoices,from,to,q]);
 const filteredExpenses=useMemo(()=>expenses.filter(x=>x.expense_date>=from&&x.expense_date<=to&&`${x.description||''}`.toLowerCase().includes(q.toLowerCase())),[expenses,from,to,q]);
 const filteredPayments=useMemo(()=>payments.filter(x=>x.payment_date>=from&&x.payment_date<=to&&`${x.reference||''} ${x.method}`.toLowerCase().includes(q.toLowerCase())),[payments,from,to,q]);
 const m=useMemo(()=>{const sales=invoices.filter(x=>!['draft','void'].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);const tax=invoices.filter(x=>!['draft','void'].includes(x.status)).reduce((s,x)=>s+Number(x.tax_total||0),0);const exp=expenses.reduce((s,x)=>s+Number(x.amount||0),0);const receivable=invoices.filter(x=>!['paid','void','draft'].includes(x.status)).reduce((s,x)=>s+Number(x.balance_due||0),0);const inMoney=payments.filter(x=>x.direction==='in'||x.direction==='inbound').reduce((s,x)=>s+Number(x.amount||0),0);const outMoney=payments.filter(x=>x.direction==='out'||x.direction==='outbound').reduce((s,x)=>s+Number(x.amount||0),0);return{sales,tax,exp,receivable,inMoney,outMoney,profit:sales-exp}},[invoices,expenses,payments]);
 const exportCSV=(name:string,rows:string[][])=>{const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
 const exportCAPack=()=>{const rows=[['Moneymatters CA Working Pack'],['Period',from,to],[],['Sales Register'],['Invoice','Date','Status','Total','Tax','Balance'],...invoices.filter(x=>x.invoice_date>=from&&x.invoice_date<=to).map(x=>[x.invoice_number,x.invoice_date,x.status,x.total,x.tax_total,x.balance_due]),[],['Expense Register'],['Date','Description','Amount','Tax'],...expenses.filter(x=>x.expense_date>=from&&x.expense_date<=to).map(x=>[x.expense_date,x.description,x.amount,x.tax_amount]),[],['Payment Register'],['Date','Direction','Method','Reference','Amount','Invoice'],...payments.filter(x=>x.payment_date>=from&&x.payment_date<=to).map(x=>[x.payment_date,x.direction,x.method,x.reference||'',x.amount,x.invoice_id||''])];exportCSV(`moneymatters-ca-pack-${from}-${to}.csv`,rows)};
 const openReport=(k:ReportKey)=>{setReport(k);setQ('')};
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Preparing reports…</div>;
 if(!ctx)return null;
 const reportTitle={sales:'Sales Register',expenses:'Expense Register',receivables:'Receivables',payments:'Payment Register',tax:'Tax Register'}[report];
 return <main className="min-h-screen bg-[#f5f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Business intelligence</p><h1 className="mt-1 text-3xl font-semibold">Reports</h1><p className="mt-1 text-sm text-slate-500">Ask by period and drill directly into the source transactions.</p></div><div className="flex gap-2"><button onClick={exportCAPack} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white">Export CA working pack</button><button onClick={()=>location.href='/next-workspace'} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Cockpit</button></div></header>{error&&<div className="mb-5 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Sales" value={money(m.sales)} note="Posted invoices · current FY"/><Metric title="Expenses" value={money(m.exp)} note="Recorded expenses" tone="amber"/><Metric title="Profit*" value={money(m.profit)} note="Sales less recorded expenses" tone={m.profit>=0?'green':'red'}/><Metric title="Receivable" value={money(m.receivable)} note="Open customer balances" tone="blue"/></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Profit & Loss snapshot</h2><p className="mt-1 text-xs text-slate-400">Current financial year · starting April.</p><div className="mt-5 space-y-3"><Line label="Sales" value={m.sales}/><Line label="Expenses" value={-m.exp}/><div className="border-t border-slate-200 pt-3"><Line label="Net operating result" value={m.profit} strong/></div></div><p className="mt-5 text-[11px] leading-5 text-slate-400">*Management snapshot from posted sales and recorded expenses; final statements remain ledger/year-end controlled.</p></Card><Card className="p-6"><h2 className="font-semibold">Cash movement</h2><p className="mt-1 text-xs text-slate-400">Recorded payment activity.</p><div className="mt-5 space-y-3"><Line label="Money received" value={m.inMoney}/><Line label="Money paid" value={-m.outMoney}/><div className="border-t border-slate-200 pt-3"><Line label="Net movement" value={m.inMoney-m.outMoney} strong/></div></div></Card></div>
 <Card className="mt-5 overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-semibold">Drill-down reports</h2><p className="mt-1 text-xs text-slate-400">Filter a report, inspect the source record and continue into the relevant workflow.</p></div><div className="flex flex-wrap gap-2">{([['sales','Sales'],['expenses','Expenses'],['receivables','Receivables'],['payments','Payments'],['tax','Tax']] as [ReportKey,string][]).map(([k,l])=><button key={k} onClick={()=>openReport(k)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${report===k?'bg-slate-950 text-white':'border border-slate-200 bg-white'}`}>{l}</button>)}</div></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${reportTitle.toLowerCase()}…`} className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div></div>
 <div className="divide-y divide-slate-100">{report==='sales'&&filteredInvoices.map(x=><Row key={x.id} cells={[x.invoice_number,x.invoice_date,x.status,money(x.total),money(x.tax_total),money(x.balance_due)]} onClick={()=>location.href=`/next-workspace/documents?type=invoice&id=${x.id}`}/>)}{report==='receivables'&&filteredInvoices.filter(x=>!['paid','void','draft'].includes(x.status)).map(x=><Row key={x.id} cells={[x.invoice_number,x.invoice_date,x.status,money(x.total),money(x.balance_due)]} onClick={()=>location.href=`/next-workspace/documents?type=invoice&id=${x.id}`}/>)}{report==='expenses'&&filteredExpenses.map(x=><Row key={x.id} cells={[x.expense_date,x.description||'Expense',money(x.amount),money(x.tax_amount)]}/>)}{report==='payments'&&filteredPayments.map(x=><Row key={x.id} cells={[x.payment_date,x.direction,x.method,x.reference||'—',money(x.amount)]}/>)}{report==='tax'&&filteredInvoices.map(x=><Row key={x.id} cells={[x.invoice_number,x.invoice_date,x.status,money(x.tax_total),money(x.total)]} onClick={()=>location.href=`/next-workspace/documents?type=invoice&id=${x.id}`}/>)}{report==='sales'&&<HeaderRow labels={['Invoice','Date','Status','Total','Tax','Balance']}/>} {!((report==='sales'&&filteredInvoices.length)||(report==='receivables'&&filteredInvoices.filter(x=>!['paid','void','draft'].includes(x.status)).length)||(report==='expenses'&&filteredExpenses.length)||(report==='payments'&&filteredPayments.length)||(report==='tax'&&filteredInvoices.length))&&<div className="p-10 text-center text-sm text-slate-500">No records match this report and period.</div>}</div></Card></div></main>
}
function HeaderRow({labels}:{labels:string[]}){return <div className="grid grid-cols-2 gap-3 bg-slate-50 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid-cols-6">{labels.map(x=><span key={x}>{x}</span>)}</div>}
function Row({cells,onClick}:{cells:string[];onClick?:()=>void}){return <button type="button" onClick={onClick} className={`grid w-full grid-cols-2 gap-3 px-5 py-4 text-left text-xs sm:grid-cols-6 ${onClick?'hover:bg-slate-50':''}`}>{cells.map((x,i)=><span key={i} className={i===0?'font-semibold text-slate-800':'text-slate-600'}>{x}</span>)}</button>}
function Metric({title,value,note,tone='blue'}:{title:string;value:string;note:string;tone?:'blue'|'amber'|'green'|'red'}){const c={blue:'bg-blue-50 text-blue-700',amber:'bg-amber-50 text-amber-700',green:'bg-emerald-50 text-emerald-700',red:'bg-rose-50 text-rose-700'};return <Card className="p-5"><span className={`inline-flex rounded-xl px-2 py-1 text-[10px] font-bold ${c[tone]}`}>{title}</span><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></Card>}
function Line({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between gap-3 ${strong?'font-semibold':''}`}><span className="text-sm">{label}</span><span className={value<0?'text-rose-600':''}>{money(value)}</span></div>}
