'use client';

import { useEffect, useState } from 'react';
import ReportViewerControlled from './ReportViewerControlled';
import { REPORT_TEMPLATE_MAP, REPORT_TEMPLATES } from '@/lib/reports/report-definitions-catalog';
import type { GroupKey, ReportId, StatusKey } from '@/lib/reports/report-definitions';

type SavedPreset={id:string;name:string;reportId:ReportId;from:string;to:string;range:string;groupBy:GroupKey;status:StatusKey;q:string;businessId:string;createdAt:string};

const categories=[
 {key:'Financial & Accounting',title:'Financial & Accounting',description:'Authoritative accounting command-center reports.',links:[['General Ledger','/next-workspace/accounting'],['Trial Balance','/next-workspace/accounting'],['Balance Sheet','/next-workspace/accounting']]},
 {key:'Sales & Receivables',title:'Sales & Receivables',description:'Sales activity, aging and customer collections.'},
 {key:'POS & Counter Operations',title:'POS & Counter Operations',description:'Shift settlement and tender control.'},
 {key:'Tax & Statutory',title:'Tax & Statutory',description:'Tax slabs and HSN/SAC reporting.'}
] as const;

export default function ReportsHub(){
 const[reportId,setReportId]=useState<ReportId|null>(null),[saved,setSaved]=useState<SavedPreset[]>([]),[selectedPreset,setSelectedPreset]=useState<SavedPreset|null>(null);
 const loadPresets=()=>{try{setSaved((JSON.parse(localStorage.getItem('moneymatters.report.presets')||'[]') as SavedPreset[]).slice(0,20))}catch{setSaved([])}};
 useEffect(()=>{const params=new URLSearchParams(location.search);const id=params.get('report') as ReportId|null;if(id&&REPORT_TEMPLATE_MAP.has(id))setReportId(id);loadPresets();const h=()=>loadPresets();window.addEventListener('moneymatters:report-presets-updated',h);return()=>window.removeEventListener('moneymatters:report-presets-updated',h)},[]);
 const openReport=(id:ReportId,preset?:SavedPreset)=>{const params=new URLSearchParams();params.set('report',id);if(preset){params.set('from',preset.from);params.set('to',preset.to);params.set('group',preset.groupBy);params.set('status',preset.status);params.set('q',preset.q)}history.pushState({},'',location.pathname+'?'+params.toString());setSelectedPreset(preset||null);setReportId(id)};
 const back=()=>{history.pushState({},'',location.pathname);setReportId(null);setSelectedPreset(null)};
 if(reportId)return <ReportViewerControlled reportId={reportId} initialFrom={selectedPreset?.from} initialTo={selectedPreset?.to} initialGroup={selectedPreset?.groupBy} initialStatus={selectedPreset?.status} initialQuery={selectedPreset?.q} onBack={back}/>;
 const groups=categories.map(category=>({...category,reports:REPORT_TEMPLATES.filter(x=>x.category===category.key)}));
 return <main className="min-h-[calc(100vh-100px)] bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px]">
  <header className="flex flex-col gap-4 border-b border-slate-200/80 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Business intelligence</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">FinOps Report Studio</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Pre-built statutory and operational reports with live filtering, grouping, subtotals and export.</p></div><button type="button" onClick={()=>location.href='/next-workspace'} className="rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-700">← Dashboard</button></header>
  <div className="mt-5 grid gap-5 xl:grid-cols-[230px_minmax(0,1fr)]">
   <aside className="h-fit rounded-xl border border-slate-200/80 bg-white p-2.5 shadow-[0_1px_2px_rgba(15,23,42,.03)]"><p className="px-2 pb-2 text-[9px] font-bold uppercase tracking-[.14em] text-slate-400">Report catalog</p>{categories.map(category=><div key={category.key} className="mb-1"><a href={'#'+category.key.replaceAll(' ','-').toLowerCase()} className="block rounded-lg px-2 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">{category.title}</a></div>)}<div className="mt-2 border-t border-slate-100 pt-2"><a href="#saved-custom-presets" className="block rounded-lg px-2 py-2 text-xs font-semibold text-indigo-700 hover:bg-indigo-50">Saved Custom Presets {saved.length>0&&<span className="ml-1 rounded-full bg-indigo-100 px-1.5 py-0.5 text-[9px]">{saved.length}</span>}</a></div></aside>
   <section className="space-y-7">
    {groups.map(category=><section id={category.key.replaceAll(' ','-').toLowerCase()} key={category.key}><div className="mb-3"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{category.title}</p><p className="mt-1 text-xs text-slate-500">{category.description}</p></div>
      {category.key==='Financial & Accounting'?<div className="grid gap-3 md:grid-cols-3">{category.links.map(([label,href])=><a key={label} href={href} className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.03)] hover:border-indigo-200 hover:bg-indigo-50/30"><span className="text-sm font-semibold text-slate-900">{label}</span><span className="mt-1 block text-[11px] text-slate-500">Open the authoritative accounting command center.</span><span className="mt-3 block text-[10px] font-bold text-indigo-700">Open →</span></a>)}</div>
      :<>
        {category.key==='POS & Counter Operations'?<div className="mb-3 grid gap-3 md:grid-cols-2"><a href="/next-workspace/reports/daily-cash-book" className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.03)] hover:border-indigo-200 hover:bg-indigo-50/30"><span className="text-sm font-semibold text-slate-900">Daily Cash Book</span><span className="mt-1 block text-[11px] text-slate-500">Close and reconcile the physical cash drawer for the selected day.</span><span className="mt-3 block text-[10px] font-bold text-indigo-700">Open →</span></a></div>:null}
        {category.key==='Tax & Statutory'?<div className="mb-3 grid gap-3 md:grid-cols-2"><a href="/next-workspace/reports/statutory-hub" className="rounded-xl border border-emerald-200 bg-emerald-50/30 p-4 hover:border-emerald-300"><span className="text-sm font-semibold text-slate-900">Statutory Hub</span><span className="mt-1 block text-[11px] text-slate-600">Generate GSTR-1 JSON and TallyPrime XML handoff files.</span><span className="mt-3 block text-[10px] font-bold text-emerald-700">Open →</span></a></div>:null}
        <div className="grid gap-3 md:grid-cols-2">{category.reports.map(report=><button key={report.id} type="button" onClick={()=>openReport(report.id)} className="rounded-xl border border-slate-200/80 bg-white p-4 text-left shadow-[0_1px_2px_rgba(15,23,42,.03)] transition hover:border-indigo-200 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-900">{report.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{report.description}</p></div>{report.statutory&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">STATUTORY</span>}</div><div className="mt-3 flex flex-wrap gap-1.5">{report.tags.map(tag=><span key={tag} className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-semibold text-slate-500">{tag}</span>)}</div><div className="mt-3 text-[10px] font-bold text-indigo-700">Launch report →</div></button>)}</div></>}
    </section>)}
    <section id="saved-custom-presets"><div className="mb-3"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Saved Custom Presets</p><p className="mt-1 text-xs text-slate-500">Browser-local filters and grouping only; financial data is never copied into a preset.</p></div>
      {!saved.length?<div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-xs text-slate-500">No saved report views yet. Open a report and use <b>Save View</b>.</div>:<div className="grid gap-3 md:grid-cols-2">{saved.map(preset=>{const t=REPORT_TEMPLATE_MAP.get(preset.reportId);return <div key={preset.id} className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{preset.name}</h2><p className="mt-1 text-xs text-slate-500">{t?.title||preset.reportId}</p></div><button type="button" onClick={()=>{const next=saved.filter(x=>x.id!==preset.id);localStorage.setItem('moneymatters.report.presets',JSON.stringify(next));setSaved(next)}} className="text-[10px] font-semibold text-slate-400 hover:text-rose-600">Delete</button></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px] text-slate-500"><span>{preset.from} → {preset.to}</span><span>{preset.groupBy==='none'?'No grouping':'Group: '+preset.groupBy}</span></div><button type="button" onClick={()=>openReport(preset.reportId,preset)} className="mt-3 w-full rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white">Launch preset</button></div>})}</div>}
    </section>
   </section>
  </div>
 </div></main>;
}
