'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, type BusinessContext } from '@/lib/supabase';

type Template = { id: string; document_type: string; template_key: string; template_name: string; description: string | null };
type Brand = { name: string; legal_name: string; tax_registration_number: string; brand_primary_color: string; brand_secondary_color: string; brand_accent_color: string; logo_storage_path: string | null; logo_original_filename: string | null };

const moneySafe = (v: string) => v.trim();

function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,.05)] ${className}`}>{children}</section>}
function Field({label,children,help}:{label:string;children:React.ReactNode;help?:string}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}{help&&<span className="mt-1.5 block text-[11px] leading-4 text-slate-400">{help}</span>}</label>}
function Input(props:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-slate-400 focus:ring-2 focus:ring-slate-100 ${props.className||''}`}/>}
function Button({children,onClick,disabled=false,secondary=false}:{children:React.ReactNode;onClick?:()=>void;disabled?:boolean;secondary?:boolean}){return <button onClick={onClick} disabled={disabled} className={`rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${secondary?'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50':'bg-slate-950 text-white hover:bg-slate-800'}`}>{children}</button>}

export default function BrandingPage(){
 const [ctx,setCtx]=useState<BusinessContext|null>(null),[loading,setLoading]=useState(true),[brand,setBrand]=useState<Brand|null>(null),[templates,setTemplates]=useState<Template[]>([]),[type,setType]=useState('invoice'),[selected,setSelected]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[logoUrl,setLogoUrl]=useState('');
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return}const r=await supabase.rpc('get_my_business_context');const c=r.data?.[0] as BusinessContext|undefined;if(!c){location.href='/';return}setCtx(c);const [b,t]=await Promise.all([supabase.from('businesses').select('name,legal_name,tax_registration_number,brand_primary_color,brand_secondary_color,brand_accent_color,logo_storage_path,logo_original_filename').eq('id',c.business_id).single(),supabase.from('document_templates').select('id,document_type,template_key,template_name,description').eq('is_active',true).order('document_type').order('template_name')]);setBrand(b.data as Brand);setTemplates(t.data||[]);if(b.data?.logo_storage_path){const{data}=supabase.storage.from('business-branding-public').getPublicUrl(b.data.logo_storage_path);setLogoUrl(data.publicUrl)}})().finally(()=>setLoading(false))},[]);
 const current=useMemo(()=>templates.filter(t=>t.document_type===type),[templates,type]);
 async function saveBrand(){if(!ctx||!brand)return;setBusy(true);setError('');setMessage('');const r=await supabase.from('businesses').update({name:moneySafe(brand.name),legal_name:moneySafe(brand.legal_name)||null,tax_registration_number:moneySafe(brand.tax_registration_number)||null,brand_primary_color:brand.brand_primary_color,brand_secondary_color:brand.brand_secondary_color,brand_accent_color:brand.brand_accent_color}).eq('id',ctx.business_id);if(r.error)setError(r.error.message);else setMessage('Business identity and brand colours saved.');setBusy(false)}
 async function uploadLogo(file:File){if(!ctx)return;setBusy(true);setError('');setMessage('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Use PNG, JPG or WebP.');setBusy(false);return}if(file.size>5*1024*1024){setError('Logo must be 5 MB or smaller.');setBusy(false);return}const path=`${ctx.business_id}/logo-${Date.now()}.${file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg'}`;const up=await supabase.storage.from('business-branding-public').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up.error){setError(up.error.message);setBusy(false);return}const meta=await supabase.from('businesses').update({logo_storage_path:path,logo_original_filename:file.name,logo_mime_type:file.type,logo_updated_at:new Date().toISOString()}).eq('id',ctx.business_id);if(meta.error){setError(meta.error.message);setBusy(false);return}await supabase.from('business_brand_assets').update({is_active:false}).eq('business_id',ctx.business_id).eq('asset_type','logo');await supabase.from('business_brand_assets').insert({business_id:ctx.business_id,asset_type:'logo',storage_path:path,mime_type:file.type,original_filename:file.name,is_active:true});const{data}=supabase.storage.from('business-branding-public').getPublicUrl(path);setLogoUrl(data.publicUrl);setBrand(x=>x?{...x,logo_storage_path:path,logo_original_filename:file.name}:x);setMessage('Logo uploaded. It is now linked to this business and will be reused by its documents.');setBusy(false)}
 async function chooseTemplate(t:Template){if(!ctx)return;setBusy(true);setError('');const r=await supabase.from('business_document_preferences').upsert({business_id:ctx.business_id,document_type:t.document_type,template_id:t.id,primary_color:brand?.brand_primary_color||'#0f172a',secondary_color:brand?.brand_secondary_color||'#e2e8f0',accent_color:brand?.brand_accent_color||'#2563eb',text_color:'#0f172a',background_color:'#ffffff',font_family:'Inter',show_logo:true,show_business_address:true,show_tax_details:true,show_payment_qr:true,show_payment_link:true,show_signature:true,show_terms:true,custom_fields:{}},{onConflict:'business_id,document_type'});if(r.error)setError(r.error.message);else{setSelected(s=>({...s,[type]:t.id}));setMessage(`${t.template_name} selected for ${type}.`)}setBusy(false)}
 if(loading||!brand)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Loading business branding…</div>;
 return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Business control centre</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Branding & documents</h1><p className="mt-1 text-sm text-slate-500">One business identity drives every quotation, invoice and receipt.</p></div><Button secondary onClick={()=>location.href='/'}>Back to workspace</Button></header>
 <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className="space-y-5"><Card className="p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Business identity</h2><p className="mt-1 text-xs text-slate-400">Stored against this business, not globally against your login.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[11px] font-semibold text-emerald-700">Business-scoped</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Business name"><Input value={brand.name} onChange={e=>setBrand({...brand,name:e.target.value})}/></Field><Field label="Legal name"><Input value={brand.legal_name||''} onChange={e=>setBrand({...brand,legal_name:e.target.value})}/></Field><Field label="GST / tax registration"><Input value={brand.tax_registration_number||''} onChange={e=>setBrand({...brand,tax_registration_number:e.target.value})}/></Field></div><div className="mt-5 flex flex-wrap gap-3"><Field label="Primary"><Input type="color" value={brand.brand_primary_color} onChange={e=>setBrand({...brand,brand_primary_color:e.target.value})} className="h-11 p-1"/></Field><Field label="Secondary"><Input type="color" value={brand.brand_secondary_color} onChange={e=>setBrand({...brand,brand_secondary_color:e.target.value})} className="h-11 p-1"/></Field><Field label="Accent"><Input type="color" value={brand.brand_accent_color} onChange={e=>setBrand({...brand,brand_accent_color:e.target.value})} className="h-11 p-1"/></Field></div><div className="mt-6"><Button disabled={busy} onClick={saveBrand}>{busy?'Saving…':'Save identity'}</Button></div></Card>
 <Card className="p-6"><h2 className="text-lg font-semibold">Business logo</h2><p className="mt-1 text-xs text-slate-400">PNG, JPG or WebP · max 5 MB. The document renderer should fit it into its allocated logo box automatically.</p><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-32 w-48 place-items-center overflow-hidden rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4">{logoUrl?<img src={logoUrl} alt="Business logo" className="max-h-full max-w-full object-contain"/>:<span className="text-xs text-slate-400">No logo uploaded</span>}</div><div><input id="logo" type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)uploadLogo(f)}}/><label htmlFor="logo" className="inline-flex cursor-pointer rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{logoUrl?'Replace logo':'Upload logo'}</label>{brand.logo_original_filename&&<p className="mt-2 text-xs text-slate-400">{brand.logo_original_filename}</p>}</div></div></Card></div>
 <Card className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-semibold">Document templates</h2><p className="mt-1 text-xs text-slate-400">Five or more templates per document type can be offered without changing business data.</p></div><div className="flex rounded-xl bg-slate-100 p-1">{['quotation','invoice','receipt'].map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize ${type===x?'bg-white shadow-sm':'text-slate-500'}`}>{x}</button>)}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{current.map(t=>{const active=selected[type]===t.id;return <button key={t.id} onClick={()=>chooseTemplate(t)} className={`group rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 hover:shadow-lg ${active?'border-slate-950 ring-2 ring-slate-100':'border-slate-200'}`}><div className="aspect-[4/3] overflow-hidden rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="h-3 w-2/5 rounded bg-slate-900"/><div className="mt-3 h-2 w-full rounded bg-slate-200"/><div className="mt-2 h-2 w-4/5 rounded bg-slate-200"/><div className="mt-5 grid grid-cols-3 gap-2"><span className="h-10 rounded bg-white"/><span className="h-10 rounded bg-white"/><span className="h-10 rounded bg-white"/></div><div className="mt-4 ml-auto h-2 w-1/3 rounded bg-slate-300"/></div><div className="mt-3 flex items-center justify-between gap-2"><div><b className="block text-sm">{t.template_name}</b><span className="text-[11px] text-slate-400">{t.description||'Professional business document'}</span></div>{active&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Selected</span>}</div></button>})}{!current.length&&<div className="col-span-full rounded-2xl bg-slate-50 p-10 text-center text-sm text-slate-400">No active {type} templates are configured yet.</div>}</div><div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4"><b className="text-sm">Brand preview</b><div className="mt-3 rounded-xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="h-7 w-24 rounded" style={{background:brand.brand_primary_color}}/><div className="h-3 w-20 rounded" style={{background:brand.brand_accent_color}}/></div><div className="mt-5 h-2 w-1/2 rounded bg-slate-200"/><div className="mt-2 h-2 w-4/5 rounded bg-slate-100"/><div className="mt-6 flex gap-2"><span className="h-2 w-16 rounded" style={{background:brand.brand_secondary_color}}/><span className="h-2 w-10 rounded" style={{background:brand.brand_accent_color}}/></div></div></div></Card></div>
 {message&&<div className="fixed bottom-5 right-5 z-50 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white shadow-2xl">{message}</div>}{error&&<div className="fixed bottom-5 left-5 z-50 max-w-md rounded-2xl bg-rose-600 px-5 py-3 text-sm font-semibold text-white shadow-2xl">{error}</div>}
 </div></main>
}
